### ISSUE TITLE
Unwanted line breaks and p tags being added to front end html code when gutenberg is activated

### ISSUE THREAD

**Issue by loratov** [WordPress/gutenberg#11758]
**Describe the bug**
We have a lot of html in the tinymce editor and just by turning on the gutenberg plugin  it renders the html on the front end incorrectly. It adds break tags in unwanted places, wraps p tags around elements, strips span elements... Gutenberg v4.2.0

**To Reproduce**
1. Input html in the text tab of tinymce editor in classic version (example html below)
2. View html on front end - it appears in same format as was inputted
3. Activate Gutenberg plugin
4. View html on front end - breaks have been added, paragraph tags now surround the image tag...

Example HTML: 
```
<div class="col-sm-6 col-md-4 carousel-item">
<p class="text">testing</p>
<img src="https://via.placeholder.com/350x150" />
  <a href="http://localhost:8080/">
    <img src="https://via.placeholder.com/350x150" />
    <span>Lorem Ipsum</span>
  </a>
  <a class="animarrow" href="http://localhost:8080">Read More</a>
</div>
```

**Expected behavior**
I expect the html output to be the same as it is in the editor. 

**Screenshots**
Classic Editor: 
![classic](https://user-images.githubusercontent.com/37795755/48350384-a8b5d200-e68f-11e8-90af-fd5de2a05fa7.png)

Gutenberg Editor: 
![gutenberg](https://user-images.githubusercontent.com/37795755/48350393-aeabb300-e68f-11e8-920e-060da62f0d8e.png)

**Comment by designsimply** [comment]
I tested but cannot confirm a bug. In my test, I used WordPress 4.9.8 without Gutenberg installed at all and found the exact same result you are showing.

I entered your sample HTML into a post while Gutenberg was completely uninstalled:

```
<div class="col-sm-6 col-md-4 carousel-item">
<p class="text">testing</p>
<img src="https://via.placeholder.com/350x150" />
  <a href="http://localhost:8080/">
    <img src="https://via.placeholder.com/350x150" />
    <span>Lorem Ipsum</span>
  </a>
  <a class="animarrow" href="http://localhost:8080">Read More</a>
</div>
```

I published the post and viewed it on the front-end using Chrome 70.0.3538.77 on macOS 10.13.6 and saw the same output with the extra `<p>` and `<br>` tags as you've noted above:

```
<div class="col-sm-6 col-md-4 carousel-item">
<p class="text">testing</p>
<p><img src="https://via.placeholder.com/350x150"><br>
  <a href="http://localhost:8080/"><br>
    <img src="https://via.placeholder.com/350x150"><br>
    <span>Lorem Ipsum</span><br>
  </a><br>
  <a class="animarrow" href="http://localhost:8080">Read More</a>
</p></div>
```

If I go back and look at the text editor in the classic editor (without Gutenberg installed), then I see the code entered exactly. However, if I view how the browser renders the code while using the classic editor, I see the extra `<p>` and `<br>` tags you've referenced:

![screen shot 2018-11-12 at 7 30 19 am](https://user-images.githubusercontent.com/1119271/48353653-302e2180-e64d-11e8-8125-cff61b5f6e77.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=15662&action=edit running WordPress 4.9.8 using Chrome 70.0.3538.77 on macOS 10.13.6.</sup>

I think what you are seeing is the browser render valid HTML in place of what you have entered and I think that is the expected behavior.

**Comment by loratov** [comment]
I am referring to how the html is rendered on the front end of the page, not the visual tab. The front end of the page, when gutenberg is not installed, renders correctly. If I switch to the visual tab then I do see the extra tags being added but it still does not render that way when I view the front end of the page. 

When Gutenberg is installed, however, it renders the added elements on the front end of the page. 

We use the text editor instead of the visual editor in the majority of our website and this seems to be incompatible with Gutenberg just when the plugin is installed.

**Comment by designsimply** [comment]
Sorry for the confusion. I included that to show that the classic editor itself has the same result rendered in the browser. I ran the test again with classic only, no Gutenberg installed at all ([screenshot](https://user-images.githubusercontent.com/1119271/48354907-1215f080-e650-11e8-9e76-f1dc638a0e6f.png)), and WordPress 4.9.8 and here is the result:

Video: [38s](https://cloudup.com/c8on5eIJejS)

![screen shot 2018-11-12 at 7 52 17 am](https://user-images.githubusercontent.com/1119271/48354891-0aeee280-e650-11e8-91be-ebd5f7769251.png)

I think I made a mistake about the HTML though. It is valid. I wonder if WordPress is adding the extra tags separate from Gutenberg though?

**Comment by designsimply** [comment]
I tested again and I think Gutenberg can solve this problem for you. If you use the Custom HTML block, the extra tags don't appear:

![screen shot 2018-11-12 at 8 07 48 am](https://user-images.githubusercontent.com/1119271/48355823-1ba05800-e652-11e8-9d88-f080222ac242.png)

![screen shot 2018-11-12 at 8 07 30 am](https://user-images.githubusercontent.com/1119271/48355855-34a90900-e652-11e8-9680-f56e4d1629ed.png)

**Comment by loratov** [comment]
I forgot to mention we removed the wpautop from the_content. Can you try to reproduce the issue with this removed? 
remove_filter( 'the_content', 'wpautop' );

**Comment by xavivars** [comment]
Just a comment: what you are seeing in the console is not _necessarily_ what is being rendered originally (html returned by WordPress), but after Chrome converts it to a DOM tree.

Usually, it's the same thing, but if you really want to see if that exists, you'll beter do a "view-source"

**Comment by lkraav** [comment]
@xavivars yes, that's also involved, but underlying cause of broken paragraph tags is usually https://core.trac.wordpress.org/ticket/14050

**Comment by designsimply** [comment]
#11895 was just reported and has a clear set of steps including `wpautop` and I would like to consolidate to that issue to continue working on it there.

@loratov I see that you noted you tested with Gutenberg 4.2.0. May I also ask you to reply here to note what version of WordPress you're testing with (is it 4.9.8)?
