### ISSUE TITLE
Video thumbnails are not visible in iPhone devices

### ISSUE THREAD

**Issue by kmrpankaj** [WordPress/gutenberg#13020]
**Describe the bug**
Video thumbnails are not visible in the iPhone and iPad devices.

**To Reproduce**
1. Create a new page or post.
2. Click on the 'Add Video' icon to upload a video in mp4 format.
3. Save the page.
4. Open the page in an iPhone/iPad device.

**Expected behavior**
An auto-generated video thumbnail should appear as it does in the desktop browser in Chrome or Firefox.

**Screenshots**
https://snag.gy/qdI3gn.jpg
https://snag.gy/8jIVwn.jpg

**Smartphone (please complete the following information):**
 - Device: iPhone6, iPad Air 2
 - OS: iOS 12.1.1
 - Browser: Safari
 - Version: 12

**Comment by kosiew** [comment]
@swissspidy, 
Is there an update on this?

**Comment by swissspidy** [comment]
@kosiew I wouldn't know. I just added some labels to indicate that this needs to be tested.

If someone could provide a video that can be used for testing, that would help.

**Comment by talldan** [comment]
This seems like a limitation deliberately imposed on mobile safari. Other browsers load the first frame to use as the default video `poster` when a `poster` isn't set, but mobile safari doesn't. Mobile safari probably does this to limit bandwidth usage on mobile.

The best workaround at the moment would be to set a poster image in the block's sidebar.

The question is, should Gutenberg provide 'fix' the shortcomings of mobile safari by providing a `poster`?

**Comment by swissspidy** [comment]
> The question is, should Gutenberg provide 'fix' the shortcomings of mobile safari by providing a `poster`?

I have a  working fork of the video block's edit component that extracts a video's  first frame and sets it as a poster automatically, in case that would be of interest.

**Comment by karmatosed** [comment]
@swissspidy that sounds super interesting, would you want to add this as a new PR?

**Comment by JoshuaGoode** [comment]
Worked with some folks having issues with this today. Routed them to manually set a poster image for now.

**Comment by ajaykj** [comment]
I had a user today having the same issue. In this case, they added the video to a `Media/ Text` block.

**Comment by swissspidy** [comment]
> I have a working fork of the video block's edit component that extracts a video's first frame and sets it as a poster automatically, in case that would be of interest.

In case anyone is interested in this, here  are the details:

The core is this function that extracts the video’s first frame: https://github.com/google/web-stories-wp/blob/1ead3db6e41f59fc2fce5c1d4948e55a1166acac/assets/src/edit-story/app/media/utils/getFirstFrameOfVideo.js

We’ve improved it over time, and tested it against all major browsers with no issues.

Then there is the part that takes the frame and uploads it to WordPress: https://github.com/ampproject/amp-wp/blob/1.4/assets/src/stories-editor/helpers/uploadVideoFrame.js#L41-L80

What it does:

1. upload frame
2. update video to set frame as featured_media.
3. Optional: use custom meta key (`amp_is_poster` in this case) to hide the poster from the media library. Otherwise when you upload 10 videos, 10 posters will be generated fro them and you end up with 20 items in the media library.

Last, the hook in the block’s edit component that does all this whenever a new video is added that does not yet have a poster: https://github.com/ampproject/amp-wp/blob/1.4/assets/src/stories-editor/components/custom-video-block-edit.js#L165-L181

**Comment by autumnfjeld** [comment]
hc-8895299-hc follow up on ticket 1653510-zen

**Comment by autumnfjeld** [comment]
I tried to reproduce this on a WordPress.com site, but could not.  The video appeared with a still image showing (however could that have been the first frame of the video, rather than the poster image?). I could see a still image in a video frame when I viewed my page/post on my iPhone.  Could someone else confirm that the issue is resolved? Perhaps @swissspidy?  😄 

* iPhoneX
* iOS v 13.6.1
* Safari
 

The steps I took:

* Go to my existing WordPress.com site (Business Plan) on my desktop browser
* Create a new post, insert a new video block
* Upload an .mp4 video
* Publish the post
* View the post live on my iPhone in Safari
* See the video with a still image showing (no blank screens like shown in comments above)

![Video thumbnail – 🤓](https://user-images.githubusercontent.com/5665959/95947524-8956ef00-0e3a-11eb-825d-78d98f46fba3.png)

**Comment by swissspidy** [comment]
The issue js NOT resolved. Still happens as you can see on this screenshot:
 
![40D0C079-7CAC-465E-96BA-64C1A3504D58](https://user-images.githubusercontent.com/841956/96128516-c2a06500-0ef5-11eb-9530-8a773b1a0e60.jpeg)

**Comment by synora** [comment]
Another report at 3670516zen.

**Comment by synora** [comment]
I'm still able to replicate this bug as a report came in from a WordPress.com user. I've suggested they manually set a post image as a workaround.

**Comment by autumnfjeld** [comment]
If we did want to to compensate for the "shortcomings" of mobile Safari (@talldan has a good [point](https://github.com/WordPress/gutenberg/issues/13020#issuecomment-543043544) of questioning that)

I'd suggest a spike to explore how to tweak the behavior in the browser rather than extracting/generating and using images for the poster.  One solution could be to autoplay the video "behind the scenes" which should 🤞  trigger the native behavior of generating the video thumbnail. A rough outline of programmatic steps:  1) trigger autoplay 2) pause 3) set video back to t=0. All this can be done in milliseconds.

Another approach: add a time param to the video file url, like this https://muffinman.io/blog/hack-for-ios-safari-to-display-html-video-thumbnail/

**Comment by swissspidy** [comment]
As pointed out in https://github.com/WordPress/gutenberg/issues/13020#issuecomment-543043544, Safari probably does this to save bandwidth. Now we'd want to waste a user's bandwidth by trying to work around this?
What if a user deliberately turned on low data usage mode on their smartphone/tablet? I would rather load a poster image instead of tricking the browser into preloading a potentially large video.

**Comment by lsl** [comment]
The other approach linked above solves that problem I think.

> By simply adding #t=0.001 at the end of the video file url, we are telling the browser to skip the first millisecond of the video. When you do this, even iOS Safari will preload and show that specific frame to the user.

I don't have access to iOS to confirm but if that works and doesn't impact data usage negatively its probably a good choice for a fix. 

While *far* from concrete evidence, the [implementer notes on w3c](https://www.w3.org/TR/media-frags/#media-fragment-servers) sound like only the closest frames are likely to be served up for preview. Still, hard to say what actually happens in practice.

**Comment by hanene2030** [comment]
add #t=0.001 at the end of the video url

https://muffinman.io/blog/hack-for-ios-safari-to-display-html-video-thumbnail/

**Comment by jordesign** [comment]
Confirming that this issue is still present in Mobile Safari. Given this is a browser/device level decision, and there's no activity on this issue in almost two years - I'm going to close this issue unless I hear otherwise within the next 2 weeks.
