### ISSUE TITLE
List Block - Cannot update after deleting last empty list item

### ISSUE THREAD

**Issue by JavonDavis** [WordPress/gutenberg#13864]
**Describe the bug**
Before or after publishing a blog post with a list that has the last item being empty, simply removing that item does not autosave, update in preview or allow the user to press the update button or update the post in preview.

**To Reproduce**
1. Create a list block with the last item being empty
2. Either save, publish or preview
3. Remove empty list item
4. Update the post or preview
5. Should still see the empty list item

**Expected behavior**
Empty list item should be removed

**Screenshots**
<img width="1558" alt="screen shot 2019-02-13 at 11 36 37 am" src="https://user-images.githubusercontent.com/6520461/52728437-4cf82f00-2f85-11e9-81fc-4c94580bc083.png">

<img width="1555" alt="screen shot 2019-02-13 at 11 36 50 am" src="https://user-images.githubusercontent.com/6520461/52728473-57b2c400-2f85-11e9-94b7-56de5aead791.png">

**Desktop:**
 - OS: MacOS Mojave 10.14.2
 - Browser: Chrome
 - Version: 72

**Additional context**
- Gutenberg editor from a .com site

**Comment by youknowriad** [comment]
I'm pretty sure this is fixed by #13697 but needs testing cc @iseulde

**Comment by youknowriad** [comment]
Yes, this seems fixed for me in master.

**Comment by iseulde** [comment]
😄😄😄

**Comment by JavonDavis** [comment]
Thanks @youknowriad!

**Comment by arunsathiya** [comment]
I am afraid this is still reproducible. I just tested on `master` branch, and as @JavonDavis noted, the update button is not clickable on removing the last empty list item. 

Likewise, clicking outside the block (to make the `update` button clickable), and clicking on it does not seem to remove the empty list item. On the preview/live view, the empty list item can be noted to be visible.

Tested on Google Chrome Version 72.0.3626.109 (Official Build) (64-bit) with macOS 10.14.2 - Mac OS Mojave. Here is a [video](https://cloudup.com/cDejitbSg_W) of the entire process.

**Comment by youknowriad** [comment]
Reopening for further investigation

**Comment by ellatrix** [comment]
I cannot reproduce this issue, also not after doing the steps in the video.

**Comment by oxyc** [comment]
Also tested this and cannot reproduce. Are you sure you were using the master branch @arunsathiya? there's supposed to be a _Gutenberg_ menu item in the side menu when the plugin is active but you don't have it in your video.
