### ISSUE TITLE
Scheduled YouTube videos will not embed in YouTube Block

### ISSUE THREAD

**Issue by kathymillatt** [WordPress/gutenberg#14067]
**Describe the bug**
I can embed any YouTube video that is already published using the YouTube embed block.  However, I don't embed published videos, I embed scheduled YouTube videos that have yet to be published and schedule my post to coincide.  

**To Reproduce**
1. Go to your own site
2. Click on embed YouTube video block
3. Try to embed the url of a scheduled but not yet published YouTube video
4. See error where it says "Sorry, we could not embed that content."

**Expected behavior**
I expect the link to embed and the greyed out video to be shown. 
The link will not embed and when I preview the page, there is the link showing in plain text but no video

**Screenshots**
<img width="1263" alt="screenshot 2019-02-23 15 11 52" src="https://user-images.githubusercontent.com/47922029/53288175-5d768980-377d-11e9-969a-a4bbade94f7f.png">

Link only shows in scheduled post

**Desktop (please complete the following information):**
 - OS: Mac latest version iOS
 - Browser Safari
 - Version latest

**Additional context**
- Gutenberg 5.1

**Comment by swissspidy** [comment]
I think this boils down to the [fact](https://core.trac.wordpress.org/ticket/14759) that WordPress caches oEmbed responses indefinitely.

So, in your case, you enter the URL for a video which basically does not exist (yet). WordPress stores that information ("video not found") in the database and does not attempt to embed it again for that reason.

If there was no such caching, WordPress would try to embed the scheduled video on every page load until it finally gets published on YouTube.

At the moment there is no way to invalidate that oEmbed cache in WordPress out of the box, but there are [suggestions](https://core.trac.wordpress.org/ticket/30720) to add something like that.

**Comment by kathymillatt** [comment]
I’ve published my first post with a scheduled YouTube video and it still just shows the link. I was hoping it would show a video as the blog post is posted after the video has gone live. 
Now I can’t even get it to show it despite updating the post.

**Comment by scottwyden** [comment]
It would be nice for the block editor to get past this. I know if you're using Jetpack then it pulls in scheduled videos, so I'd imagine there is a way to make it work.  More so for the caching issue than for anything else.

**Comment by amberhinds** [comment]
We came upon this on our podcast site and had to write a plugin that resets the oembed cache when a post transitions from scheduled to published status. So as long as the scheduled YouTube video is published before the post publishes, then it fixes this issue. 

It seems a lot like this issue should be tagged as a bug, not an enhancement.

**Comment by SteveJonesDev** [comment]
Here is the solution we came up with for our use case. https://github.com/equalizedigital/oembed-cleaner

The main issue here is that the oEmbed meta cache is persistent and is never retried, even when a post is updated.

In this case the YouTube video isn't yet public and WordPress stores the meta cache as `{{unknown}}`. Caching a persistent failed value like this that is only clearable by modifying the database directly or modifying the video URL doesn't seem like the best approach. Ideally is would retry at the very least on post update.

**Comment by swissspidy** [comment]
I still see this is as an enhancement because it's quite an edge case (embeds are rarely time-based or scheduled) and could have unintended side effects too (your post content changes without you knowing). So that plugin seems like a good route.

Anyhow, this is not really a block editor specific issue, so this is better discussed at https://core.trac.wordpress.org/ in the Embeds component.

**Comment by Mamaduka** [comment]
I agree with @swissspidy; the issue is unrelated to the editor. The core block just sends a request to the server, which returns embed previews based on the provider.

Closing in favor of https://core.trac.wordpress.org/ticket/30720.
