### ISSUE TITLE
Search widget input and button style unbalanced

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#17593]
Since beta 1 the following is what you see for search widget:

![image](https://user-images.githubusercontent.com/253067/65646313-9e27d100-dff2-11e9-8079-7aaf7c7a2560.png)

Ideally, the 'search' action would be dominant whereas the input is.

**Comment by karmatosed** [comment]
I think this is also the same problem here:

![image](https://user-images.githubusercontent.com/253067/65682262-808a5400-e052-11e9-98a5-e131fcb5a069.png)

Oddly we seem to have gained spacing here that also I don't think was before.

**Comment by epiqueras** [comment]
>Ideally, the 'search' action would be dominant whereas the input is.

I'm not sure what that means. Should the button be a primary button?

>Oddly we seem to have gained spacing here that also I don't think was before.

I am not seeing this on `master`. Do you think it's fixed now? Or maybe it's browser specific?

**Comment by karmatosed** [comment]
> I'm not sure what that means. Should the button be a primary button?

Yes or the most dominant visually. The way this styling has been done (which might be inherited from core styling changes) the button is less dominant visually.

![image](https://user-images.githubusercontent.com/253067/65820433-c9900300-e220-11e9-9341-cdbbd9509011.png)

The above is what I am still seeing on the trunk of WordPress and latest Gutenberg included.

**Comment by jasmussen** [comment]
Turns out this is not a regression. Shipping WordPress:

<img width="268" alt="Screenshot 2019-09-30 at 12 04 30" src="https://user-images.githubusercontent.com/1204802/65869438-c0b34480-e37a-11e9-996a-57cad1357c7e.png">

Nightly:

<img width="279" alt="Screenshot 2019-09-30 at 12 04 47" src="https://user-images.githubusercontent.com/1204802/65869445-c4df6200-e37a-11e9-8eb2-cda45abfdbaf.png">

(note that the weird dropdown is being worked on in https://core.trac.wordpress.org/ticket/47477)

So I would not necessarily call this a super urgent fix. However it is an _easy_ fix. Here's a little Flex magic:

<img width="313" alt="Screenshot 2019-09-30 at 12 06 07" src="https://user-images.githubusercontent.com/1204802/65869494-dc1e4f80-e37a-11e9-8b4a-d9485713b056.png">

I'll put that in a separate PR.

**Comment by jasmussen** [comment]
So, I missed the search widget part of this, and looked only at the font size picker. Looking at the other now.

**Comment by jasmussen** [comment]
Polished the search widget in #17648. Turns out the search widget would always grow infinitely, but perhaps it's just waaay more visible now that we're testing everything for the beta process — the main body content column used to be way thinner and has grown with the Twenty themes, making the effect more pronounced.
