### ISSUE TITLE
Clicking into text blocks doesn't always allow you to edit. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#19731]
**Describe the bug**

Using the latest version of `master`, I've noticed that sometimes I'm unable to click into RichText blocks and edit them (Paragraph, Header, List, etc.). 

I haven't been able to track down exact replication steps yet, but I've seen it happen a handful of times now, usually while composing longer posts. When it occurs, the only remedy I've found is to save the post and reload the page. 

**Screenshots**

In the GIF below, it's possible to edit the code block, but not the paragraph block:

![editing](https://user-images.githubusercontent.com/1202812/72635650-4b6c7f00-392b-11ea-88ac-ddb1fb2887ed.gif)

**Desktop (please complete the following information):**
 - MacOS 10.15.2
- Safari 13.0.4

**Comment by simison** [comment]
Happens to me quite often with Macos Firefox and Chrome.

**Comment by talldan** [comment]
Yes, I noticed this for the first time yesterday as well with the navigation block. It seemed to be ok for the first few clicks and then started happening. Raising the priority as this seems like an important bug to fix.

**Comment by ellatrix** [comment]
When do you think it started happening? Did you select multiple blocks right before?

**Comment by ellatrix** [comment]
I suspect it's related to multi selection no re-enabling the rich text fields but I wonder what is triggering it.

**Comment by kjellr** [comment]
> When do you think it started happening? Did you select multiple blocks right before?

For me, It seems to happen just in the course of clicking in and out of individual blocks, not rearranging or selecting multiple blocks.

**Comment by ellatrix** [comment]
Could someone test again with the latest `master` or the latest Gutenberg release? I have a feeling that #19720 might have fixed the issue. Otherwise I'll investigate further.

I reproduced it (don't know the steps) with 7.2.0, so it’s not a regression in 7.3.0. I did see that editing was disabled, so it definitely has to do with multi selection (attempts).

**Comment by talldan** [comment]
I'm still experience it on master @ellatrix. It takes a lot of clicking around for it to happen.

I think it must be related to the code in the PR you linked to, particularly the `node.removeAttribute( 'contenteditable' );` part. The paragraphs that had the bug didn't have the `contenteditable` attribute set. I think this is causing the RichText's `onFocus` not to trigger, meaning the `selectionChange` action isn't called.

**Comment by ellatrix** [comment]
Thanks for testing! I'll look into it today

**Comment by ellatrix** [comment]
#19839 should fix thee issue.

**Comment by AdrienM76** [comment]
If it helps any, I am able to reproduce it consistently simply by trying to move a block using the move widget. (not sure what it is called) I'm not familiar with installing and testing master, but I'll see what I can do.

**Comment by ZebulanStanphill** [comment]
This looks like it may be the same issue as #18977. #19839 appears to fix both, so I guess they are the same, or at least both caused by the same root problem.

**Comment by OceanWind** [comment]
This is still an issue with the block editor in WordPress v5.8.1. It seems to be related to copying multiple blocks. Once that's done, clicking into certain blocks does not allow you to edit the text. If you delete the block and undo the deletion, you can edit again.
