### ISSUE TITLE
Image block dialogue missing "Mine", "Uploaded to this post", "Unattached" filters

### ISSUE THREAD

**Issue by EvanLTD** [WordPress/gutenberg#19851]
When inserting an image via an **Image Block**, the dropdown menu of filter options is missing from the Select or Upload Media window. This is exactly the same problem as the now-resolved issue 8748, except this one pertains to images inserted via the regular image block rather than the Featured Image dialog: [https://github.com/WordPress/gutenberg/issues/8748](url)

**To Reproduce**

1. Create a Post
2. Insert an Image Block
3. Click the **Media Library** button within the block
4. Note that in the Select or Upload Media window, below the Filter Media heading, one of the dropdown menus is missing. (There should be one with options for "Images, Uploaded to this post, Mine, Unattached.")

Note that when inserting images via a **Gallery Block**, or via the **Featured Image dialog**, this filter dropdown menu DOES appear correctly. The Image Block should be made consist with those. 

Gutenberg Version 7.3.0 
WP 5.3.2

### **_How it looks now (screenshot from inserting image via Image Block:_**

<img width="379" alt="image" src="https://user-images.githubusercontent.com/34531456/73022386-853ff880-3df7-11ea-9bc3-ac6eb3ef6075.png">

**_### How it should look (screenshot from inserting Gallery or Featured Image):_**

<img width="364" alt="image" src="https://user-images.githubusercontent.com/34531456/73022456-9e48a980-3df7-11ea-80c1-b7c687d3e0ca.png">

**Comment by epiqueras** [comment]
Shouldn't this be done in Core @jorgefilipecosta?

**Comment by jorgefilipecosta** [comment]
Hi @epiqueras, the core provides the media library UI to this UI. I think The WordPress components that interact with the core media library are the place where we can address this issue.

**Comment by epiqueras** [comment]
The way #8748 was fixed was by creating a custom modal. Shouldn't this be in the default modal exposed by Core?

**Comment by jorgefilipecosta** [comment]
> The way #8748 was fixed was by creating a custom modal. Shouldn't this be in the default modal exposed by Core?

I'm not sure maybe the interface core exposes allows to enable these filters with just a flag. I will cc @joemcgill, @anthonyburchell in case they are able to provide some insights.

**Comment by anthonyburchell** [comment]
Yeah for some context here on how things were before Gutenberg, here's a screenshot of the image block equivalent flow in Classic Editor (Add Media) : 

<img width="624" alt="Screen Shot 2020-02-21 at 4 04 49 PM" src="https://user-images.githubusercontent.com/11888980/75075641-f096ec00-54c3-11ea-9c90-0b664bd4d935.png">

The changes to make this available in the image block flows would be similar to the changes in #8748. Worth noting, this would also need to be solved for inline images.

**Comment by Fu-San** [comment]
Like [#8748](https://github.com/WordPress/gutenberg/issues/8748), I think this issue should be labeled as 'Backward Compatibility' and 'Bug'. Since it is a feature that was available before.
This issue cause a lot of problems while editing an older post, as without filters, (specially 'Uploaded to this post') it's extremely tough to find images for sites that have lots of images.

**Comment by Fu-San** [comment]
@anthonyburchell @epiqueras Any fix on this? It seems still not touched and isn't assigned to anyone.

**Comment by torounit** [comment]
related: #12753

**Comment by tiagogon** [comment]
Is this planned for anytime soon?

**Comment by noisysocks** [comment]
Reported here as well: https://core.trac.wordpress.org/ticket/48797

**Comment by ssakcoR** [comment]
"Uploaded to this post" is susch a time saver! This hasn't been solved still! :/

However, it doesn't appear when creating a "Gallery" block. On a single image it doesn't. I doesn't make much sense creating a gallery block for one image only...

**Comment by matthewmcvickar** [comment]
Any idea when this might be addressed?

**Comment by dnnsjsk** [comment]
Yikes just came across this.

Any way this can be fixed in the meantime?

**Comment by dnnsjsk** [comment]
Hey, this filter seems to work for me. My conditions are a bit different, but you can probably adjust it to your needs.
```php
add_filter(
    'ajax_query_attachments_args',
    function ($query = []) {
        $user_id = get_current_user_id();
        if ($user_id && current_user_can('contributor')) {
            $query['author'] = $user_id;
        }
        return $query;
    },
    10,
    1
);
```

**Comment by netinial** [comment]
It seems this issue has been resolved at 
https://github.com/WordPress/gutenberg/pull/17410

However we confirm issue repeats again.
 
Changing Theme to default.
Disabling all Plugins does not works.

Image block dialogue missing **Filter Media** as "Mine", "Uploaded to this post", "Unattached" filters

Any chance to check issue again?

@dnnsjsk we could not applied your solution 
Do you have any chance to help us?

```
add_filter(
    'ajax_query_attachments_args',
    function ($query = []) {
        $user_id = get_current_user_id();
        if ($user_id && current_user_can('contributor')) {
            $query['author'] = $user_id;
        }
        return $query;
    },
    10,
    1
);
```

my $query 

```
add_filter(
    'ajax_query_attachments_args',
    function ($query = []) {
        press($query);
    },
    10,
    1
);
```

returns as follow


```
Array
(
    [orderby] => date
    [order] => DESC
    [posts_per_page] => 80
    [paged] => 1
    [post_type] => attachment
    [post_status] => inherit,private
)
```

What is the logic to add  $query['author'] = $user_id;
