### ISSUE TITLE
you can't insert a site-local image URL

### ISSUE THREAD

**Issue by skierpage** [WordPress/gutenberg#20903]
**Describe the bug**
I want to insert existing images on my web site, i.e. the img src attribute for them will be `/path/to/image.jpg`. But for a long time and continuing in Gutenberg 7.7.1 , the editor's (Add image) > Insert from URL won't accept/resolve a local path, it displays a tooltip "Please enter a URL."

**To reproduce**
1. Create a new post
2. Click on '+' then 'image'
3. Click 'Insert from URL'
4. Enter the full path to an existing static image on the same web site as your Wordpress and Gutenberg, and press or click the '↵' symbol.
4. See error: you get the tooltip and the mini-dialog remains up.

**Expected behavior**
The mini-dialog to insert from URL should be able to resolve the site-relative path and find the image just as it can when I include my domain name. That just seems like a bug.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora 31 Linux
 - Browser: Firefox Nightly
 - Version: 76.0a1

**Additional context**
The workaround is to insert the full URL (//mysite.com/path/to/image.jpg won't work either, I have to include the https: scheme), then switch the block to HTML mode and manually delete `https://mysite.com` from the `img src` attribute.

(I know about the WordPress Media Library.)

**Comment by paaljoachim** [comment]
Testing using WordPress 5.7 beta 1
Theme: Twenty Twenty One
WordPress Beta Tester plugin is activated.
No Gutenberg plugin activated.
A local site
Chrome

OSX 10.15.7

Testing instructions

1. Create a new post
2. Click on '+' then 'image'
3. Click 'Insert from URL'
4. Enter the full path to an existing static image on the same web site as your Wordpress and Gutenberg, and press or click the '↵' symbol.
5. See error: you get the tooltip and the mini-dialog remains up.

I made a new post. 
Clicked the + and selected Image.
Entered a local path to the same web site: https://test-site.dev.cc/wp-content/uploads/Field-grass-wheat-sky.jpg
and clicked enter/return.
Noticed no error.

I will go ahead and close this issue as it looks like it has been fixed. If I am mistaken let me know.
Thanks.

**Comment by skierpage** [comment]
> No Gutenberg plugin activated.

I'm confused, this is a Gutenberg bug.

> I made a new post.
> Clicked the + and selected Image.
> Entered a local path to the same web site: https://test-site.dev.cc/wp-content/uploads/Field-grass-wheat-sky.jpg
> and clicked enter/return.

You mean you entered /wp-content/uploads/Field-grass-wheat-sky.jpg ?
> Noticed no error.

When I do this with Wordpress 5.6.1 and Gutenberg 10.0.0 with a local image path e.g. /wordpress/wp-content/uploads/MyImage.jpg, I still encounter the bug -- I get the tooltip "Please enter a URL" and the mini-dialog remains up. So the bug is not fixed for me.

_However,_ after entering the full https://my.site.com/wordpress/wp-content/uploads/MyImage.jpg to get Gutenerg to accept the image, I can now click Replace on the image block's floating toolbar, and can then click [Edit] next to Current media URL:, and in this mini-dialog I _can_ remove the leading `https://my.site.com` in the text field and Gutenberg accepts the site-relative URL. So it's half-fixed (and this is a better workaround than switching to "Edit as HTML".

> I will go ahead and close this issue as it looks like it has been fixed. If I am mistaken let me know.
I'm not in any beta, so maybe it's fully fixed in what you're running. Hmm. I'll wait a bit to see. Thanks for checking!

**Comment by paaljoachim** [comment]
Hi @skierpage 

I will retest as I now know which WordPress version and Gutenberg plugin version you are using.

WordPress version 5.6.1 
Gutenberg plugin 10 activated 
Twenty Twenty One.

1. Create a new post
2. Click on '+' then 'image'
3. Click 'Insert from URL'
4. Enter the full path to an existing static image on the same web site as your Wordpress and Gutenberg, and press or click the '↵' symbol.
5. See error: you get the tooltip and the mini-dialog remains up.


This time I will use an online test site that I have.

I made a new post.
Clicked the "+" and then "image".
Clicked "Insert from URL"
Inserted a link to a static image in the media library of the same site. Example: 
<img width="696" alt="Screen Shot 2021-02-19 at 08 33 00" src="https://user-images.githubusercontent.com/5323259/108472494-1a2c5400-728d-11eb-8ca4-a163eed196cc.png">
URL used: https://webkonsulenten.com/wp-content/uploads/Brick-plaster-wall-floor.jpg
Clicked Enter/Return symbol:
<img width="661" alt="Screen Shot 2021-02-19 at 08 33 29" src="https://user-images.githubusercontent.com/5323259/108472559-3203d800-728d-11eb-9d7f-3ed798fa55b1.png">

Tested in Chrome and Firefox.

---------

**Comment by skierpage** [comment]
@paaljoachim you're using a full URL. I am talking about a URL without `blahblahblah.com` on the front! In the language of RFC1738 which specifies URLs, I mean no schema on the front, no colon, no host, just the `/url-path` part.

Anyway, I also continue to see the problem in chromium-browser (normally I'm on Firefox). [+] > Image > Insert from URL won't allow local image path and displays a slightly different tooltip, but an existing image block's toolbar > Replace > Current media URL [Edit] will. Please reopen this bug.

And I figured out why. The new image's Insert from URL text field with class `block-editor-media-placeholder__url-input-field` is created in [media-placeholder](https://github.com/WordPress/gutenberg/blob/0c11f0cbf4ab89b68b1db889eacf965df3f0997c/packages/block-editor/src/components/media-placeholder/index.js#L39) and is of `<input type="URL">`. This HTML5 input type won't allow a local URL path, it demands a "properly-formed absolute URL" with at least _urlscheme_://_restofurl_. So the browser is displaying the tooltip indicating invalid URL and blocking submission (no wonder I couldn't find the code for this tooltip in Gutenberg :stuck_out_tongue_winking_eye: ). Meanwhile the Replace > Current media URL text field with label `block-editor-url-input__input` is created in [url-input](https://github.com/WordPress/gutenberg/blob/70b1cde3bcf186059f0e4ee7396717046b96569b/packages/block-editor/src/components/url-input/index.js#L422) with `<input type="text">`, which allows you to enter anything as the media URL, including just `/path/to/image.jpg`.

The fix is easy: change the former component to `type="text"` to match the latter. If I edit the HTML of the web page in my browser's developer tools'  HTML inspector to make this change, the bug goes away. I'll attempt a pull request.

**Comment by paaljoachim** [comment]
Hey @skierpage 

Heck it seems like an advantage that I was not "getting" it. If the result is that you will add a pull request so it becomes fixed..:)

Thanks for clarifying!
Have a great day!
