### ISSUE TITLE
Display tags in the order added and do not reorder them on save

### ISSUE THREAD

**Issue by LeninZapata** [WordPress/gutenberg#21589]
Hi, Gutenberg is ordering the tags alphabetically after saving, I don't want it to sort the tags, I need the tags in the order that I put them, I don't want it to sort it automatically.

![ACmPOC6qta](https://user-images.githubusercontent.com/42600954/79278560-85d5b180-7e71-11ea-80ee-6fefe7cc86c8.gif)

**Comment by johngodley** [comment]
This seems to be general WordPress behaviour, rather than specific to Gutenberg, and is the same in the classic editor.

How are you using the tag order? Your theme can show the tags in any order it wants, and this will appear in your post. How it appears in the editor shouldn't change that.

**Comment by LeninZapata** [comment]
I have a plugin of related posts by tag, but the relation is not relevant because first look for the posts with the first tags stored alphabetically, and not the first main tag, that is to say for me the order of the tags are key because the first tag is the most relevant. So when saving everything, it is sorted alphabetically and this does not help me, any idea how to alter this?

**Comment by talldan** [comment]
The terms only seem to be shown alphabetically visually, but are stored in order added in the database, so I think this is really a design issue rather than a data one. It's a question of whether the best user experience is for this field to show the tags in order added or alphabetically.

That the tags are reordered on saving the post seems unusual to me.

I'll add the Needs Design Feedback label.

**Comment by LeninZapata** [comment]
According to the database structure, I currently find it complicated that this can be ordered according to the order of the user. 

What occurs to me that the IDs of the terms are stored in a metapost (only the ids) in a meta called `'_tax_tag_orden' = 23,11,1,50` then this would have the order and with that you could play around a bit, for another tax without hierarchy the meta would be `'_tax_mycuscomtax_orden' = 99,119,3,33` I suppose that there must be a filter at the moment of saving the post tags to be able to save this new metapost.

It is an idea but I think that there should be the possibility that the entered tags have the order entered. This greatly influences the related posts of plugins and themes since the first term would be the most prominent of the others.

**Comment by karmatosed** [comment]
If someone set a specific order, I think expecting them to stay in that order makes senses. I would vote to not reorder.

**Comment by LeninZapata** [comment]
You just have to add a function just after saving in, this function saves in the `wp_postmeta` table a meta called `_tax_{taxonomy}_orden` and as value the IDS of the terms ordered as the user put them.

**Comment by talldan** [comment]
Sounds like this is resolved? I'll close the issue for now, but if I'm misinterpreting then let me know.

**Comment by talldan** [comment]
I've reworded the title of this so that it can be treated as an enhancement.

#22048 has been opened since and seems very similar.

**Comment by gsarig** [comment]
I faced the same issue and saw that while there is the `wp_term_relationships` table, it doesn't get properly updated with the tags' order on post update. As a workaround, I hooked into the `rest_after_insert_this-post_type` to update the order. Here is [a more detailed explanation](https://www.gsarigiannidis.gr/wordpress-post-tags-order/) of what I did, along with some code that seems to work fine so far.

**Comment by paaljoachim** [comment]
There is a tags PR here that can be tested and commented on:
https://github.com/WordPress/gutenberg/pull/30598

**Comment by annezazu** [comment]
Noting that this still occurs in 10.6.1:


https://user-images.githubusercontent.com/26996883/118590159-237b6e80-b75f-11eb-9390-dd12ba815e61.mov

**Comment by johnlomat** [comment]
Will this be implemented in the future?

**Comment by iolugovoy** [comment]
Any updates on this?

**Comment by benborges** [comment]
any update on this ?

**Comment by ejazrasool** [comment]
This needs fixing. Reordering of tags should be a choice, not default behaviour.

**Comment by siajupiter** [comment]
This needs fixing. any update?

**Comment by madfcat** [comment]
Can we have this functionality?

@gsarig mentioned a workaround and it does what we need. But the tags still are ordered in Block Editor.
Is there a way to order them accordingly to the term order column from the DB or at least to stop sorting the tags while adding them in the Block Editor?

**UPD: The tags can be sorted from the Posts -> All Posts -> Quick Edit.**
I use this solution for now. But it is annoying that we do not have this functionality in the Block Editor. Definitely must have.

**Comment by Paktas** [comment]
The editor should **NOT** change the order of tags upon saving.
Suggest to use `term_order` column for preserving the tag sequence data.

**Comment by Mamaduka** [comment]
This was resolved via https://github.com/WordPress/gutenberg/pull/67154. See: https://github.com/WordPress/gutenberg/issues/6704#issuecomment-2759345950.
