### ISSUE TITLE
Block Patterns without a category crashes the block editor

### ISSUE THREAD

**Issue by skorasaurus** [WordPress/gutenberg#27249]
**Describe the bug**

Accessing a registered block pattern that has doesn't have a categories objects crashes the block editor. 

According to the [existing documentation](https://developer.wordpress.org/block-editor/developers/block-api/block-patterns/) , a category is not required. 

If categories is now required; it needs to be documented at https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/block-api/block-patterns.md

**To reproduce**
1. place this block pattern in your functions.php file. 

```
register_block_pattern(
	'skorasaurus/test-case-block-pattern',
	array(
		'title'       => __( 'a simple heading', 'what should this be' ),
		'description' => _x( 'mmm..cake', ' this is slang and has more nuance in english', ''),
		'content'     => '<!-- wp:heading -->
		<h2>The history of cake</h2>
		<!-- /wp:heading -->',
	)
);
```

2. create a new post or page in block-editor
3. Go to the patterns tab
4. "The editor has encountered an unexpected error." appears; and in console, the following:

```
Uncaught TypeError: t.categories is undefined
    s https://local.wordpress.test/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=fdb8c27842d6665c8f717ab07efd9458:30
    s https://local.wordpress.test/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=fdb8c27842d6665c8f717ab07efd9458:30
    s https://local.wordpress.test/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=fdb8c27842d6665c8f717ab07efd9458:30
    mountMemo https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:15577
    useMemo https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:15873
    useMemo https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react.af754d50.js:1607
    is https://local.wordpress.test/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=fdb8c27842d6665c8f717ab07efd9458:30
    renderWithHooks https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:14938
    mountIndeterminateComponent https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:17617
    beginWork https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:18731
    callCallback https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:182
    invokeGuardedCallbackDev https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:231
    invokeGuardedCallback https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:286
    beginWork$1 https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:23338
    performUnitOfWork https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:22289
    workLoopSync https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:22265
    performSyncWorkOnRoot https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:21891
    flushSyncCallbackQueueImpl https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:11224
    unstable_runWithPriority https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react.af754d50.js:2685
    runWithPriority$1 https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:11174
    flushSyncCallbackQueueImpl https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:11219
    flushSyncCallbackQueue https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:11207
    discreteUpdates$1 https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:22028
    discreteUpdates https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:803
    dispatchDiscreteEvent https://local.wordpress.test/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:4291
```

**Expected behavior**
The block pattern to load.

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", 
- If the Gutenberg plugin is installed, which version is it? 9.4.1

I was also able to replicate this with wordpress 5.6 and Gutenberg 9.5.2.

I was able to reproduce this in [Gutenberg 9.1.0](https://github.com/WordPress/gutenberg/releases/tag/v9.1.0); I was not able to reproduce this in Gutenberg 9.0.0

**Comment by skorasaurus** [comment]
There's a PR for this at #27655

**Comment by youknowriad** [comment]
Thanks for the issue, it seems we should fix the crash and not the documentation to avoid this breaking change.

**Comment by skorasaurus** [comment]
very similar issue with #27864

**Comment by pwkip** [comment]
This seems to happen with the block editor in core (without plugin enabled). Adding a category to one of the registered block patterns solves it. Will this fix be pushed to core as well?

**Comment by skorasaurus** [comment]
> This seems to happen with the block editor in core (without plugin enabled). Adding a category to one of the registered block patterns solves it. Will this fix be pushed to core as well?
> 
> Let me clarify a bit.
> 
>     * registering a block with `register_block_pattern` (without a category) works fine
> 
>     * removing all core blocks with `remove_theme_support('core-block-patterns')` works fine
> 
> 
> But the combination of the 2 crashes the editor.
> 
> Workaround: also add a category to the block

Hi @pwkip ; 

I am able to create a post when I have Gutenberg 9.9.2 activated and both register a block without a category 
and remove all core blocks as you described; are you requesting to have this backported to 5.6.x?

**Comment by pwkip** [comment]
@skorasaurus i believe the problem still exists in the gutenberg plugin again. Here's the code to reproduce the issue: https://github.com/WordPress/gutenberg/pull/27970#issuecomment-774526268

**Comment by skorasaurus** [comment]
ah, I see... I tried a different theme now (popper) and I am able to reproduce the error in Gutenberg 9.9.3. 

I was not able to reproduce this in twentytwenty; I think it is because twentytwenty ships with its own patterns as a part of the theme. 
 
To recap and to reproduce: 


1. place this block pattern in your functions.php file.


```register_block_pattern(
	'skorasaurus/test-case-block-pattern',
	array(
		'title'       => __( 'a simple heading', 'what should this be' ),
		'description' => _x( 'mmm..cake', ' this is slang and has more nuance in english', ''),
		'content'     => '<!-- wp:heading -->
		<h2>The history of cake</h2>
		<!-- /wp:heading -->',
	 )
);
```

2.  add the remove_theme_support('core-block-patterns'); into your functions.php (properly hooked in, to 'after_theme_setup')
3. create a new post or page in block-editor
4. Go to the patterns tab
5. "The editor has encountered an unexpected error." appears;

You must use a theme that does not have its own block-patterns registered. For example, you cannot use twentytwenty, twentytwentyone

**Comment by Jamiewarb** [comment]
Just ran into this error now. It's quite a puzzling issue to solve as I imagine you would register your first block pattern before registering your block pattern categories, and the two don't seem connected at first.

**Comment by ingageco** [comment]
I ran into this issue as well, and resolved it by creating a custom block pattern category. It appears that the issue may come from there being no pattern categories after the core blocks (and their categories) are removed. Maybe this is obvious, but it doesn't seem clear that at least one registered category is required when core patterns are removed.
