### ISSUE TITLE
Full-site Editing: Themes located in a subdirectory do not load template parts

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#28022]
If a theme is loaded from a subdirectory, then its template parts are not properly loaded into the site editor. For example, if the theme is located here: 

`wp-content/themes/subfolder/themename`

instead of: 

`wp-content/themes/themename`

This has come up when folks test the [TT1 Blocks theme](https://github.com/WordPress/theme-experiments/tree/master/tt1-blocks): it used to work when you copied the entire `theme-experiments` folder into `wp-content/themes`, but it no longer does. This was fixed once before in https://github.com/WordPress/gutenberg/pull/26391. 

I believe this will be fixed by https://github.com/WordPress/gutenberg/pull/27765, but opening an issue here to track the bug.

**Comment by jffng** [comment]
Is this fixed by #28088?

**Comment by jeyip** [comment]
> Is this fixed by #28088?

Yep! There is one caveat -- we need to update block themes before the issue is completely resolved. I've modified seedlet blocks [here](https://github.com/Automattic/themes/pull/3045) and block theme experiments [here](https://github.com/WordPress/theme-experiments/pull/172). I left a note in #28088 with more information, but in essence, the problem isn't entirely fixed until we remove theme attributes from block-themes.

**Comment by annezazu** [comment]
Just noting that @helen ran into this today while streaming resulting in a really jarring experience especially when trying to use the Live Preview option for block themes. When this is fixed, should confirm it works with the Live Preview option under Appearance > Themes.

**Comment by carolinan** [comment]
Template parts for themes inside subfolders are working so I am closing this issue.
