### ISSUE TITLE
Make the Author input always full width to reduce the visual change upon select

### ISSUE THREAD

**Issue by garretthyder** [WordPress/gutenberg#28180]
**Describe the bug**
With the Author input inline rather than full width when you click into it it's a little jarring as it transitions to full width and displays it's options. Would be a little cleaner to just have the input always full width.

**Screenshots**
Below is the current behaviour where clicking has the input become full width and expand. 
![62c27174896eb9f57e42bf80a52a8c42](https://user-images.githubusercontent.com/8726005/104521056-0f591200-55b1-11eb-90cf-85b4661e07b2.gif)
Below is the proposed behaviour of having the input full width so there's no width change and instead it only expanded down.
![632de77acbeed814e5075a418c08fafc](https://user-images.githubusercontent.com/8726005/104521390-a7ef9200-55b1-11eb-95ac-7410a6406e0f.gif)

**To reproduce**
1. Install WP.
2. Have more than one author.
3. Go to create a post and find the Author input in the sidebar Page tab under Status & visibility.
4. Click into the input to see the width change behaviour.

**Expected behavior**
 Would be a little cleaner to just have the input always full width.

**Editor version:**
- WordPress version: 5.6
- Gutenberg: Is irrelevant as issue is present with or without the plugin.

**Desktop:**
 - OS: MacOS Big Sur 11.1
 - Browser: Chrome 87.0.4280.141

Thank you

**Comment by adamsilverstein** [comment]
Hey @jasmussen, when you have a moment can you please look at this one as well? What do you think about making the selector full width?

**Comment by jasmussen** [comment]
Thank you for the ping!

> What do you think about making the selector full width?

I actually thought about that when tinkering with the CSS on your other PR, because the jumpiness when it works is a bit annoying. But on the other hand, it gives that input field a prominence that I'm not sure is totally warranted.

Since the jumpiness only happens when tinkering with the contents which are likely wider than the resting state, could we try and making it full-width only onselect? I.e. something like:

```
[selector] {
	transition: all .1s ease;
	@include reduce-motion("transition");
}
[selector]:focus {
	width: 100%;
}
```

In my head that should work decently, and it may of course fall flat in practice. But I think it's worth a shot!

The above may also need a `box-sizing: border-box;`, but it should already be inherited.

**Comment by JustinyAhin** [comment]
This seems to have been fixed already.

https://user-images.githubusercontent.com/33403964/113293407-9fc00c80-92ed-11eb-9a1e-46ed56f75596.mp4


**Editor version**:

- WordPress version: 5.7
- Gutenberg: Is irrelevant as issue is present with or without the plugin.

**Desktop**:

- OS: MacOS Big Sur 11.1
- Browser: Firefox developer edition

**Comment by jasmussen** [comment]
Thanks for the triage, @JustinyAhin — I think the issue may still be present, as the author select changes to a custom component when you have more than 10 authors. That's the component I think is still not 100% wide.

**Comment by jordesign** [comment]
Closing this as resolved - the author input is now full width regardless of the author name.

<img width="303" alt="Screenshot 2023-08-17 at 9 28 25 pm" src="https://github.com/WordPress/gutenberg/assets/1842363/4db8a9a1-9882-4cdc-9f4d-9961e4a74edc">
