### ISSUE TITLE
Replacing a template part does not prompt saving the template

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#35405]
### Description

Using header template parts as an example:
Picture that a block theme has two header template part files that are both registered to use the header template part area.
When the default header template part is selected in the site editor, it has a toolbar option called replace. When you select replace, you can switch the template part for another.

This replacement prompts saving the first template part.
But it does not prompt saving the change to the current template. This means that on the front, the first, _presumably replaced_, template part still shows.
Refreshing the site editor also reverts back to displaying the first template part.

(With default template part, I mean the part who's slug is used in the markup of the template .html file in the theme.)

Did I misunderstand the purpose of the replace feature?

### Step-by-step reproduction instructions

1. Activate a theme with two registered header -or footer, template parts.
2. Open the site editor and select the default template part
3. Replace the current template part and see that the template part is switched in the editor.
4. See that the save button is now enabled. Clicking the save button asks if you want to save the header template part. Save.
5. View the front of the website to confirm which template part is showing.

### Environment info

WordPress 5.8.1, Gutenberg Version 11.6.0, and trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Denis74F** [comment]
Hi @carolinan ,
it happened to me too and the only solution I found is this:
1 select "**list view**"
2 select "**header**"
3 replace
4 select your template
5 now at the top you will notice the index Header selected
6 move outside the template header with the cursor **(at the top you will now only see index)**
7 do something in index and now save

Done!
In this way I was able to save the change.

**Comment by chthonic-ds** [comment]
@Denis74F I feel there's still an issue here when following the steps you've provided. 

If I use replace to select a new template part, I'm making a change to the template and not the template part. However, the save panel indicates changes have been made to both "Page" and "Template Part". Replacing a template part (without making additional changes to it) should be seen as a change to the template, only.

**Comment by Denis74F** [comment]
Hi @chthonic-ds ,
you are right, however it is the only way i found to make it work, surely this problem needs to be fixed.

**Comment by carolinan** [comment]
Thank you, I know how to make the template save, but users should not have to do that, it is not at all intuitive and if you are doing many iterations it is too much work.

**Comment by Denis74F** [comment]
I agree. I wanted to help solve the problem. For users it is too difficult, in fact they probably would not succeed.

**Comment by ellenbauer** [comment]
I've been testing the Site Editor now for a while as well and it seems very confusing for me, even now.

I totally agree with Carolina's comment, it seems very difficult for users to get the entire Page Template to change when Replacing a Header or Footer Page Template Part, even though it it was one would think is happening.

**Comment by carolinan** [comment]
This has been solved with https://github.com/WordPress/gutenberg/pull/35827, closing.
