### ISSUE TITLE
Navigation: Social icons on a new line

### ISSUE THREAD

**Issue by scruffian** [WordPress/gutenberg#35549]
### Description

When social links are added to a navigation block they are forced onto a new line, rather than being horizontal:
<img width="573" alt="Screenshot 2021-10-12 at 13 48 03" src="https://user-images.githubusercontent.com/275961/136959290-0b6f8fb7-502c-47e8-bbac-89737f35f018.png">

### Step-by-step reproduction instructions

1. Switch to emptytheme
2. Add a navigation block
3. Add some links to the block
4. Add a social links block inside the block
5. Look at the frontend - notice that the social links are on a new line.

### Screenshots, screen recording, code snippet

<img width="573" alt="Screenshot 2021-10-12 at 13 48 03" src="https://user-images.githubusercontent.com/275961/136959290-0b6f8fb7-502c-47e8-bbac-89737f35f018.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jasmussen** [comment]
I couldn't actually reproduce this one, despite testing with trunk and empty theme. Can you try your steps again on latest trunk? Nevertheless there was an issue I discovered in trying to reproduce this, which _could_ potentially cause the issue you're seeing, so I pushed some tweaks in #35722 which might help here.

**Comment by scruffian** [comment]
I agree this seems to not longer be an issue.

**Comment by pbking** [comment]
I'm afraid this is still an issue, but only when the navigation overlay menu is set to 'mobile'.

Reproduced with emptytheme on /trunk of Gutenberg:

```
<!-- wp:navigation {"overlayMenu":"mobile"} -->
<!-- wp:navigation-link {"label":"a Blog page","type":"page","id":703,"url":"http://localhost:4759/?page_id=703","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Lorem Ipsum","type":"page","id":146,"url":"http://localhost:4759/?page_id=146","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:social-links -->
<ul class="wp-block-social-links"><!-- wp:social-link {"url":"http://pbking.com","service":"fivehundredpx"} /-->

<!-- wp:social-link {"url":"http://pbking.com","service":"wordpress"} /--></ul>
<!-- /wp:social-links -->
<!-- /wp:navigation -->
```

Editor (correct):
<img src="https://user-images.githubusercontent.com/146530/138132340-d22f7580-f60f-44bf-9193-5ce3e658756b.png" width=200>

View (not correct):
<img src="https://user-images.githubusercontent.com/146530/138132140-0bc688bd-374d-4d56-b106-881415f40a05.png" width=200>

**Comment by jasmussen** [comment]
<strike>That could be related to an issue Ben reported as well. I'll take a look, thanks.</strike>

I'm commenting on it! Perfect. And thanks for the steps to reproduce, it appears on the frontend only, when the block has responsiveness:

<img width="650" alt="Screenshot 2021-10-21 at 09 20 33" src="https://user-images.githubusercontent.com/1204802/138230358-05fdeace-3f31-4e70-84ec-8082ebf1c229.png">

I'll jump in.

**Comment by jasmussen** [comment]
Thanks for the patience. Actual fix in #35820.
