### ISSUE TITLE
Block patterns loading inconsistently

### ISSUE THREAD

**Issue by dingo-d** [WordPress/gutenberg#35852]
### Description

When I register custom blocks and want to use them in the editor, sometimes they render out fine in the dropdown, and sometimes I only see the name of the pattern.

And no errors in the console, or debug log. 

### Step-by-step reproduction instructions

1. Create a custom pattern
2. Create a custom pattern category
3. Remove core patterns (because they don't fit with what we want to offer to the client)
4. Load the patterns

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/8638515/138340461-3d40f14b-7833-424e-b3a2-b88599e25f4b.png)

Three patterns load fine. Two don't. 

Why?

Who knows 🤷🏼‍♂️ 

### Environment info

- WP 5.8.1, core editor, custom theme
- Chrome, FF, Edge
- Windows 11 Desktop, or Mac OS MBP laptop

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
-Is it the same pattern that doesn't load? What happens if you remove all patterns except the erroring?
Did you confirm that the pattern is valid?
Do they work if you enable Gutenberg?

**Comment by dingo-d** [comment]
Patterns are valid, as they render out fine when I select them. The issue doesn't come from a pattern. Sometimes one is showing, sometimes not, and the same for others. I cannot reproduce the bug with any consistency, which makes this super hard to debug.

I haven't tried it out in a plugin, just the core editor so far.

**Comment by Mamaduka** [comment]
@dingo-d, we fixed a few bugs related to pattern rendering in WP 5.9 (#38175). Are you still able to reproduce the issue with the current major WP version?

**Comment by abhansnuk** [comment]
As in today's bug scrub, pre 6.0 release, I could reproduce this issue when Gutenberg was not enabled. It applied to the third pattern to display, and not one particular pattern. With Gutenberg enabled, I could not reproduce it.

Today on retesting, post 6.0 release, I can not currently reproduce the issue with Gutenberg enabled or not.

**Comment by dingo-d** [comment]
For me, they do load now, but something is broken in how they are rendered, so I need to check out more about what happened here...

**Comment by annezazu** [comment]
@dingo-d I'm going to close this out for now as it doesn't appear this issue is still active. Please comment back here though if that's not the case! I'm always happy to reopen and reinvestigate.

**Comment by dingo-d** [comment]
@annezazu I think there is another issue opened that I've commented on (cannot for the life of me find it atm) where there is no style applied to the patterns preview at all.

**Comment by annezazu** [comment]
Feel free to @ me on that issue but I am only closing this one out for now. I'll see if I can perhaps find the same one today.
