### ISSUE TITLE
Button Block margin issue

### ISSUE THREAD

**Issue by kajalmultidots** [WordPress/gutenberg#38651]
### Description

In Twenty-Twenty one theme, when we add Button block and below in that button block we add new button block, then the margin between two button block is not there.However in other theme it is displayed properly. 

### Step-by-step reproduction instructions

Go to Twenty-Twenty One theme
Add Button Block
Add another Button Block below the first one
For more information I have attached the video for that

### Screenshots, screen recording, code snippet

https://www.loom.com/share/0eec0f5414194665ad6ab56816d27242

### Environment info

WordPress version: 5.9
Gutenberg Plugin Version: 12.5.4

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by HILAYTRIVEDI** [comment]
Hi @kajalmultidots, Thank you for this ticket. But even by following the above steps, I can't be able to reproduce the issue. I think it is fixed now 👍.

Testing video : https://www.awesomescreenshot.com/image/24452395?key=bf214446286acae06476d503d136d571

**Comment by kmadhak** [comment]
Hello @kajalmultidots , @karmatosed,

I have tried to reproduce the same issue, and yes I am also facing the same issue, with and without Gutenberg plugin.

following are the version details

WordPress:- 5.9.2
Gutenberg Plugin Version: 12.5.4
Mac OS:- 12.3.1

Please review from your end and let me know if there is anything.

Thank you.

**Comment by skorasaurus** [comment]
> Hello @kajalmultidots , @karmatosed,
> 
> I have tried to reproduce the same issue, and yes I am also facing the same issue, with and without Gutenberg plugin.
> 
> following are the version details
> 
> WordPress:- 5.9.2 Gutenberg Plugin Version: 12.5.4 Mac OS:- 12.3.1
> 
> Please review from your end and let me know if there is anything.
> 
> Thank you.

There have been a few newer releases of the gutenberg plugin since 12.5.4; the current version is 12.9; are you able to reproduce this using the newest version of the plugin?

**Comment by kmadhak** [comment]
Hello @skorasaurus ,

Yes I have updated the Gutenberg plugin to 12.9.0, and yes I am facing same issue.

Thank you.

**Comment by skorasaurus** [comment]
Sorry for the delay. 

I am still unable to produce this as indicated in the video included which shows the appropriate margin for the separate button blocks editor. 

https://user-images.githubusercontent.com/955351/182205566-d62a23fb-4f4f-4585-b61c-dc521c250ea4.mp4


Are you experiencing this on any other themes? If this is only happening on the twentytwentyone theme, you can report this at the [twentytwentyone support forum](https://wordpress.org/support/theme/twentytwentyone/).

**Comment by kajalmultidots** [comment]
Hello @skorasaurus,

I am not able to reproduce this issue, I think it has been resolved with the latest Gutenberg plugin. 

Thanks
