### ISSUE TITLE
Blocks can still be inserted from the list next to the inserter even if useOnce is true

### ISSUE THREAD

**Issue by fastlinemedia** [WordPress/gutenberg#3968]
## Issue Overview
I've created a block and set useOnce to true, however I'm still able to insert it when it shows up in the quick links next to the inserter. Notice in the screenshot below how my Test Block is greyed out in the actual inserter but can still be highlighted and clicked in the quick links.

![screenshot 2017-12-12 21 50 18_preview](https://user-images.githubusercontent.com/2453483/33923569-c249d614-df86-11e7-877d-82d1162de295.png)

## Steps to Reproduce (for bugs)

1. Create a block with useOnce set to true.
2. Use the block enough times that it shows up in the quick links.
3. You can insert it more than once using the quick links even though useOnce is true.

## Expected Behavior

You should be able to only insert the block once. 

## Current Behavior

You can insert the block more than once.

**Comment by youknowriad** [comment]
I guess we should check the "autocompleter" as well.

**Comment by aduth** [comment]
Fixed in #3988

**Comment by ocean90** [comment]
It seems like this issue has been reintroduced at some point. The code from #3988 does no longer exist, see https://github.com/WordPress/gutenberg/blob/63abd32d9b5cb809ad71167f209dd7a6d0a79a3f/editor/components/inserter-with-shortcuts/index.js

@youknowriad Yep, it's also not disabled in the autocompleter.

**Comment by SuperGeniusZeb** [comment]
Thanks to #7166, disabled blocks can no longer be inserted from the autocompleter. However, the frecent block inserter buttons still let you insert disabled blocks, though there is now an error message shown when you do so:
![image](https://user-images.githubusercontent.com/19592990/41168727-74b2ecbc-6b0c-11e8-80d9-1f3d326ffa0d.png)

**Comment by Soean** [comment]
Can't reproduce anymore, issue seems to be fixed.

**Comment by SuperGeniusZeb** [comment]
@Soean I can still reproduce in `master`.
![image](https://user-images.githubusercontent.com/19592990/41504197-5b17ec74-71ad-11e8-8a45-fa52a3907a41.png)
