### ISSUE TITLE
Query Loop block setup state missing the option to choose patterns

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#40430]
### Description

With 6.0 Beta 1, the Query Loop block only shows the option to start blank whereas before it showed the option to Choose & Start Blank.

cc @jorgefilipecosta based on this work: https://github.com/WordPress/gutenberg/pull/38997

### Step-by-step reproduction instructions

1. Open Site Editor
2. Add a Query Loop block
3. Notice setup state only allows you to start blank.

### Screenshots, screen recording, code snippet

<img width="1103" alt="Screen Shot 2022-04-18 at 4 36 26 PM" src="https://user-images.githubusercontent.com/26996883/163893193-3ff81bd3-35d4-4f7e-86f7-e45c4e2b0987.png">

### Environment info

- WordPress 6.0 Beta 1
- TT2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
There was briefly a bug that prevented the `Choose` button and patterns from being shown, but my understanding is that it was fixed before the beta - https://github.com/WordPress/wordpress-develop/pull/2580.

But maybe it wasn't, I don't know and I'm not sure how to tell.

**Comment by talldan** [comment]
Actually I see now the fix was only committed after Beta 1, so it will be in Beta 2 😄 

I'll close this as fixed. If it is still a problem in beta 2 the issue can be reopened. I tested `trunk` and I can see it works as expected, so I'm confident it shouldn't be a problem.

**Comment by annezazu** [comment]
Thank you so much for connecting these dots!

**Comment by mayan62** [comment]
I still have this bug !! And i have no idea why i have the newest wordpress and Gutenberg installed.
