### ISSUE TITLE
Canvas height in focus mode should wrap document contents

### ISSUE THREAD

**Issue by jameskoster** [WordPress/gutenberg#42226]
I'm sure we discussed this elsewhere but I am struggling to find the issue. Apologies in advance if this is a duplicate.

---

When you enter focus mode to edit something like a header, the canvas stretches to fill the viewport. This can make it difficult to understand the boundaries of the entity you're editing:

https://user-images.githubusercontent.com/846565/177759317-4c5f936a-2be3-48bc-83dc-c95af92d4930.mp4

Ideally the canvas should wrap its contents more precisely, something like:

<img width="1237" alt="Screenshot 2022-07-07 at 12 09 08" src="https://user-images.githubusercontent.com/846565/177759847-c02069b7-26dd-4f3f-a9f2-f649f47a62d7.png">

**Comment by Mamaduka** [comment]
It was initially fixed in #37394. Leave a note for future reference.

**Comment by mtias** [comment]
We should prioritize this as it makes the view feel super weird and kind of pointless.

**Comment by Mamaduka** [comment]
I did `git bisect` and it looks like #38855 introduced the regression. After it `autoResizeIframeHeight` stopped working correctly.

**Comment by talldan** [comment]
I noticed this one is still not working perfectly. Particularly when reloading the editor while in the focus mode:

https://user-images.githubusercontent.com/677833/191464237-dcea53df-fda6-428b-bff3-209fc60abcf4.mp4

Reopening the issue.
