### ISSUE TITLE
Link input without URI scheme should be completed with HTTPS by default

### ISSUE THREAD

**Issue by porg** [WordPress/gutenberg#46244]
![](https://user-images.githubusercontent.com/737143/205104999-814d9b42-08f1-4f19-8473-05cf47f6452d.mp4)

## Reproduction
1) Select an element which supports a hyperlink, e.g. text in a paragraph.
2) Press the link button or shortcut (⌘ K)
3) Into the text field "Search or type url" type or paste an URL without the URI scheme at the beginning, e.g. "example.com/page"
4) Press ENTER to confirm and close the dialog.

## Actual
- Upon inspection you see that the link was created with `http://` prepended.

## Expected
- In this day and age the auto completion should default to `https://`

## HTTPS as the default scheme? Arguments  pro (✅) or against (❌) or uncertain (ℹ️)
- ✅ The majority of websites moved to HTTPS.
- ❌ Most HTTPS websites have set up HTTP to HTTPS redirections, so most users will get to their destinations anyways.
- ✅ But that redirection means longer wait times to reach the destination, instead of a correct HTTPS on first try.
- ❌❌  Falsely using HTTPS for a page that is HTTP only fails totally.
  - The user has to realize this and manually correct in the address bar. Some users will fail here.
- ℹ️ I do not know if it has negative/punishing SEO implications on your website if your outgoing links use predominantly HTTP (for destinations which actually are available as HTTPS).

## My preliminary conclusion (no CMS or SEO or W3C expert at all)
- Overally it seems that defaulting to HTTP is safer, but nevertheless it kinda feels wrong in this day and age.
- You experts decide. It's just something that came to my attention.

**Comment by jordesign** [comment]
I see this has been resolved for adding links to the buttons block specifically (in [#46385](https://github.com/WordPress/gutenberg/issues/46385)).

@eoinsav @getdave is there any way the work from that could be brought in to impact here more broadly?

**Comment by getdave** [comment]
Yes it could be done.

**Comment by porg** [comment]
- When your start this, then please also check this URL-scheme auto-completion bug:
  #35910

**Comment by WDWNT-Frank** [comment]
Just wondering but is anything being done on this? It's still n issue and not resolved in any way.

**Comment by Mamaduka** [comment]
Created PR to swap prepend functions for blocks - #75005.

**Comment by getdave** [comment]
We are looking at this for Navigation in https://github.com/WordPress/gutenberg/pull/73486
