### ISSUE TITLE
Randomly duplicating design tools

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#47293]
### Description

When selecting different blocks in the Site Editor using Gutenberg 15.0 (and all experiments turned off), I found by clicking more than once on a block, I can make the design tools duplicate in the sidebar. From what I can tell, I think it's happening when you click on a block of one type (featured image) and then click on another of the same block (featured image) but I'm not quite sure.  cc @ndiego in case you have time to help test. Trying to share this ASAP to get more eyes.

### Step-by-step reproduction instructions

1. Use Gutenberg 15.0. 
2. Open the Site Editor under Appearance > Editor.
3. Click on a featured image block in a query loop with the block settings open.
4. Click on a different featured image block in the query loop. Notice design tools randomly double. 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/213501873-c6e8c825-a4b5-4da4-977f-5fe593bd5b3d.mov

### Environment info

- WP 6.1.1
- GB 15.0
- TT3
- MacOS
- Chrome Version 108.0.5359.124 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by annezazu** [comment]
I made a replay.io recording replicating this: https://app.replay.io/recording/replication-for-randomly-duplicating-design-tools-47293--e4d4d1a6-8fe2-49ea-bc96-dfb31417f2e1  This gives access to my specific environment where this can be replicated to save time and see what's going on. 

If a developer is able to dig into this and wants access, please say so here and I will give you access to replay.io to dig in.

**Comment by annezazu** [comment]
Really wild stuff is happening 😓  the more I click around:

<img width="849" alt="Screen Shot 2023-01-19 at 8 53 05 AM" src="https://user-images.githubusercontent.com/26996883/213506567-ad61c29d-bb37-4cab-8fe1-c11d6e306518.png">

**Comment by ndiego** [comment]
I believe this might be an issue related to Slot/Fill? Either way, I am able to confirm in the Site Editor with Gutenberg trunk. 

![site-editor-issue](https://user-images.githubusercontent.com/4832319/213510678-c597bec6-69dd-4aea-91a2-6fe77fb3df34.png)

**Comment by ironprogrammer** [comment]
+1 on reproducing this issue.

## Environment
- Hardware: MacBook Pro Apple M1 Pro
- OS: macOS 12.6.2
- Browser: Safari 16.2, Google Chrome 109.0.5414.87
- Server: nginx/1.23.3
- PHP: 7.4.33
- WordPress: 6.1.1
- Theme: twentytwentythree v1.0
- Active Plugins:
  - gutenberg v15.0.0

<img alt="Issue 47293 Repro" src="https://user-images.githubusercontent.com/824344/213590854-e7d61555-f778-4729-aaf4-8d0559452d46.gif" width="600">

**Comment by aaronrobertshaw** [comment]
This might be related to an issue I raised last week: https://github.com/WordPress/gutenberg/issues/47101 which was fixed in via https://github.com/WordPress/gutenberg/pull/47110.

**Comment by t-hamano** [comment]
As @aaronrobertshaw said, I believe this issue was fixed in #47110. I have submitted a similar #47135. But this fix will be part of Gutenberg 15.1, which has not yet been released.

**Comment by annezazu** [comment]
Can we release a point release for GB 15.0 to address this? The site editor felt unusable IMO with this currently in place.

**Comment by t-hamano** [comment]
I too agree with the point release. Who should we mentions this to?

**Comment by tellthemachines** [comment]
I can still reproduce this on latest trunk, when clicking around inside the Post Template block. Once it's happened, then any other block on the page shows duplicate controls, but I could only trigger it within Post Template. 

The other thing I'm noticing is that only Color and Typography-related controls are affected.

<img width="1315" alt="Screenshot 2023-01-20 at 11 40 02 am" src="https://user-images.githubusercontent.com/8096000/213613757-58c852b3-33b3-44e2-862b-9e2dc83d58e8.png">

**Comment by t-hamano** [comment]
I was also able to reproduce it. Somehow, in my environment, it seems to be more likely to occur by clicking on the Post Excerpt Block in the query loop. In addition to 47110, I would like to find out what we need to fix.

https://user-images.githubusercontent.com/54422211/213867739-0d99b86f-53ff-4a48-8109-f4fb3617a293.mp4

**Comment by franzaurus** [comment]
I'm also able to reproduce this on my machine, and made the replay.io recording in my test environment here:
https://app.replay.io/recording/replication-for-randomly-duplicating-design-tools-47293-on-windows--b06eec00-46a8-4e19-aa70-19b5149b12a4

In my case, the duplication was triggered by any blocks under the Post Template.

Environment
- WP 6.1.1
- Windows 11
- Firefox 108.0.2
- TT3
- Gutenberg 15.0

![Mcv345aop](https://user-images.githubusercontent.com/79677758/213870556-4dcbade3-abfd-49a6-bb15-5a5766c5d525.png)

**Comment by t-hamano** [comment]
I believe #47331 will solve this problem.

**Comment by annezazu** [comment]
Asked in core editor to see if we can get some movement and help: https://wordpress.slack.com/archives/C02QB2JS7/p1674356272740079

**Comment by aaronrobertshaw** [comment]
It might be worth noting that to reproduce this on trunk, you need to select a block within the Post Template other than the first post. The following steps illustrate the bug for me:

1. Open the Site Editor and edit a template with a query block
2. In the list view, navigate to and select the query block's inner post template block
3. Within the Post Template block, click the read more link for a post **other than the first one**.
4. Note the duplicate controls in both the block toolbar and the inspector controls sidebar
