### ISSUE TITLE
Regression: Text expansion in Firefox deletes first character

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#50403]
### Description

Starting in WordPress 6.2, text expansion formatting shortcuts are not working correctly. When I type `##` into the editor in Firefox and then press `SPACE` and start typing, the first character is deleted.

### Step-by-step reproduction instructions

1. Create new post in Firefox
2. Type `## Heading`
3. The editor shows "eading" (no "H") formatted as a Heading 2

### Screenshots, screen recording, code snippet

![Animated GIF demonstrating the step-by-step-reproduction instructions](https://user-images.githubusercontent.com/1238696/236551561-cdd921ae-acea-4c4c-9506-6570f3760175.gif)

### Environment info

- WordPress 6.2
- Firefox
- Windows
- Any theme/plugins

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by mrwweb** [comment]
Update: I failed to note that this impacts possibly all similar types of text formatting expansions.

I get the same result (formatting expansion happens while deleting the first characters) for the following:

- `>` for a blockquote
- `-` for a list item
- `*` for a list item
- `1.` for a list item
- `###` for Heading 3

**Comment by skorasaurus** [comment]
Thanks for the clear report; I am able to reproduce this without Gutenberg enabled but with Gutenberg 15.7.0 enabled, I cannot reproduce this; the expansion works as expected. Tested on Firefox 112.0.2 (64-bit). 

@annezazu : could you find out where this was fixed and determine if it's feasible to include it a WP 6.2.x release? (and should this be reported in core instead?)

**Comment by ramonjd** [comment]
> could you find out where this was fixed and determine if it's feasible to include it a WP 6.2.x release? (and should this be reported in core instead?)

I can confirm I can still see the issue running WordPress 6.3-alpha-55700 (with Gutenberg plugin disabled).

With Gutenberg 15.7 enabled the issue is fixed.

As far as I can tell this PR fixed the issue in Gutenberg back on Feb 21, 2023:

- https://github.com/WordPress/gutenberg/pull/48210

I suppose it's safe to assert that the fix didn't make it into 6.2 at the time? 

I can't find any evidence that a regression was introduced in Gutenberg after the fix in #48210

Here's an older issue that cites the same problem in 6.2:

- https://github.com/WordPress/gutenberg/issues/49741

So this issue is a duplicate of #49741 and I suppose it should be reported in Core instead.

**Comment by annezazu** [comment]
Great sleuthing @ramonjd. I'm going to close this out after confirming the fix is making it into the 6.2.x minor release coming up soon: https://github.com/WordPress/gutenberg/pull/48210#issuecomment-1538243448
