### ISSUE TITLE
The new design of the link UI in 16.1.0 has turned one click into four

### ISSUE THREAD

**Issue by bobthemovieman** [WordPress/gutenberg#52216]
## What problem does this address?
In 16.1.0 you "cleaned up" the UI for adding a link into a post. But I ALWAYS want to make the link click open in a new window, and now if I add a link I have to click back into the link, then click on "Advanced options" and then click on the open in a new window option.  I'd love for this to be cleaner and simpler, but can you please add some options into the preferences to allow these options on the link add to be defaulted to my preferences? 

## What is your proposed solution?
Add some global preferences for how the "add link" dialogue options should be defaulted.

**Comment by getdave** [comment]
Thank you for taking the time to provide constructive feedback. It's appreciated. Indeed, this is what the Plugin and WP release beta period is for. It's important that we hear this feedback in order that we can make changes where possible/appropriate. 

We've been looking into adding a preference for this for a while. We'll try and take a look at that as we recognise it's important for _some_ users.

**Comment by zdenys** [comment]
Some users from WordPress.com have brought up a similar request/complaint.

**Comment by ricjcs** [comment]
> this is what the Plugin and WP release **beta** period is for.

@getdave 
Well... but apparently the WordPress will be released with a feature that turns one click into four, and without a solution, right?

**Comment by getdave** [comment]
> @getdave Well... but apparently the WordPress will be released with a feature that turns one click into four, and without a solution, right?

We appreciate this is non-optimal for a cohort of users. That is why contributors have been working on a workround for this in https://github.com/WordPress/gutenberg/pull/52799 as we recognise this problem. 

Unfortunately the original implementation was rejected and so it's now gone with a different approach. This is more complex than anticipated.

Sometimes despite best efforts we cannot land new features or even fixes in time for the release process. Contributors will continue to work at this issue so that we do have an option available in the future.

If you have time available, we would of course value testing and feedback from yourself on the PR. Many thanks.

**Comment by ricjcs** [comment]
Thank you very much for your kind response, your time and work. I just think that if a suitable solution is not ready, WordPress should not be released with the new link UI, as it will impact users for at least 6 months. As you said, that's what beta versions are for, and in those versions it was concluded that the link UI needs to be improved. However, in WP Release Candidate, it comes with this feature. Once again, thank you.

**Comment by TapiwaZvaks** [comment]
As the others suggest, this has added about 5 clicks where previously there was only one. That's a big deal for people who actually spend their days in WordPress writing posts. Indeed, the default should be to open all links in a new tab. I can't think of a situation where it would be ideal to open a linked to page on the same page. Hopefully this issue will be resolved soon.

**Comment by getdave** [comment]
Thank you for the feedback. Please see [my response](https://github.com/WordPress/gutenberg/pull/52799#issuecomment-1676948260) on this discussion.

**Comment by mattwmc** [comment]
Super annoying! Fix the problem!!!!

**Comment by atnjqt** [comment]
Just upgraded to WP Core 6.3 and our team is furious with this change. They rely heavily on the block editor functionality for managing content... and the additional number of clicks is clearly a nuisance to the community.

Having a setting to automatically set that advanced option as checked for new hyperlinks as the default would go a long way in alleviating this pain point. Most links if not all get bounced to a new site. Appreciate the WP Core maintainers for recognizing this for the community per the discussion above.

**Comment by TapiwaZvaks** [comment]
They will take their sweet time and they are unwilling to revert to
previous settings. Meanwhile my hair is growing grey by the day. So many
clicks and so many useful features hidden now. Why? "To clean up the
interface" thats why...!

**Comment by TapiwaZvaks** [comment]
The problem was previously been fixed now it's back. It's like nobody even cares

**Comment by ricjcs** [comment]
The problem is back. After it has been fixed and is perfect, it goes back to the same thing again... So many clicks for a simple action harm those who publish frequently.

**Comment by TapiwaZvaks** [comment]
I thought it was just me. Yes, it's back. Maybe they want to force us to find plugins for such a simple thing that didn't need to be changed in the first place. I also notice a few subtle changes that make my life a bit difficult with the current changes. As an example, the URL when writing a post is no longer clearly visible. You have to click on it to bring it up. The sad thing is that there are so many useful changes that can be made. As an example, work could be done to make tables as useful as in MS Word. To cite one issue, you can't use the Tab button to move between columns. Also many more issues but they would rather focus on destroying the user experience. There used to be an I to the top left that showed the header structure of the post. Very useful, but that went away in previous updates. The Preview element used to be clearly labelled Preview, now there is a computer icon on there

**Comment by ACEkin** [comment]
From a user's point, it is hard to understand why we have to add a link and then edit it to select an option check box. Why not incorporate all the check boxes into the add link interface? I reported this issue several years ago, but it still does not get the attention it deserves. Please, take another look at it.
