### ISSUE TITLE
Block Theme Previews: Live preview displays the active theme instead of the chosen theme

### ISSUE THREAD

**Issue by franzaurus** [WordPress/gutenberg#52309]
### Description

In WordPress 6.3 beta3, when I do live preview for a selected block theme, the Site Editor displays the active theme instead of the chosen theme.

### Step-by-step reproduction instructions

1. Activate TT2 or any other block theme
2. Under Appearance > Themes, click to live preview the TT3 theme
3. Notice that the Site Editor shows you the preview of the active TT2 theme instead of TT3 

### Active TT2, live previewing TT3
![beta3-live-preview](https://github.com/WordPress/gutenberg/assets/79677758/783a2ee0-c869-4c2f-ad00-4e1cb8b7e64c)

### Environment info

    Localwp 7.02+6395
    WordPress: 6.3-beta3
    PHP: 8.1.9
    Server: nginx/1.16.0
    Database: mysqli (Server: 8.0.16 / Client: mysqlnd 8.1.9)
    Browser: Chrome 114.0.0.0 (Windows 10/11)
    Theme: Twenty Twenty-Three 1.1
    MU-Plugins: None activated
    Plugins:
        WordPress Beta Tester 3.5.0
        WordPress Importer 0.8.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Thanks for the report @franzaurus !

I've tested this and can confirm I have been able to recreate this. When no page or template is selected - the existing active theme preview is shown. It is only when a specific template or page is shown that the new theme is previewed.

(Please note in this video that I had customised the TT3 theme prior to testing).


https://github.com/WordPress/gutenberg/assets/1842363/2ae5d2e1-8e4f-4a1d-9221-abae1edcf579

**Comment by carolinan** [comment]
I am able to reproduce this, but inconsistently. Were you able to narrow down the exact steps to getting the preview to switch to the selected theme?

**Comment by carolinan** [comment]
Also reported in https://core.trac.wordpress.org/ticket/58712

**Comment by jomonthomaslobo1** [comment]
> 
@carolinan 
### Steps to reproduce:

1. Install a block theme
2. Select the live preview
3. The preview shows the name correctly on the left-hand side but on the right-hand side, the theme is not previewed properly.Selecting Activate won’t change the theme.

**Comment by carolinan** [comment]
Thank you, I meant what to click on for the preview to change to the correct theme.
@jordesign wrote " It is only when a specific template or page is shown that the new theme is previewed."

For me it is inconsistent.

Activate Twenty Twenty-Three
Go to the themes screen. Select Live Preview of any other block theme. Get redirected to the Site Editor. ✔️ 
The preview shows Twenty Twenty-Three.
I select Pages. The preview still shows Twenty Twenty-Three.
I select Templates. The preview still shows Twenty Twenty-Three.
Now I select Styles and to my surprise it shows the styles and the preview of the correct theme.
I go back to the templates and it shows the correct theme.
Now I go to the Theme screen again and select Live Preview of a third installed block theme.
This time I don't have to click on anything or do anything. The preview is correct.

So I wonder if it is about timing?

**Comment by scruffian** [comment]
Fixed here: https://github.com/WordPress/wordpress-develop/pull/4795

**Comment by franzaurus** [comment]
My experience is closer to @jordesign than to @carolinan. I was consistently redirected to the correct theme whenever a "page", or "template" was chosen. Although activating the selected theme would still showed the existing theme as the active one. 

### My testing environment via instawp
- WordPress: 6.3-beta3
- PHP: 8.1.20
- Server: Apache/2.4.57 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.1.1f
- Database: mysqli (Server: 10.6.14-MariaDB-1:10.6.14+maria~ubu2004 / Client: mysqlnd 8.1.20)
- Browser: Chrome 114.0.0.0 (Windows 10/11)
- Theme: Twenty Twenty-Two 1.4
- MU-Plugins: None activated
- Plugins: WordPress Beta Tester 3.5.0

**Comment by carolinan** [comment]
Does this need any other Gutenberg changes than https://github.com/WordPress/gutenberg/pull/52537?

**Comment by scruffian** [comment]
@carolinan are you still seeing issues?

**Comment by carolinan** [comment]
No issues, I was more wondering if this should be closed as completed.

**Comment by scruffian** [comment]
Yes good point!
