### ISSUE TITLE
Site Editor: View on the editor back end doesn't match the front-end

### ISSUE THREAD

**Issue by franzaurus** [WordPress/gutenberg#52307]
### Description

In WordPress 6.3-beta3, the template view at the back-end, doesn't match the front-end view. I noticed that at the front-end, bulleted list blocks are automatically inserted in the query block for blog posts, and in the navigation page list as well. It seems padding values are being ignored too.

### Step-by-step reproduction instructions

1. Activate Twenty twenty-three theme
2. Open Editor
3. Observe the home template content are displayed properly
4. View the front-end
5. Observe the front-end view doesn't match the back-end view

### Back-end view

![beta3-editor-view](https://github.com/WordPress/gutenberg/assets/79677758/ba24ea5b-8217-42f7-a0b5-be2304f68f66)

### Front-end view
![beta3-front-end](https://github.com/WordPress/gutenberg/assets/79677758/a635af52-63da-4555-a27d-58fcd31d996c)

### Video
![localwp-view](https://github.com/WordPress/gutenberg/assets/79677758/f8cbd9ae-459b-4254-af36-9694f768ee45)

### Environment info
- Localwp 7.02+6395
- WordPress: 6.3-beta3
- PHP: 8.1.9
- Server: nginx/1.16.0
- Database: mysqli (Server: 8.0.16 / Client: mysqlnd 8.1.9)
- Browser: Chrome 114.0.0.0 (Windows 10/11)
- Theme: Twenty Twenty-Three 1.1
- MU-Plugins: None activated
- Plugins:
  * WordPress Beta Tester 3.5.0
  * WordPress Importer 0.8.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jordesign** [comment]
Hey @franzaurus  - I haven't been able to recreate this with a fresh installation of WordPress (apart from the beta tester plugin). Are you able to recreate it in any other environments?

I also notice that you've got some additional content in your site. I don't _expect_ that would make a difference - but are you able to check again with a totally empty/default installation of WordPress?

**Comment by franzaurus** [comment]
Hi @jordesign, thanks so much for your help in testing the issue. For this test, I used a WordPress fresh install in Localwp instance. But since your report said you can't replicate the issue, I've setup a different test environment via instawp. Apparently the issue is not reproducible there. 

So I guess this back-end/front-end mismatch view is specific to a certain environment. In this case the issue is introduced by Localwp environment. I added a video in the original post for clarity.

Instawp environment
- WordPress: 6.3-beta3
- PHP: 8.1.20
- Server: Apache/2.4.57 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.1.1f
- Database: mysqli (Server: 10.6.14-MariaDB-1:10.6.14+maria~ubu2004 / Client: mysqlnd 8.1.20)
- Browser: Firefox 115.0 (Windows 10/11)
- Theme: Twenty Twenty-Three 1.1
- MU-Plugins: None activated
- Plugins:
  * WordPress Beta Tester 3.5.0
   
![instawp-view](https://github.com/WordPress/gutenberg/assets/79677758/e4d376d6-d403-4f45-8f65-058a0bb8834e)

**Comment by t-hamano** [comment]
Hi @franzaurus,

This issue was also reported in #52199, but it is probably specific to the Windows OS environment.

Here is the ticket for the core: https://core.trac.wordpress.org/ticket/58711

This problem has also been fixed in [Changeset 56136](https://core.trac.wordpress.org/changeset/56136). Therefore, the fix will be reflected in the nightly build or the next beta version.

I would like to close this issue, but if I have missed something, please comment.

**Comment by franzaurus** [comment]
@t-hamano thank you for directing me to the ticket link at https://core.trac.wordpress.org/ticket/58711. Unfortunately, I cannot do the patch test as I'm not familiar with the steps. However, I'm still experiencing the issue in WP 6.3 RC3 (the same Windows env) although the problem doesn't show up if I install Gutenberg on top of it.

Let me know if you need more information. Thank you.
