### ISSUE TITLE
Site Editor: The static homepage with the Front Page template that doesn't have the post content displays nothing

### ISSUE THREAD

**Issue by arthur791004** [WordPress/gutenberg#53264]
### Description

Referring to https://github.com/Automattic/wp-calypso/issues/79224, the site editor might display nothing when
1. The “Your homepage displays” setting is configured to a static page
2. The theme has a front-page.html or the user created a front-page template
3. The front-page template contains only patterns

The reason is the registered patterns/blocks are filtered out via the [canInsertBlockType](https://github.com/WordPress/gutenberg/blob/5bf6aa089c67685da4aa738a45d30ed32786fb73/packages/block-editor/src/store/selectors.js#L2368) function because [the block editing mode is disabled](https://github.com/WordPress/gutenberg/blob/5bf6aa089c67685da4aa738a45d30ed32786fb73/packages/block-editor/src/store/selectors.js#L1559), and it's disabled due to [useDisableNonPageContentBlocks](https://github.com/WordPress/gutenberg/blob/5bf6aa089c67685da4aa738a45d30ed32786fb73/packages/edit-site/src/components/page-content-focus-manager/disable-non-page-content-blocks.js#L35)

### Step-by-step reproduction instructions

1. Install and activate the themes below
  * [Kigen](https://public-api.wordpress.com/rest/v1/themes/download/kigen.zip) 
  * [Hey](https://public-api.wordpress.com/rest/v1/themes/download/hey.zip)
3. Go to Settings > Reading, and configure “Your homepage displays” to a static page
4. Go to Appearance > Editor
5. Ensure the preview displays nothing

### Screenshots, screen recording, code snippet

![image](https://github.com/WordPress/gutenberg/assets/13596067/946a98ea-ed19-4230-83f8-c81601385221)

### Environment info

The latest trunk on 2 Aug

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I think this was fixed in #53169. The fix will ship with Gutenberg 16.4.

**Comment by annezazu** [comment]
This seems to match what was reported here by @wpsoul https://github.com/WordPress/gutenberg/issues/52388#issuecomment-1660849268

**Comment by tellthemachines** [comment]
> Install and activate the [Kigen](https://wordpress.com/theme/kigen) theme

@arthur791004 that theme doesn't seem to be available in the WP theme directory. Could you share it as a zipped folder or, alternatively, point to a publicly accessible theme where the issue can be reproduced? You could also create a dummy theme with just the minimal code required to reproduce.

**Comment by arthur791004** [comment]
Here it is: https://public-api.wordpress.com/rest/v1/themes/download/kigen.zip

**Comment by arthur791004** [comment]
> I think this was fixed in https://github.com/WordPress/gutenberg/pull/53169. The fix will ship with Gutenberg 16.4.

I guess it's slightly different since I tested it using the latest trunk yesterday and the issue is still there 🤔

**Comment by tellthemachines** [comment]
Thanks!

I can't reproduce the issue on the latest Gutenberg trunk or on WP 6.3 RC3 with the Kigen theme:

<img width="1455" alt="Screenshot 2023-08-03 at 4 26 35 pm" src="https://github.com/WordPress/gutenberg/assets/8096000/ba7d9f54-87db-4554-b270-8e3f6d824793">

Could you try testing also on WP 6.3 RC without Gutenberg enabled?

**Comment by arthur791004** [comment]
I tried again and it works now.

* With Gutenberg 16.3.0, the site editor displays nothing
* With Gutenberg built from the latest trunk, the site editor displays it correctly!

So, I expect this issue would be resolved with Gutenberg 16.4.0 🎉

**Comment by tellthemachines** [comment]
Thanks for checking! Closing as fixed by https://github.com/WordPress/gutenberg/pull/53169.
