### ISSUE TITLE
Gutenberg Editor is Not Usable Since WordPress 6.3 Hit

### ISSUE THREAD

**Issue by VR51** [WordPress/gutenberg#53579]
### Description

I get the same error. Whole bunch of sites. Looks like an infinite loop in a function that runs in the editor. I'm seeing a lot of people report the same error and bugs in Gutenberg since WP 6.3 was released.

Example messages logged in Console when a new block is inserted into a Gutenberg page, different sites:

```
helpers.js:89 Uncaught RangeError: Maximum call stack size exceeded
    at Function.isArray (<anonymous>)
    at Function.zr [as save] (blocks.min.js:10:4314)
    at Wg.Content (block-editor.min.js:26:308655)
    at B (element.min.js:9:6433)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
```

And

```
TypeError: this.activateMode is not a function
    at https://c0.wp.com/c/6.3/wp-includes/js/media-views.min.js:2:59604
    at It (chrome-extension://gojhcdgcpbpfigcaejpfhfegekdgiblk/web3/provider.js:2:586804)
    at Function.ma (chrome-extension://gojhcdgcpbpfigcaejpfhfegekdgiblk/web3/provider.js:2:621991)
    at n._createModes (https://c0.wp.com/c/6.3/wp-includes/js/media-views.min.js:2:59564)
    at n.initialize (https://c0.wp.com/c/6.3/wp-includes/js/media-views.min.js:2:58973)
    at n.initialize (https://c0.wp.com/c/6.3/wp-includes/js/media-views.min.js:2:79857)
    at n.initialize (https://c0.wp.com/c/6.3/wp-includes/js/media-views.min.js:2:73432)
    at h.View (https://c0.wp.com/c/6.3/wp-includes/js/backbone.min.js:2:14648)
    at n.constructor (https://c0.wp.com/c/6.3/wp-includes/js/wp-backbone.min.js:2:2602)
    at n.constructor (https://c0.wp.com/c/6.3/wp-includes/js/media-views.min.js:2:106817)
```

And

```
blocks.min.js:10 Uncaught RangeError: Maximum call stack size exceeded
    at Function.zr [as save] (blocks.min.js:10:4273)
    at Wg.Content (block-editor.min.js:26:308655)
    at B (element.min.js:9:6433)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
    at B (element.min.js:9:6431)
```

This error and symptoms of this error have been reported by others in the WP forums and in Trac (See: https://core.trac.wordpress.org/ticket/59038)

### Step-by-step reproduction instructions

- Load the Gutenberg Editor. Blocks show the 'Recover Block' error message.
- Add a new block into the editor. Console logs the error Uncaught RangeError: Maximum call stack size exceeded.
- Try to save a page. The page does not save.

Edits to pages can be saved only when the HTML editor is in use.

I've disabled and enabled plugins to try and discover whether the fault is being caused by a plugin. Apparently is not.

I've reinstalled 6.3 in 2 sites to see whether any files are missing. Made no difference.

The active theme is not the cause of the issue. the problem occurs in sites that use different themes.

I've tried to use Gutenberg with admin script optimizations disabled and with Jetpack Performance disabled. Neither attempt gave me a working editor.

### Environment info

I'm not using the Gutenberg plugin. I'm using the version of Gutenberg that ships with WordPress. I tried the Gutenberg plugin (latest) to see whether this would resolve the issue; it ddn't.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by carolinan** [comment]
Hi
Does it work if you disable all plugins and change to a default theme? 
If you disabled Jetpack, I am unsure of what would reference `https://c0.wp.com/`

**Comment by VR51** [comment]
@carolinan hi there.

Please see this report on Trac https://core.trac.wordpress.org/ticket/59038.

**Comment by carolinan** [comment]
Those are multiple issues combined into one ticket, which makes it very difficult to troubleshoot.

**Comment by carolinan** [comment]
I have read the issue, but the questions above are unanswered. Disabling plugins is one way to troubleshoot, but it does not help if the issue is in the active _theme._

**Comment by tellthemachines** [comment]
This may have been fixed by #53596; @VR51 are you able to confirm by testing on Gutenberg trunk?

**Comment by annezazu** [comment]
@VR51 checking back in here to see if you can confirm. For now and for tracking, I'm going to add this into the 6.3 board as triage until we hear back. Worst case, can close out for now.

**Comment by VR51** [comment]
@annezazu thank you for asking about this. I concentrated my replies on the Trac ticket. I'm about to respond there now. Not much to report back yet; have had a busy week so not much testing done post getting the editor to work by disabling plugins that caused the editor bug to show itself.

My observation, as stated in Trac, is that there is a bug in the editor that grows in response to plugins that act on the editor screen. One or two plugins that cause issues in the editor screen are unlikely to cause the bug's impact to grow large enough to cause web browsers to give up rendering blocks. Some plugins with high impact on the bug are alone sufficient to break the editor: non rendering blocks, slow performance.

**Comment by annezazu** [comment]
Thanks for following up! If you can test with Gutenberg trunk to see if it's resolved by the above PR, that would be very helpful. Let's keep this open for now though until we have more information. Really appreciate your effort to provide more information here and help us get closer to a solution.

**Comment by VR51** [comment]
@annezazu Hi there!

I am no longer able to replicate the bug. I know many plugin devs released updates in the last week. Appears to be the plugin devs have worked around the issue. Hopefully the update pushed to Trunk resolves the issue where it still exists.

I am sorry I cannot be of more help at this point.

**Comment by annezazu** [comment]
No worries at all. Thank you for following up and for your persistence. I'll go ahead and close this out for now.

**Comment by VR51** [comment]
@annezazu I do not usually add to closed issues. I think you will find this interesting. There seems to be a bug that shows when the Opera One browser is used to work with the Gutenberg editor. This bug looks similar to the one this GitHub issue is about.

The issue has been reported to Opera here https://forums.opera.com/topic/66015/opera-one-does-not-work-correctly-with-wordpress

To summarise that bug (Opera One specific),

- Using a non Incognito browser window causes Gutenberg to bug out
- Sites where the bug shows itself do work fine when an Incognito browser window is used
- The bug seems to be sporadic: it shows in some sites but not others
- The bug appears not to be caused by WordPress plugins or themes
- The bug appears not to be caused by Opera extensions
- The bug (or maybe it is a different cause) affects the Appearance Customizer too: the Customizer loads but changes cannot be saved

NB Opera uses the term Private Window instead of Incognito Mode.

I have fully cleared my browser cache and fully disabled browser extensions. The bug is there regardless.

I suspect there is a difference in the way Opera One handles jQuery / Javascript errors between Private windows and plain non private windows.

Thought I would tag this observation onto this Github issue because it might shed light on the underlying cause of fault.

**Comment by annezazu** [comment]
Thanks so much for bringing this back. I'm going to flag this for the wider Test team to see if we can get more info and someone can dig in! It seems specific and related to an Opera update but let's be sure.

**Comment by VR51** [comment]
> Thanks so much for bringing this back. I'm going to flag this for the wider Test team to see if we can get more info and someone can dig in! It seems specific and related to an Opera update but let's be sure.

Opera has investigated the issue. Opera's reply is quoted below here. I'm not sure Opera has correctly identified the issue but I will test during the weekend. According to Opera the issue was caused by the Opera Wallet extension. I'm not certain that can be correct because the bug still showed when Opera extensions were disabled.

> We've investigated the issue at Opera and found that it was caused by the Opera Wallet extension (v1.17) being incompatible with some WordPress plugins (Gutenberg, more specifically). We've recently addressed this and released Opera Wallet v1.18 to resolve the issue. The extension should be automatically updated once you reopen your browser. If you want to update it manually, go to opera://extensions, turn on Developer Mode, and press Update.

https://forums.opera.com/topic/66015/opera-one-does-not-work-correctly-with-wordpress/13

**Comment by annezazu** [comment]
Thanks for the continued updates. Fingers crossed this does fix the issue!
