### ISSUE TITLE
White space at dashboard top side at 782px wide screen

### ISSUE THREAD

**Issue by shreyasikhar** [WordPress/gutenberg#55349]
### Description

There is white space at the top of the dashboard when I edit the post at 782px screen size only. I tested this in the following themes: Twenty Twenty, Twenty Twenty-Three and Twenty Nineteen.

Issue video: https://share.cleanshot.com/2LNwPsrZ9FtSnyW98JmD

### Step-by-step reproduction instructions

1. Open Post Edit screen
2. Switch to responsive mode from the inspector panel and set width to 782px

### Screenshots, screen recording, code snippet

https://share.cleanshot.com/2LNwPsrZ9FtSnyW98JmD

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by sabernhardt** [comment]
This is the top of the **Post** editor in **Fullscreen mode** when the viewport is exactly 782 pixels wide.

![Post editor with 46 pixels of empty space at the top](https://github.com/WordPress/gutenberg/assets/17100257/27cfc00e-f372-4a3c-92f9-c34871e55150)

The blank area was reported in the [Site editor context](https://github.com/WordPress/gutenberg/pull/29489#pullrequestreview-610218899) years ago. It seems to have been fixed there already (though the template selection probably should behave differently at that width).

![Site editor does not have empty space at the top](https://github.com/WordPress/gutenberg/assets/17100257/dc3fbc5d-ac99-492e-afdc-a1420ff6bc37)
![Template selection covers half the screen but the preview is not showing](https://github.com/WordPress/gutenberg/assets/17100257/2a5fa4d3-3643-4d84-a841-d3c9a6624105)

**Comment by jordesign** [comment]
Confirmed in my testing as well - it seems the space is reserved for the WP admin bar (which is only visible until 781px) but the space for it is maintained at 782px

**Comment by shreyasikhar** [comment]
Hello Everyone,
This issue is still reproducible. So, if any of you can check if the [PR](https://github.com/WordPress/gutenberg/pull/55350) changes are good for this issue? or please tag the respective people to check, thanks.

cc: @jordesign @sabernhardt @apeatling

**Comment by sabernhardt** [comment]
The similar issue with the blank space next to the site editor's `.edit-site-layout__sidebar-region` panel was reported on [Trac #60035](https://core.trac.wordpress.org/ticket/60035), which may deserve its own issue in this repository.

781px seems to be a mistake, and I think the ["adminbar goes big" comment](https://github.com/WordPress/gutenberg/blob/cdeca67b63635cca295ba8f4874130c53f394ab0/packages/base-styles/_breakpoints.scss#L11) could have led to the confusion. 782 is where the admin toolbar becomes taller with large icons, but that's for _smaller_ screens up to 782 pixels wide (since [MP6 in 2013](https://core.trac.wordpress.org/changeset/26134)). Gutenberg tends to use 782 as the min-width.

The breakpoint queries probably should be
`(max-width: #{ ($break-medium) })`
and
`(min-width: #{ ($break-medium + 1) })`
but never subtracting one.
