### ISSUE TITLE
Pattern: unable to see white text when editing a pattern at the source 

### ISSUE THREAD

**Issue by gabbsmo** [WordPress/gutenberg#60771]
### Description

Since upgrading WP from 6.4 to 6.5.2 I lost the ability to edit synced patterns inline on a post where it is used. Instead I have the option to "Edit Original" which will open a new editor.

This is particularily troublesome if the pattern is using white text, that is designed for use on a dark background, i.e. a group block. In this case all text is invisible on the white background of the editor.

### Step-by-step reproduction instructions

1. Create group block with dark background
2. Add some text with white font color
3. Create a synced pattern from the text
4. Click edit original

### Environment info

WordPress 5.6.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ktmn** [comment]
> lost the ability to edit synced patterns inline on a post where it is used

I agree, this change was a regression in my opinion.

I tracked down where it changed and appears to be here: https://github.com/WordPress/gutenberg/pull/57036

> As part of the work on allowing [partial editing of synced patterns](https://github.com/WordPress/gutenberg/issues/53705) we want to disable full editing of the synced pattern entities within the block editor.

---

> Needs Design Feedback

Gutenberg = it's like a Word document, you click on the text and you can change it. Simple! Now when you click on a pattern _nothing happens_. The text is not editable. That's the end of the road for most people. Roll it back.

If this is needed for "partially synced patterns" then do it for "partially synced patterns" not for "synced patterns".

**Comment by annezazu** [comment]
Thanks for opening this issue. To build on what was shared above, this change was done to accommodate an upcoming feature that allows you to have a synced pattern with the option to allow for specific parts of it to be overridden within individual patterns. This means you could have part of a design and text set across all synced patterns along with some customization to make specific instances of the same pattern your own. As a result, the new experience was introduced. It's a trade off for sure but it won't be rolled back as is.

**Comment by annezazu** [comment]
With that said, I've updated the name and labeling of this issue a bit to see what we can do to address the issue around the white text and being unable to see the background!

**Comment by gabbsmo** [comment]
My spontaneous suggestion is to introduce a toggleable dark mode to Gutenberg/WP Dashboard.

**Comment by richtabor** [comment]
This is what I'm getting. Do you mind sharing a screen recording (and/or do you notice a variable)? 

https://github.com/WordPress/gutenberg/assets/1813435/2773cc9c-d3b6-4669-a66f-165fff17acbb

**Comment by gabbsmo** [comment]
It looks like you include the background group in your pattern so that will naturally work. Try only selecting the paragraphs of text inside the group and create the pattern from that. Then you should get what I described in the OP.

I don't have a recording right now but can make it later if you need it.

**Comment by talldan** [comment]
> If this is needed for "partially synced patterns" then do it for "partially synced patterns" not for "synced patterns".

@ktmn The challenge here is that it will be possible to use both partially synced patterns and synced patterns in the same post, so having inconsistent editing of those patterns would be a confusing experience.

The change did also fix this bug - [Editing a Synced Pattern that you don't have permission to edit is a poor user experience](https://github.com/WordPress/gutenberg/issues/54442#top).

**Comment by gabbsmo** [comment]
@annezazu @richtabor any chance that this issue can be revisited? There has been a few WP versions since and this is still a pain point.

**Comment by annezazu** [comment]
I can no longer replicate the issue of a dark background with white text showing up incorrectly in the editor:

https://github.com/user-attachments/assets/0e3eb5c7-5914-4094-be8b-e0c203ec267f

It looks like this is solved? Or am I missing something? The experience of editing original won't change due to the aforementioned new feature.

**Comment by gabbsmo** [comment]
Thank you for your reply. Good to see that some progress has been made for paragraph blocks. Is that in WP Core or the Gutenberg plugin? I am not using the plugin.

In my case I am using button blocks from GenerateBlocks but it is the same with the Gutenberg button blocks. 

If I make a button in my pattern with transparent background (rgb 255,255,255,0) and white text I don't see anything in the editor if I don't have a background in my pattern.

**Comment by annezazu** [comment]
That's using Core WP with the Gutenberg plugin installed as Gutenberg is backported for releases. Can you please share a video? Please show with core button blocks.

**Comment by gabbsmo** [comment]
I made a [recording](https://ways-my.sharepoint.com/:v:/g/personal/gabriel_smoljar_ways_se/IQBVeiW4KbjZTL9ES5N-gysUAbo6y6v0z3duY9J_KioAA9Q?e=oAeGjX) that shows my experience with a fresh install of WP and Gutenberg plugin.

**Comment by talldan** [comment]
> I can no longer replicate the issue of a dark background with white text showing up incorrectly in the editor:

@annezazu I think you need to specifically set the text to be a white color.

---

I think this is still an issue, but it needs some discussion about what the correct fix is. Perhaps users should be able to change the editor canvas background color when in an isolated editor. At the moment it adopts whatever the theme's background color is.

Or use a checkerboard pattern like some apps do when the background is transparent.
