### ISSUE TITLE
Block Editor: Unable to paste text into text field inside block

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#61377]
### Description

Some blocks have text fields. For example, Embed block, Shortcode block, etc. Pasting text into the text field of these blocks deletes the blocks and creates a Paragraph block in their place.

I think this can happen with any block that has a text field, not just the core block.

This problem does not seem to occur in WP6.5.

### Step-by-step reproduction instructions

- Insert Shortcode block, Embed block, etc.
- Copy text from elsewhere and paste it into the text field.
- It should be converted to a Paragraph block.

### Expected Behaviour (WP6.5)

https://github.com/WordPress/gutenberg/assets/54422211/dc5764ea-2626-4583-a7b4-e1dbdaa6eb29

### Actual Behaviour (Latest Gutenberg)

https://github.com/WordPress/gutenberg/assets/54422211/df22bb58-385f-49c1-bca4-1def4b569952

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I'm adding this to the project board because I think this issue has a very large impact and should be fixed in WP6.6.

**Comment by t-hamano** [comment]
After going back through the commits, it appears that this issue occurred in #54543.

**Comment by afercia** [comment]
> This problem does not seem to occur in WP6.5.

Right. As also reported on https://github.com/WordPress/gutenberg/issues/61566 this appears to be a regression.

**Comment by liviopv** [comment]
The issue is still present on the Shortcode Block as of 18.4:

https://github.com/WordPress/gutenberg/assets/14153300/fc5c252c-004c-4a47-bed9-88a08adfc87a

**Comment by ellatrix** [comment]
There's a PR #61389 waiting for approval

**Comment by liviopv** [comment]
@ellatrix reopening because I'm still getting a similar behavior when pasting content into the Classic Block when running 18.4.1 and I'm not sure if that's intentional:

https://github.com/WordPress/gutenberg/assets/14153300/18168f7f-1977-4a9e-ab88-a3a91f93303a

## Steps to reproduce
1. Add a Classic Block to a page
2. Paste content into the Classic Block
3. The Classic Block will transform into other blocks like Paragraph

**Comment by t-hamano** [comment]
I tried testing with Playground and the latest Gutenberg, but I couldn't reproduce this problem.

From looking at your video, the Classic block is not opened as a dialog, so I would expect the editor to not be an iframe, which means custom fields are enabled. I tested it in the same environment and it doesn't convert to other blocks 🤔


https://github.com/WordPress/gutenberg/assets/54422211/5ddb5788-716b-45fc-95de-95c2657f5869
