### ISSUE TITLE
Navigation block overlay padding zero clamp calculation fails for zero values

### ISSUE THREAD

**Issue by djcowan** [WordPress/gutenberg#61398]
### Description

The padding on the navigation responsive container is calculated using a clamp function.
The clamp calculation uses the `--wp--style--root--padding-xyz` - which fails when any of the units are set to zero (0)
Our site don't require a value for top or bottom.
```
padding: 
clamp(1rem, var(--wp--style--root--padding-top), 20rem) //<-- is zero
clamp(1rem, var(--wp--style--root--padding-right), 20rem) 
clamp(1rem, var(--wp--style--root--padding-bottom), 20rem) // <-- is zero
clamp(1rem, var(--wp--style--root--padding-left), 20em);
```

### Step-by-step reproduction instructions

1. Go the the Style editor > Layout
2.  Set top and bottom to zero
3.  open the responsive menu container on mobile
4.  calc function fails - no padding applied
![zero](https://github.com/WordPress/gutenberg/assets/2137698/3eec057a-ec81-4bb0-92e3-bdcddaa640b4)

### Environment info

WordPress 6.5.2 running our Custom block theme
Gutenberg - Version 18.2.0
Mac/Windows, iOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by hanneslsm** [comment]
I can confirm this issue. I have also noticed it with a new custom theme but haven't had time to investigate it yet. Clamp calculation as the cause makes sense - my theme also doesn't have a top padding.

**Comment by djcowan** [comment]
We sidestep by setting 0.01em and fix it when it breaks.

**Comment by amitraj2203** [comment]
Hi @djcowan and @jordesign, I have raised a [PR](https://github.com/WordPress/gutenberg/pull/61697) for this issue. Please have a look at it and let me know if it needs improvement.

Thank You!

**Comment by hanneslsm** [comment]
It looks like the issue is also solved when using `0px` instead of `0`

**Comment by Successfulsebunya** [comment]
## Reproduction Report
### Description
❌ This report validates the issue can not be reproduced.

### Environment
- WordPress: 6.8.2
- PHP: 8.3.0-dev
- Server: PHP.wasm
- Database: WP_SQLite_Translator (Server: 5.5 / Client: 3.40.1)
- Browser: Chrome 138.0.0.0
- OS: macOS
- Theme: Twenty Twenty-Five 1.2
- MU Plugins: None activated
- Plugins:
  * Gutenberg 21.2.0
  * Test Reports 1.2.0

### Actual Results
1.  ❌ Error condition doesn’t re-occur (not reproduced).

### Additional Notes
- Padding once set to 0 remains zero. Must have been fixed.
1. Step-by-step reproduction instructions
2. Go the the Style editor > Layout
3. Set top and bottom to zero
4. open the responsive menu container on mobile
5. Padding is set to 0

### Supplemental Artifacts

<img width="1710" height="867" alt="Image" src="https://github.com/user-attachments/assets/83a7d6e4-2813-4d55-ade4-e8c6ad9637b4" />
<img width="410" height="271" alt="Image" src="https://github.com/user-attachments/assets/33559d5a-7384-4c49-80b5-8d46b2088f1d" />

**Comment by SirLouen** [comment]
## Reproduction Report
### Description
❌ This report can't validate that the issue can be reproduced.

### Environment
- WordPress: 6.9-alpha-60093-src
- PHP: 8.2.29
- Server: Apache/2.4.62 (Debian)
- Database: mysqli (Server: 11.8.2-MariaDB-ubu2404 / Client: mysqlnd 8.2.29)
- Browser: Chrome 138.0.0.0
- OS: Windows 10/11
- Theme: Twenty Twenty-Three 1.6
- MU Plugins: None activated
- Plugins:
  * Test Reports 1.2.0

### Reproduction Instructions
1. Using the instructions provided in the OP

### Actual Results
1.  ❌ Error condition is not occurring.

### Additional Notes

- @djcowan I'm not confident to say that this is failing, but intended behaviour, or maybe it has been resolved already.

- @amitraj2203 your proposed PR doesn't make sense to me. Why not simply adding 0 to the first value of the clamp instead of such convoluted `min` over the `clamp`?? Probably in case it has been already resolved, you had to look for the root cause of the failing `clamp` not this quick fix…

- So at this point I can say that this has been already been solved, so I'm closing it. @djcowan feel free to write back, if you have some other reproduction instructions to make this happen, and we will be able to reproduce it and test it again.

### Supplemental Artifacts

Padding to 0:
<img width="1245" height="1016" alt="Image" src="https://github.com/user-attachments/assets/194a1cf3-35ab-4b0b-956a-af476b92708f" />

Clamp is taking the 1rem
<img width="1592" height="1100" alt="Image" src="https://github.com/user-attachments/assets/bb3e410a-430d-43d0-88bf-8cec6ef2867f" />

**Comment by hanneslsm** [comment]
Thanks @SirLouen and @Successfulsebunya 

To clarify, the issue still exists and is reproducible. @SirLouen thanks for providing the screenshots. I looks like you were setting the padding to `0px` via the editor. However, when editing the value in the theme.json `0` (note the missing unit), the issue still occurs.

<img width="1158" height="749" alt="Image" src="https://github.com/user-attachments/assets/66856a17-2023-4aca-ad43-ccfa79e6a7d4" />

**Comment by SirLouen** [comment]
@hanneslsm 
In the first post, the steps were to modify this in the editor. So this seems a new problem
But still I can't reproduce this. I'm using TT3 for the testing
Can you provide more testing info like environment variables?

**Comment by hanneslsm** [comment]
> In the first post, the steps were to modify this in the editor. So this seems a new problem

You are right, I didn't see this, because I'm just always editing the theme.json directly.

I'm realizing now, I might have been mistaken. When the value is set to `0` (without a unit) the clamp does not fall back to 1rem (1rem * 0 = 0)
When the value is set to `0px` (with a unit) the clamp falls back to 1rem ( 1rem * 0px = 1rem).

So, actually, everything could be as desired.

<img width="1571" height="872" alt="Image" src="https://github.com/user-attachments/assets/cddea15e-554b-4ca7-a553-4c6a1cb6481b" />
Tested in a local environment on MacOS
Theme: TT3
PHP Version: 8.2.23
MySQL Version: 8.0.35
Server Software: nginx/1.26.1
WordPress Version: 6.8.2
Gutenberg Version 21.2.0
