### ISSUE TITLE
6.6 Dev Note Tracking Issue

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/gutenberg#62096]
## Tracking all Dev Notes from Gutenberg plugin releases 17.8 - v18.5

Please read the information below carefully. If you have questions or suggestions, connect with `@JuanMa` via Slack, ping @juanmaguitar on GitHub, or comment here. 

> [!IMPORTANT]
> 🗓 Deadline **Drafts for All Dev Notes** - **June 11th, 2024** (on Beta 2, so there's enough time for reviews) 
> 🗓 Deadline **All Dev Notes Published** - **June 23rd, 2024** (a few days before RC1) 

Not all developer-related information must be in a separate DevNote on the Make Core blog for the field guide. We can group related information. We can already decide whether some features warrant a stand-alone blog post or a group post. 

## Stand-alone post

To streamline the process and eliminate bottlenecks, all writers of stand-alone dev notes will write the dev notes on the Make Core Blog.
 

<details>
<summary>Instructions</summary>

- Create your note in a new post,
- Save as Draft
- Enable public preview
- Share the link to the public preview in a comment below as "ready for review"
- "For dev notes, each one must have at least two reviewers" ([Handbook](https://make.wordpress.org/core/handbook/tutorials/writing-developer-notes/))

</details>

## Part of a group post

If the information related to your PR will be part of a group post, please write the **dev note in a comment on the PR**, so it can be reviewed and, if necessary commented on, by the release docs team or a reviewer. 

## Before you start writing  📣  please read the handbook pages: 

- ⭐️ [Writing developer notes](https://make.wordpress.org/core/handbook/tutorials/writing-developer-notes/)
- ⭐️ [Style & Substance section](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#style-and-substance) of the Post & Comment Guidelines for Make Blog 
- ⭐️ [Documentation Style Guide](https://make.wordpress.org/docs/style-guide/) - Good for reference, when in doubt, especially when English is not your native language.

---

> [!NOTE]
> The list is incomplete. We are in the process of reviewing plugin release changelogs and add them as we progress on the task. 

There are two labels relevant to DevNotes : 
- [`needs dev note`](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Needs+Dev+Note%22+merged%3A%3E%3D2024-03-05+)
- [`has dev note`](https://github.com/WordPress/gutenberg/issues?q=label%3A%22has+dev+note%22+merged%3A%3E%3D2024-03-05+) 

If you worked on a feature/module/component that definitely needs a dev note, please assign the label `needs dev note` If you already added the Dev Note to the make blog on draft or as a comment on the PR, please label it `has dev note` 

---

## TO DO

_Progress of the Documentation work for WP 6.6 release (including the DevNotes tracked on this issue) can also be followed at [WP 6.6 Documentation](https://github.com/orgs/WordPress/projects/202) project dashboard_

_PRs with label `has-dev-note` or a related DevNote draft are marked with [x]_

### Stand-alone posts

- [x] **Grid layout** feature: @tellthemachines [dev note published](https://make.wordpress.org/core/2024/06/18/grid-layout-type/) 
    - [x] https://github.com/WordPress/gutenberg/pull/59051 `GB17.8`
    - [x] https://github.com/WordPress/gutenberg/pull/58539 `GB17.8`
    
- [x] **Background image feature** dev note, covering the following PRs: @ramonjd [dev note published](https://make.wordpress.org/core/2024/06/20/site-wide-background-images-in-wordpress-6-6/)
    - [x] https://github.com/WordPress/gutenberg/pull/59354 `GB17.9`
    - [x] https://github.com/WordPress/gutenberg/pull/59454 `GB18.1`
    - [x] https://github.com/WordPress/gutenberg/pull/61271 `GB18.5`
    - [x] https://github.com/WordPress/gutenberg/pull/61998 `GB18.5`
    
- [x] **Theme.json version 3** @ajlende  [dev note published](https://make.wordpress.org/core/2024/06/19/theme-json-version-3/) 
  - [x] https://github.com/WordPress/gutenberg/pull/58409 `GB18.3` 📝 @ajlende 

- [x] **CSS Specificity** @aaronrobertshaw [dev note published](https://make.wordpress.org/core/2024/06/21/wordpress-6-6-css-specificity/)
  - [x] https://github.com/WordPress/gutenberg/pull/61638 `GB18.5` @aaronrobertshaw 
  - [x] https://github.com/WordPress/gutenberg/pull/60106 `GB18.1` @tellthemachines
  - [x] https://github.com/WordPress/gutenberg/pull/59457 `GB18.1` @tellthemachines

- [x] **React JSX transform** @youknowriad  [dev note published](https://make.wordpress.org/core/2024/06/06/jsx-in-wordpress-6-6/)
  - [x] https://github.com/WordPress/gutenberg/pull/61692 `GB18.5` @youknowriad 
**React updates**

- [x] **Preparation for React 19 Upgrade** @Mamaduka [dev note published](https://make.wordpress.org/core/2024/06/07/preparation-for-react-19-upgrade/)
  - [x] https://github.com/WordPress/gutenberg/pull/61202 `GB18.3` @Mamaduka

- [x] **Section Styles** @aaronrobertshaw [dev note published](https://make.wordpress.org/core/2024/06/24/section-styles/)
  - [x] https://github.com/WordPress/gutenberg/pull/57908 `GB18.5` @aaronrobertshaw 

- [x] **Improvements to active block variation detection** @ockham [dev note published](https://make.wordpress.org/core/2024/06/18/improvements-to-active-block-variation-detection/) 
  - [x] https://github.com/WordPress/gutenberg/pull/62088 `GB18.5` @ockham
  - [x] https://github.com/WordPress/gutenberg/pull/62031 `GB18.5` @ockham
  - [x] https://github.com/WordPress/gutenberg/pull/62272 `GB18.5` @ockham
  - [x] https://github.com/WordPress/gutenberg/pull/62325 `GB18.5` @ockham

- [x]  **Social Block updates** @talldan [dev note published](https://make.wordpress.org/core/2024/06/19/social-links-block-changes-in-wordpress-6-6/) 
  - [x] https://github.com/WordPress/gutenberg/pull/61396 `GB18.4` @talldan [dev note comment](https://github.com/WordPress/gutenberg/pull/61396#issuecomment-2175474614)
  - [x] https://github.com/WordPress/gutenberg/pull/61270 `GB18.3` @talldan [dev note comment](https://github.com/WordPress/gutenberg/pull/61270#issuecomment-2149451720)

- [x] **Editor: Unified Extensibility APIs in 6.6** @youknowriad 
[dev note published](https://make.wordpress.org/core/2024/06/18/editor-unified-extensibility-apis-in-6-6/)
  - [x] https://github.com/WordPress/gutenberg/pull/60961 `GB18.3` @ntsekouras [dev note comment](https://github.com/WordPress/gutenberg/issues/62096#issuecomment-2149124208)
  - [x] https://github.com/WordPress/gutenberg/pull/60853 `GB18.2` @youknowriad 
  - [x] https://github.com/WordPress/gutenberg/pull/60815 `GB18.2` @youknowriad 
  - [x] https://github.com/WordPress/gutenberg/pull/60814 `GB18.2` @youknowriad 
  - [x] https://github.com/WordPress/gutenberg/pull/60778 `GB18.2` @youknowriad 
  - [x] https://github.com/WordPress/gutenberg/pull/60033 `GB18.1` @youknowriad
  - [x] https://github.com/WordPress/gutenberg/pull/59985 `GB18.0` @youknowriad
  - [x] https://github.com/WordPress/gutenberg/pull/61134 `GB18.3` @youknowriad 
  - [x] https://github.com/WordPress/gutenberg/pull/60856 `GB18.2` @youknowriad

### Misc Dev Notes

- [x] Miscellaneous Editor changes in WordPress 6.6 @juanmaguitar [dev note published](https://make.wordpress.org/core/2024/06/24/miscellaneous-editor-changes-in-wordpress-6-6/)
  - [x] https://github.com/WordPress/gutenberg/pull/56469 `GB18.4` @carolinan (Block Styles) [dev note comment](https://github.com/WordPress/gutenberg/pull/56469#issuecomment-2144220175)
  - [x] https://github.com/WordPress/gutenberg/pull/61885 `GB18.5` @westonruter (Interactivity API) [dev note comment](https://github.com/WordPress/gutenberg/pull/61885#issuecomment-2176453184)
  - [x] https://github.com/WordPress/gutenberg/pull/60317 `GB18.1` @fabiankaegy (REST API) [dev note comment](https://github.com/WordPress/gutenberg/pull/60317#issuecomment-2156416761)
  - [x] https://github.com/WordPress/gutenberg/pull/54543 `GB18.4` @ellatrix, see https://github.com/WordPress/gutenberg/issues/62096#issuecomment-2149512285
  - [x] https://github.com/WordPress/gutenberg/pull/61529 `GB18.4` @gigitux [dev note comment](https://github.com/WordPress/gutenberg/pull/61529#issuecomment-2152872993)
  - [x] https://github.com/WordPress/gutenberg/pull/60068 `GB18.1` @fabiankaegy [dev note comment](https://github.com/WordPress/gutenberg/pull/60068#issuecomment-2156410031)
  - [x] https://github.com/WordPress/gutenberg/pull/60220 `GB18.3` @scruffian [dev note draft](https://github.com/WordPress/gutenberg/pull/60220#issuecomment-2175831480)
  - [x] https://github.com/WordPress/gutenberg/pull/47271 `GB18.4` @fabiankaegy [dev note comment](https://github.com/WordPress/gutenberg/pull/47271#issuecomment-2156414494)
  - [x] https://github.com/WordPress/gutenberg/pull/60715 `GB18.5` @richtabor [dev note comment](https://github.com/WordPress/gutenberg/pull/60715#issuecomment-2181924059)
  - [x] https://github.com/WordPress/gutenberg/pull/59531 `GB18.2` @t-hamano [dev note comment](https://github.com/WordPress/gutenberg/pull/59531#issuecomment-2182754264)

**Comment by ellatrix** [comment]
👋 curious why you added my name to the last item

**Comment by juanmaguitar** [comment]
> curious why you added my name to the last item

🤦‍♂️  Sorry @ellatrix, your ping was meant for https://github.com/WordPress/gutenberg/pull/54543
It's fixed now!

**Comment by ramonjd** [comment]
Thanks for this! I've updated the background image feature to cover the relevant PRs that, together, introduced the feature. I'll do a single dev note to cover all of them.

**Comment by aaronrobertshaw** [comment]
I've added https://github.com/WordPress/gutenberg/pull/61638 the list which altered some of the previous CSS specificity changes in PRs such as https://github.com/WordPress/gutenberg/pull/60106. A single dev note to cover the specificity changes is probably best.

**Comment by tellthemachines** [comment]
@juanmaguitar were any PRs from 17.8 included in this list? I notice you missed the [grid stabilisation](https://github.com/WordPress/gutenberg/pull/59051) and [row/column span](https://github.com/WordPress/gutenberg/pull/58539) ones even though they were correctly tagged. I added them to the list above.

**Comment by ramonjd** [comment]
Single dev note for the background image feature:

- https://github.com/WordPress/gutenberg/pull/59354#issuecomment-2138583222

Also added to issue description.

**Comment by juanmaguitar** [comment]
> were any PRs from 17.8 included in this list?  I notice you missed the https://github.com/WordPress/gutenberg/pull/59051 and https://github.com/WordPress/gutenberg/pull/58539 ones even though they were correctly tagged

@tellthemachines Thanks for spotting this.
You're right. I was using a query to get all `PRs with Needs Dev Note label that are closed and merged from March 5th (WP 6.6 Alpha begins)` when I should have got all  `PRs Needs Dev Note that are closed and merged from February 14th (release of Gutenberg 17.7, when PRs of GB 17.8 start)`. Still learning on this 😅

I have reviewed my process and queries to make sure I properly track all PRs from `GB 17.8` requiring DevNotes

For reference, these are the queries I'm using to track them:

[PRs Needs Dev Note that are closed and merged from February 14th (release of Gutenberg 17.7, when PRs of GB 17.8 start) ](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Needs+Dev+Note%22+is%3Aclosed+merged%3A%3E%3D2024-02-14)

<details>
<summary>Per GB version</summary>

- **GB 17.8**
  - Milestone [Gutenberg 17.8](https://github.com/WordPress/gutenberg/milestone/225?closed=1) (164 closed)
  - [PRs `Needs Dev Note` of milestone "Gutenberg 17.8"](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Needs+Dev+Note%22+milestone%3A%22Gutenberg+17.8%22) 
  - [PRs `Has Dev Note` of milestone "Gutenberg 17.8"](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Has+Dev+Note%22+milestone%3A%22Gutenberg+17.8%22+) 
- **GB 17.8**
  - Milestone [Gutenberg 17.9](https://github.com/WordPress/gutenberg/milestone/226?closed=1) (196 closed)
  - [PRs `Needs Dev Note` of milestone "Gutenberg 17.9"](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Needs+Dev+Note%22+milestone%3A%22Gutenberg+17.9%22+) 
  - [PRs `Has Dev Note` of milestone "Gutenberg 17.9"](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Has+Dev+Note%22+milestone%3A%22Gutenberg+17.9%22+) 
- **GB 18.0**
  - Milestone [Gutenberg 18.0](https://github.com/WordPress/gutenberg/milestone/227?closed=1) (208 closed)
  - [PRs `Needs Dev Note` of milestone "Gutenberg 18.0"](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Needs+Dev+Note%22+milestone%3A%22Gutenberg+18.0%22+) 
  - [PRs `Has Dev Note` of milestone "Gutenberg 18.0"](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Has+Dev+Note%22+milestone%3A%22Gutenberg+18.0%22+) 
- **GB 18.1**
  - Milestone [Gutenberg 18.1](https://github.com/WordPress/gutenberg/milestone/228?closed=1) (152 closed)
  - [PRs `Needs Dev Note` of milestone "Gutenberg 18.1"](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Needs+Dev+Note%22+milestone%3A%22Gutenberg+18.1%22+) 
  - [PRs `Has Dev Note` of milestone "Gutenberg 18.1"](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Has+Dev+Note%22+milestone%3A%22Gutenberg+18.1%22+) 
- **GB 18.2**
  - Milestone [Gutenberg 18.2](https://github.com/WordPress/gutenberg/milestone/229?closed=1) (236 closed)
  - [PRs `Needs Dev Note` of milestone "Gutenberg 18.2"](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Needs+Dev+Note%22+milestone%3A%22Gutenberg+18.2%22+) 
  - [PRs `Has Dev Note` of milestone "Gutenberg 18.2"](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Has+Dev+Note%22+milestone%3A%22Gutenberg+18.2%22+) 
- **GB 18.3**
  - Milestone [Gutenberg 18.3](https://github.com/WordPress/gutenberg/milestone/230?closed=1) (165 closed)
  - [PRs `Needs Dev Note` of milestone "Gutenberg 18.3"](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Needs+Dev+Note%22+milestone%3A%22Gutenberg+18.3%22+) 
  - [PRs `Has Dev Note` of milestone "Gutenberg 18.3"](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Has+Dev+Note%22+milestone%3A%22Gutenberg+18.3%22+) 
- **GB 18.4**
  - Milestone [Gutenberg 18.4](https://github.com/WordPress/gutenberg/milestone/231?closed=1) (185 closed) 
  - [PRs `Needs Dev Note` of milestone "Gutenberg 18.4"](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Needs+Dev+Note%22+milestone%3A%22Gutenberg+18.4%22+) 
  - [PRs `Has Dev Note` of milestone "Gutenberg 18.4"](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Has+Dev+Note%22+milestone%3A%22Gutenberg+18.4%22+)
- **GB 18.5**
  - Milestone [Gutenberg 18.5](https://github.com/WordPress/gutenberg/milestone/232?closed=1) (162 closed)
  - [PRs `Needs Dev Note` of milestone "Gutenberg 18.5"](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Needs+Dev+Note%22+milestone%3A%22Gutenberg+18.5%22+) 
  - [PRs `Has Dev Note` of milestone "Gutenberg 18.5"](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Has+Dev+Note%22+milestone%3A%22Gutenberg+18.4%22+)
  
</details>

**Comment by youknowriad** [comment]
For me I've always done `PRs with Needs Dev Note.` regardless of time. Some PRs make it as experimental before and need a dev note when they become stable. And when a PR had a dev note, we should just remove the tag. no?

**Comment by fabiankaegy** [comment]
To further complicate this I am not confident that we capture all the items that need a dev note at time of merge. So I spend my time digging through all merged PR's and adding the label now...

**Comment by juanmaguitar** [comment]
> For me I've always done `PRs with "Needs Dev Note"` regardless of time

@youknowriad the difference between [`PRs with "Needs Dev Note" label`](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Needs+Dev+Note%22+is%3Amerged) (266 total) vs [`PRs with "Needs Dev Note" label merged after Feb 24th 2024 (GB 17.8)`](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Needs+Dev+Note%22+is%3Aclosed+merged%3A%3E%3D2024-02-14) (27 closed) is huge. Isn't it more effective to just focus on the GB milestones included in the WP release?

>And when a PR had a dev note, we should just remove the tag. no?

By looking at the number of  [`PRs with "Needs Dev Note" label`](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Needs+Dev+Note%22+is%3Amerged) (266 total) from previous releases I'm not confident this is actually happening.

**Comment by youknowriad** [comment]
> By looking at the number of  [PRs with "Needs Dev Note" label](https://github.com/WordPress/gutenberg/issues?q=label%3A%22Needs+Dev+Note%22+is%3Amerged) (266 total) from previous releases I'm not confident this is actually happening.

Yeah, I'm guessing we stopped doing that at some point, and this is the mistake that we made. If you all agree that it's a better way to deal with that, we can correct it and just remove the label from these old PRs.

**Comment by mirka** [comment]
Flagging that my item #58974 in the Misc Dev Notes section was already included in the Dev Notes for 6.5 (#59155). Not exactly sure which was the correct version 😅

**Comment by juanmaguitar** [comment]
> Flagging that my item https://github.com/WordPress/gutenberg/pull/58974 in the Misc Dev Notes section was already included in the Dev Notes for 6.5 (https://github.com/WordPress/gutenberg/issues/59155). Not exactly sure which was the correct version 😅

Thanks for the heads up @mirka! You're right. The DevNote for that change is available [here](https://make.wordpress.org/core/2024/03/09/miscellaneous-editor-changes-in-wordpress-6-5/#customselectcontrol-deprecation). I have removed that PR from the tracking list above 👍

**Comment by tellthemachines** [comment]
I added a draft in make core for the new grid layout features: https://make.wordpress.org/core/?p=113315&preview=1&_ppp=1b26d1c689

**Comment by SantosGuillamot** [comment]
In [Block Bindings: Iteration for WP 6.6](https://github.com/WordPress/gutenberg/issues/60956), we haven't made any changes affecting public APIs. Basically, because we focused on the editor side, and those APIs are still private. Most of the changes affect the user experience and how everything works internally. We already had a [dev note for 6.5](https://make.wordpress.org/core/2024/03/06/new-feature-the-block-bindings-api/) covering the public APIs. Do we still need a new dev note? @juanmaguitar

**Comment by fabiankaegy** [comment]
@SantosGuillamot I think the fact that the post meta bindings are now editable in line deserve a quick dev note. Even if there are no actual API changes.

**Comment by juanmaguitar** [comment]
> Do we still need a new dev note?

@SantosGuillamot I replied [here](https://github.com/WordPress/gutenberg/issues/60956#issuecomment-2145601510)

**Comment by youknowriad** [comment]
I've started working on the [JSX Dev Note here](https://docs.google.com/document/d/1YyJQpP0M4rAtZC3zWN8P3eWdKr_KkZmeRnmaQCuaa6c/edit). I could use a review.

**Comment by ramonjd** [comment]
> I've started working on the [JSX Dev Note here](https://docs.google.com/document/d/1YyJQpP0M4rAtZC3zWN8P3eWdKr_KkZmeRnmaQCuaa6c/edit). I could use a review.

I added some things - nothing huge. Looks good!

**Comment by ntsekouras** [comment]
https://github.com/WordPress/gutenberg/pull/60961  shouldn't be a standalone dev note and probably a sentence should be included with the other unification efforts between site and post editor and new extensibility points.

> You can now extend templates panel in post editor too with the existing `PluginDocumentSettingPanel`. Previously you could do it only in site editor with `PluginTemplateSettingPanel`, which is now deprecated.

**Comment by juanmaguitar** [comment]
> with the other unification efforts between site and post editor and new extensibility points.

@ntsekouras I agree a [Misc "Extensibility of the Block Editor" Dev Note](https://github.com/WordPress/gutenberg/issues/62096#user-content-misc-extensibility-block-editor-dev-note) would be a good way to compile all the `[Feature] Extensibility` PRs included in WP 6.6. 

What do you think @youknowriad @fabiankaegy?

**Comment by youknowriad** [comment]
Not sure about other extensibility features but a single dev note about all these slots / unification efforts is a good idea yes.

**Comment by talldan** [comment]
I've added a [draft dev note](https://github.com/WordPress/gutenberg/pull/61270#issuecomment-2149451720) for [Remove Button component from social link block, replace with button element](https://github.com/WordPress/gutenberg/pull/61270#top) in a comment on the PR.

Will work on my other one tomorrow.

**Comment by ellatrix** [comment]
https://github.com/WordPress/gutenberg/pull/54543 should probably go in the extensibility dev note?

> RichText’s optional onSplit prop was deprecated and replaced with a `block.json` support key called `splitting`. The `onSplit` prop was only used by a few core blocks (paragraph, heading, list item, and button), so it’s not expected that this affects a lot of third party blocks. In any case, when the `onSplit` is used, splitting will still work, but can’t be controlled as granularly as before: the callback won’t be called and the block will split in a generic way.

**Comment by juanmaguitar** [comment]
> I've added a https://github.com/WordPress/gutenberg/pull/61270#issuecomment-2149451720 for https://github.com/WordPress/gutenberg/pull/61270#top in a comment on the PR.

Thanks @talldan 🙌
Would it make sense to publish a standalone DevNote to include `social-link` and `social-links` blocks updates (https://github.com/WordPress/gutenberg/pull/61396 & https://github.com/WordPress/gutenberg/pull/61270) ?

**Comment by juanmaguitar** [comment]
> https://github.com/WordPress/gutenberg/pull/54543 should probably go in the extensibility dev note?

 @ellatrix  I agree. I've moved this PR to that group. Thanks for the quick DevNote! 👏

**Comment by aaronrobertshaw** [comment]
I've added a [draft dev note](https://github.com/WordPress/gutenberg/pull/61638#issuecomment-2151295357) for the CSS specificity changes in 6.6 and included it in this issue's description.

**Comment by aaronrobertshaw** [comment]
A [draft dev note](https://github.com/WordPress/gutenberg/pull/57908#issuecomment-2151490938) for the [Section Styles](https://github.com/WordPress/gutenberg/pull/57908) feature has been added to that PR.

**Comment by Mamaduka** [comment]
Here's a draft for the ["Upgrade React to 18.3"](https://docs.google.com/document/d/1muEgZqUBQuqR48mTv3FP4N66u9535XxuYzh8qDHt_P8/edit) dev note.

**Comment by youknowriad** [comment]
The JSX dev note is ready to ship @juanmaguitar https://make.wordpress.org/core/?p=113385&preview=true 
Should I just go ahead and publish?

**Comment by jennydupuy** [comment]
Two untracked “Needs dev note”:
https://github.com/WordPress/gutenberg/pull/61529
https://github.com/WordPress/gutenberg/pull/62088

**Comment by juanmaguitar** [comment]
> The JSX dev note is ready to ship @juanmaguitar https://make.wordpress.org/core/?p=113385&preview=true
> Should I just go ahead and publish?

@youknowriad Yes, you can publish it. 
Thanks! 🙌

**Comment by juanmaguitar** [comment]
> Two untracked “Needs dev note”: https://github.com/WordPress/gutenberg/pull/61529 & https://github.com/WordPress/gutenberg/pull/62088

Thanks @jennydupuy! 👏
I have added them to description of this issue.

Pinging @ockham (https://github.com/WordPress/gutenberg/pull/62088) and @gigitux (https://github.com/WordPress/gutenberg/pull/61529) for awareness

**Comment by juanmaguitar** [comment]
@aaronrobertshaw Thanks for the updates! 

> I've added a https://github.com/WordPress/gutenberg/pull/61638#issuecomment-2151295357 for the CSS specificity changes in 6.6 and included it in this issue's description.

Does this DevNote cover changes done in https://github.com/WordPress/gutenberg/pull/61638,  https://github.com/WordPress/gutenberg/pull/60106 & https://github.com/WordPress/gutenberg/pull/59457 ?

Also, when they're ready for review, could you post your DevNotes (https://github.com/WordPress/gutenberg/pull/61638#issuecomment-2151295357 and https://github.com/WordPress/gutenberg/pull/57908#issuecomment-2151490938)  as drafts in https://make.wordpress.org/core and enable the "public post preview" link to share them in [the project](https://github.com/orgs/WordPress/projects/202).

**Comment by gigitux** [comment]
> > Two untracked “Needs dev note”: #61529 & #62088
> 
> Thanks @jennydupuy! 👏 I have added them to description of this issue.
> 
> Pinging @ockham (#62088) and @gigitux (#61529) for awareness

Thanks for the ping! I added my dev notes [here](https://github.com/WordPress/gutenberg/pull/61529#issuecomment-2152872993). Happy to revisit it if needed!

**Comment by ockham** [comment]
> Pinging @ockham (#62088)

Thank you for the ping! We had a few other changes related to active block variation detection merged recently (#62031, #62272, #62325), so we might actually want a stand-alone Dev Note to cover them all. I've started a draft that I will share shortly.

**Comment by ockham** [comment]
> We had a few other changes related to active block variation detection merged recently (#62031, #62272, #62325), so we might actually want a stand-alone Dev Note to cover them all. I've started a draft that I will share shortly.

Here's the [draft](https://make.wordpress.org/core/?p=113407&preview=true). I've also added an item to the "Stand-alone posts" section above, with a link to the Dev Note draft (plus the four PRs that it covers).

cc/ @gziolo

**Comment by aaronrobertshaw** [comment]
> Does this DevNote cover changes done in https://github.com/WordPress/gutenberg/pull/61638, https://github.com/WordPress/gutenberg/pull/60106 & https://github.com/WordPress/gutenberg/pull/59457 ?

@juanmaguitar yes, the [dev note](https://make.wordpress.org/core/wp-admin/post.php?post=113422&action=edit) covers the end result of all those specificity related PRs.

> Also, when they're ready for review, could you post your DevNotes (https://github.com/WordPress/gutenberg/pull/61638#issuecomment-2151295357 and https://github.com/WordPress/gutenberg/pull/57908#issuecomment-2151490938) as drafts

✅ Done.

**Comment by gziolo** [comment]
> Here's the [draft](https://make.wordpress.org/core/?p=113407&preview=true). I've also added an item to the "Stand-alone posts" section above, with a link to the Dev Note draft (plus the four PRs that it covers).

Looks good from the technical point of view 💯 That’s a nice set of improvements coming in WP 6.6. I think we will need to explicitly mention in https://developer.wordpress.org/block-editor/reference-guides/block-api/block-variations/ what functionality is exclusively working with WP 6.6 and higher. I drafted a fix in https://github.com/WordPress/gutenberg/pull/62399.

**Comment by Mamaduka** [comment]
@juanmaguitar, the ["Preparation for React 19 Upgrade"](https://make.wordpress.org/core/?p=113426&preview=1&_ppp=1ff9b7860a) draft is ready for review on make blog. Let me know if it's good to publish.

**Comment by juanmaguitar** [comment]
> Let me know if it's good to publish.

@Mamaduka I did a proofreading review of [Preparation for React 19 Upgrade](https://make.wordpress.org/core/?p=113426&preview=1&_ppp=1ff9b7860a) and it looks good to be published 👍

<details>

<summary>✅ Proofreading</summary>

- 🟢  _at least_ two reviewers | see [Should dev notes be reviewed?](https://make.wordpress.org/core/handbook/tutorials/writing-developer-notes/#should-dev-notes-be-reviewed)
- 🟢 use of "I" and "we" and simple writing | see [Style and substance](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#style-and-substance)
- 🟢 proper credits (I added myself for proofreading) | see [Attribution](https://make.wordpress.org/core/handbook/tutorials/writing-developer-notes/#attribution)
- 🟢 proper tagging and categorizing | see [Tagging and categorizing](https://make.wordpress.org/core/handbook/tutorials/writing-developer-notes/#tagging-and-categorizing)
- 🟢 Grammarly check

</details>

**Comment by juanmaguitar** [comment]
@ramonjd and @ajlende, when you're dev notes as comments (see "Stand-alone posts" section in the description of this issue) are ready for review, could you post them as drafts in https://make.wordpress.org/core and enable the "public post preview" link to share them in [the project](https://github.com/orgs/WordPress/projects/202)?

**Comment by fabiankaegy** [comment]
I just added a draft for #60068 here: https://github.com/WordPress/gutenberg/pull/60068#issuecomment-2156410031

Any feedback would be greatly appreciated :)

**Comment by fabiankaegy** [comment]
Also added a draft for #47271 here: https://github.com/WordPress/gutenberg/pull/47271#issuecomment-2156414494

**Comment by fabiankaegy** [comment]
And finally here is the draft for #60317 here: https://github.com/WordPress/gutenberg/pull/60317#issuecomment-2156416761

**Comment by juanmaguitar** [comment]
The following DevNotes are drafted but need a technical review (I can do the proofreading one)

- [Grid layout type](https://make.wordpress.org/core/?p=113315) by @tellthemachines 
- [Site-wide background images](https://github.com/WordPress/gutenberg/pull/59354#issuecomment-2138583222) by @ramonjd 
- [Theme.json version 3](https://github.com/WordPress/gutenberg/pull/58409#issuecomment-2078077477) by @ajlende 
- [CSS Specificity](https://make.wordpress.org/core/?p=113422&preview=1&_ppp=136845c20e) by @aaronrobertshaw 
- [Improvements to active block variation detection](https://github.com/orgs/WordPress/projects/202/views/1?pane=issue&itemId=66552849) by @ockham 
- [Section Styles](https://make.wordpress.org/core/?p=113424&preview=1&_ppp=d69abc08a2) by @aaronrobertshaw 

In case someone can help with these reviews, please share in this tracking issue the result of your review.

**Comment by juanmaguitar** [comment]
Friendly reminder for PR owners to draft the following dev notes by the end of this week if possible:

- ~[#61885](https://github.com/WordPress/gutenberg/pull/61885) @westonruter~
- ~[#60220](https://github.com/WordPress/gutenberg/pull/60220) @scruffian~
- [#60715](https://github.com/WordPress/gutenberg/pull/60715) @richtabor
- ~[#61396](https://github.com/WordPress/gutenberg/pull/61396) @talldan~
- ~[#60853](https://github.com/WordPress/gutenberg/pull/60853) [#60815](https://github.com/WordPress/gutenberg/pull/60815) [#60814](https://github.com/WordPress/gutenberg/pull/60814) [#60778](https://github.com/WordPress/gutenberg/pull/60778) [#60033](https://github.com/WordPress/gutenberg/pull/60033) [#59985](https://github.com/WordPress/gutenberg/pull/59985) [#61134](https://github.com/WordPress/gutenberg/pull/61134) [#60856](https://github.com/WordPress/gutenberg/pull/60856) @youknowriad~

**Comment by ramonjd** [comment]
Hi folks, 

Here is a Make Core post draft for the [Background Image Dev Note](https://github.com/WordPress/gutenberg/pull/59354#issuecomment-2138583222) for your review:

https://make.wordpress.org/core/?p=113594&preview=1&_ppp=2cc45da4df

Thank you!

**Comment by youknowriad** [comment]
The Extensibility unification dev note is ready for review. cc @juanmaguitar  https://make.wordpress.org/core/?p=113603&preview=1&_ppp=4d71f9add1

**Comment by talldan** [comment]
@juanmaguitar Sorry for the delay, added a dev note for the other social links issue here - https://github.com/WordPress/gutenberg/pull/61396#issuecomment-2175474614

I'd be happy to see the two dev notes combined if you think that's best, though perhaps because one only affects social links when used in the navigation block, it makes it a little more particular.

**Comment by juanmaguitar** [comment]
@talldan Thanks for the drafts!

> I'd be happy to see the two dev notes combined if you think that's best

In order to get the DevNote published, could you take care of the following actions?
- Shape a draft post using your notes ([#61396-comment](https://github.com/WordPress/gutenberg/pull/61396#issuecomment-2175474614) and [#61270-comment](https://github.com/WordPress/gutenberg/pull/61270#issuecomment-2149451720)) in https://make.wordpress.org/core 
- Enable the "public post preview" link to share them in [the project](https://github.com/orgs/WordPress/projects/202)
- Get a technical review done on the draft - I think it would be easier for you to find the right person for the technical review, but I can also help with that technical review (doing it myself or helping find a reviewer) if you need me to

With these actions done, I can take care of a [proofreading review](https://github.com/WordPress/gutenberg/issues/62096#issuecomment-2154628098) to get the DevNote ready to be published

**Comment by juanmaguitar** [comment]
> The Extensibility unification dev note is ready for review. cc @juanmaguitar https://make.wordpress.org/core/?p=113603&preview=1&_ppp=4d71f9add1

Thanks @youknowriad, for sharing the draft post. 
Who do you think can do a technical review of the post? ~@ntsekouras could you do it~? 

With the technical review done I can take care of a final [proofreading](https://github.com/WordPress/gutenberg/issues/62096#issuecomment-2154628098) to get the DevNote ready to be published

**Comment by youknowriad** [comment]
> Who do you think can do a technical review of the post? @ntsekouras could you do it?

I already had a couple persons do a technical review there but happy, let me add the props (I forgot). Happy to get more reviews.

**Comment by juanmaguitar** [comment]
> I already had a couple persons do a technical review there but happy, let me add the props (I forgot). Happy to get more reviews.

Thanks @youknowriad for adding the props. Those technical reviews are more than enough. I did the proofreading review and added myself to the props. 

<details>

<summary>✅ Proofreading</summary>

- 🟢  _at least_ two reviewers | see [Should dev notes be reviewed?](https://make.wordpress.org/core/handbook/tutorials/writing-developer-notes/#should-dev-notes-be-reviewed)
- 🟢 use of "I" and "we" and simple writing | see [Style and substance](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#style-and-substance)
- 🟢 proper credits in italic (I added myself for proofreading) | see [Attribution](https://make.wordpress.org/core/handbook/tutorials/writing-developer-notes/#attribution)
- 🟢 proper tagging and categorizing | see [Tagging and categorizing](https://make.wordpress.org/core/handbook/tutorials/writing-developer-notes/#tagging-and-categorizing)
- 🟢 Grammarly check

</details>

The post is ready to be published :passenger_ship:

**Comment by scruffian** [comment]
Also added a dev note draft here: https://github.com/WordPress/gutenberg/pull/60220#issuecomment-2175831480

**Comment by cbravobernal** [comment]
Added a dev note for Interactivity API new directives: https://github.com/WordPress/gutenberg/pull/61885#issuecomment-2176453184

**Comment by talldan** [comment]
> In order to get the DevNote published, could you take care of the following actions?

@juanmaguitar I've carried out those steps, @ramonjd gave it a tech review. It's on the board now with the status 'Needs 2nd review", I wasn't sure if 1st review is the technical review, but that was my guess.

**Comment by juanmaguitar** [comment]
Thanks a lot @talldan! 🙌
I did a last proofreading review and published the post. 
It's available at https://make.wordpress.org/core/2024/06/19/social-links-block-changes-in-wordpress-6-6/

**Comment by t-hamano** [comment]
@juanmaguitar I added #59531 to the "Misc Dev Notes" section and wrote [a dev note](https://github.com/WordPress/gutenberg/pull/59531#issuecomment-2182754264). Sorry for the delay 🙏

**Comment by westonruter** [comment]
> Added a dev note for Interactivity API new directives: [#61885 (comment)](https://github.com/WordPress/gutenberg/pull/61885#issuecomment-2176453184)

This has been iterated on a bit more.

**Comment by juanmaguitar** [comment]
I've started a [Miscellaneous Editor changes in WordPress 6.6](https://make.wordpress.org/core/?p=113816&preview=1&_ppp=768f9b541b) which includes all the short DevNotes ([Misc Dev Notes](https://github.com/WordPress/gutenberg/issues/62096)). I plan on asking for a technical review of this whole post on Monday and doing another proofreading review myself, but any reviews that you can get done by then would speed up the review/publication process of this Misc DevNote.

> [!NOTE] 
> Please, **add any reviewers' names in the proper props place at [Miscellaneous Editor changes in WordPress 6.6](https://make.wordpress.org/core/?p=113816&preview=1&_ppp=768f9b541b)**.

The DevNotes included in [Miscellaneous Editor changes in WordPress 6.6](https://make.wordpress.org/core/?p=113816&preview=1&_ppp=768f9b541b) are:

  - [x] https://github.com/WordPress/gutenberg/pull/56469 `GB18.4` @carolinan (Block Styles) [dev note comment](https://github.com/WordPress/gutenberg/pull/56469#issuecomment-2144220175)
  - [x] https://github.com/WordPress/gutenberg/pull/61885 `GB18.5` @westonruter (Interactivity API) [dev note comment](https://github.com/WordPress/gutenberg/pull/61885#issuecomment-2176453184)
  - [x] https://github.com/WordPress/gutenberg/pull/60317 `GB18.1` @fabiankaegy (REST API) [dev note comment](https://github.com/WordPress/gutenberg/pull/60317#issuecomment-2156416761)
  - [x] https://github.com/WordPress/gutenberg/pull/54543 `GB18.4` @ellatrix, see https://github.com/WordPress/gutenberg/issues/62096#issuecomment-2149512285
  - [x] https://github.com/WordPress/gutenberg/pull/61529 `GB18.4` @gigitux [dev note comment](https://github.com/WordPress/gutenberg/pull/61529#issuecomment-2152872993)
  - [x] https://github.com/WordPress/gutenberg/pull/60068 `GB18.1` @fabiankaegy [dev note comment](https://github.com/WordPress/gutenberg/pull/60068#issuecomment-2156410031)
  - [x] https://github.com/WordPress/gutenberg/pull/60220 `GB18.3` @scruffian [dev note draft](https://github.com/WordPress/gutenberg/pull/60220#issuecomment-2175831480)
  - [x] https://github.com/WordPress/gutenberg/pull/47271 `GB18.4` @fabiankaegy [dev note comment](https://github.com/WordPress/gutenberg/pull/47271#issuecomment-2156414494)
  - [x] https://github.com/WordPress/gutenberg/pull/60715 `GB18.5` @richtabor [dev note comment](https://github.com/WordPress/gutenberg/pull/60715#issuecomment-2181924059)
  - [x] https://github.com/WordPress/gutenberg/pull/59531 `GB18.2` @t-hamano [dev note comment](https://github.com/WordPress/gutenberg/pull/59531#issuecomment-2182754264)

**Comment by juanmaguitar** [comment]
Closing this issue as all the Block Editor DevNotes have been published as well as the [WordPress 6.6 Field Guide](https://make.wordpress.org/core/2024/06/25/wordpress-6-6-field-guide/) compiling them all

Thank you to all the developers pinged in this issue (and via Slack) for your collaboration in getting the DevNotes published in time for WP 6.6 RC1 release! You all rock!! 🙌
