### ISSUE TITLE
My patterns not available when inserting into colums

### ISSUE THREAD

**Issue by neiljames** [WordPress/gutenberg#68277]
### Description

When I try to insert one of my patterns into a column there are no my patterns available.

### Step-by-step reproduction instructions

Add two colums
Click on one column to add a pattern
There are no my patterns available

### Environment info

Wordpress version 6.7.1
No Gutenberg plugin installed
Twenty Twentfour theme

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by SainathPoojary** [comment]
Hi @neiljames,

Thank you for reporting this issue!


Here are the steps I followed to replicate it. Please let me know if I missed anything:
1. Created a custom pattern and added it to a plugin.
2. Navigated to Posts >  Add New to open the block editor.
3. Inserted a Columns block with a two-column layout.
4. Clicked the + button inside one of the columns to add content.
5. Searched for the pattern and added it.

I was able to add my custom pattern in WP 6.7.1, here's the video to demonstrate it:

https://github.com/user-attachments/assets/b96b23cf-e013-4a45-8bcd-62529f27cb5b



Additionally I also tried it in latest trunk version, in it there is no suggestion for patterns in quick inserter.

https://github.com/user-attachments/assets/28aa29bb-475c-49a7-9322-4a3191abd73e

Could you provide more details to help reproduce the issue?

**Comment by neiljames** [comment]
Hi,
The two images are what I encounter when I try to add one of My Patterns to a column within a multi column block,
This first one is me selecting the placement for a Pattern

![Image](https://github.com/user-attachments/assets/cb4ba81f-c7e9-466b-9a4b-adf3f6212c68)

The Second image shows no patterns are available after I select My Patterns 

![Image](https://github.com/user-attachments/assets/a85fe723-6ab6-4293-a632-483932c1e751)

**Comment by carolinan** [comment]
Can you try again with all plugins disabled?

**Comment by neiljames** [comment]
Certainly Can,
You will see by the dashboard all of the plugins have been disabled.


1st image is trying to insert into a full width column
pattern-full-column.jpg

2nd image is trying to insert a pattern into 1st column of a three column block
pattern-part-column.jpg

![Image](https://github.com/user-attachments/assets/79bd0ca2-c007-4105-8322-a4b007244de5)

![Image](https://github.com/user-attachments/assets/7e083694-6296-409b-bbe7-391313b85a93)

**Comment by carolinan** [comment]
I have tested this again today.

Without Gutenberg, using 6.7.1:

✅ 
I created two new patterns using the interface. One synced, one non-synced. So I am not using a pattern from a plugin.
I created a new post and added a 3 column columns block.
I clicked the "Add block" inserter inside a column. When I type in my pattern name in the search, it shows up. When I select the pattern it is inserted correctly.

I clicked the "Add block" inserter inside a column.
I chose "Browse all".
This opens the sidebar. I chose "Patterns" and then the "My patterns" category.
✅  My patterns show.
✅  The non-synced pattern is inserted correctly.
❌ the synced pattern is not inserted. Even though the notice says it was inserted.


I clicked the "Add block" inserter inside a column.
I chose "Browse all".
This opens the sidebar. I chose "Patterns" and then the "My patterns" category.
✅  My patterns show.
✅  The non-synced pattern is inserted correctly.
I turn off zoom out before trying to insert the synced pattern.
✅  The synced pattern is inserted correctly.


With Gutenberg active:
I clicked the "Add block" inserter inside a column. When I type in my pattern name in the search, it does not show up. This was an intentional change, and there is a discussion about reverting it.

I chose "Browse all".
This opens the sidebar. 
I search for my pattern names using he search field:
✅  My patterns show.
I chose "Patterns" and then the "My patterns" category:
✅  My patterns show.
✅  The non-synced pattern is inserted correctly.
✅  The synced pattern is inserted correctly.

The difference is, with the Gutenberg plugin active, the zoom out mode is not enabled by default, and the synced pattern is inserted correctly.


@neiljames Does this reflect what you are seeing? I am still not able to reproduce the original report.
If this is what you are experiencing, it has been solved in the plugin. I can't say for sure whether it will be fixed in 6.7.2.

**Comment by neiljames** [comment]
This is my experience which you describe below when adding a 3 column block on a new page,

I clicked the "Add block" inserter inside a column.
I chose "Browse all".
This opens the sidebar. I chose "Patterns" and then the "My patterns" category.
✅ My patterns show.
✅ The non-synced pattern is inserted correctly.
❌ the synced pattern is not inserted. Even though the notice says it was inserted.



When I add 3 column block to an existing page I get this response

No results found as shown in image 2.

This is with the core wordpress patterns, I think I might have confused things by referring to Gutenberg.
I do not have a Gutenberg plug in installed I only use the blocks/patterns already installed within the core wordpress environment.
I think I should wait until 6.7.2 and see if it has been fixed and take it from there.

**Comment by neiljames** [comment]
Hey, I responded 2weeks ago and figured you had this covered with the 6.7.2 upgrade. I did as you asked and disabled all the plugins and my response 2 weeks ago showed no improvement.
I thought I might have misled you by giving the impression I was using a plugin but wasn’t, it was the core   Blocks.
More than happy to try anything to help.
Thanks,
@neiljames

**Comment by carolinan** [comment]
Hi @neiljames
It takes time to test, identify, make decisions and then fix possible problems.

The reason why you may be asked if you are using Gutenberg is because issues related to the blocks and the editor are fixed in Gutenberg first.

If you don't see an update on your issues, it likely has not progressed.

**Comment by carolinan** [comment]
I was able to confirm that with Gutenberg active, synced patterns can be inserted when new pages are created and the zoom out mode is active. I believe this has been fixed already.

**Comment by neiljames** [comment]
I can confirm the bug has not been fixed with v6.7.2

My patterns are available when I wish to add into a page only when I use a single column.
BUT
If I want to add my pattern into a multi column block it still shows no patterns available.

I click Page
I select  Column 2 in a group with a 2 column block
I select + to add block and open Browse All
The side bar with Blocks, Patterns, Media opens
I select patterns and as previously commented (image above) the message on the sidebar is telling me  No results found with a Lego Block Icon above it
I use the patterns search function and ask for a pattern and am told No results found
All plugins were disabled at the time

I am using the Twenty Twenty-Four Theme

**Comment by carolinan** [comment]
I mentioned it was fixed when Gutenberg is active. Not 6.7.2.

**Comment by neiljames** [comment]
Hi There,
I think it was me that was hoping it would be fixed.

**Comment by markolbert** [comment]
This problem definitely still exists in 6.7.2. The workaround I use is to add the pattern outside the columns block, and then move the pattern inside the column where I want to insert it. That works.

**Comment by Mamaduka** [comment]
@markolbert, @neiljames, can you still reproduce the problem with WP 6.8?

**Comment by neiljames** [comment]
@Mamaduka I have upgraded to 6.8.1 and the blocks are now working fine

**Comment by Mamaduka** [comment]
Thanks for the confirmation, @neiljames!
