### ISSUE TITLE
[wordpress/script] wp-scripts build-blocks-manifest removes manifest file on start

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/gutenberg#69565]
### Description

When using `"start": "wp-scripts start && wp-scripts build-blocks-manifest"` and running `npm run start`, `blocks-manifest.php` file is removed.

When using `"build": "wp-scripts build && wp-scripts build-blocks-manifest"` and running `npm run build`, `blocks-manifest.php` file is generated as it should.

### Step-by-step reproduction instructions

1. npx @wordpress/create-block@latest test-plugin
1. cd test-plugin
1. npm run build (blocks-manifest.php generated)
1. npm run start (blocks-manifest.php deleted)

### Environment info

- WordPress 6.7.2
- 2025 theme
- Node 22.14.0

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by itsseanl** [comment]
I'm having the same issue as of today. `npm run build` creates the manifest, but `npm run start` deletes it, and results in a site-wide critical error. 

I'm running node v22.13.1, wordpress 6.7.2,  and a bare-bones custom block theme.

**Comment by itsseanl** [comment]
I noticed a block project I created a few days ago specifies @wordpress/scripts ^v30.12.0, whereas the one created today specifies ^v30.13.0. I tried to specify the older version in my package.json and reinstall dependencies, but that does not seem to resolve the issue.

**Comment by t-hamano** [comment]
Thanks for the report. I was able to replicate it.

I think [this discussion](https://github.com/WordPress/gutenberg/pull/69446#discussion_r1983000425) may be related to this issue. cc @felixarntz @gziolo

**Comment by itsseanl** [comment]
I took a look at that referenced discussion and did some digging (I suck at webpack), came up with a possible solution 

in @wordpress/wp-scripts, you can update the webpack.config.js to include something like 

```
const exec = require('child_process').exec;
const BlockManifest = {

	apply(compiler){
		compiler.hooks.afterEmit.tap('BlockManifest', (compilation) =>{
			process.stdout.write('ran after');
			exec(`wp-scripts build-blocks-manifest`, (error, stdout, stderr) => {
				if (error){
					console.error(`exec error: ${error}`);
				}
				console.log(`${stdout}`);
				if (stderr){
					console.error(`stderr: ${stderr}`);
				}
		});
		});
	}
};
```

and then add that to the plugins in ScriptConfig

[here's](https://gist.github.com/itsseanl/6d6bbd5319235e66e7311b4a74d5cf1a) my updated webpack.config.js, tested and working in my project

**Comment by 2ndkauboy** [comment]
We just ran into that issue at Cloudfest Hackathon. How about changing the start task like this?

```
"start": "wp-scripts start & wp-scripts build-blocks-manifest"
```

By using a single `&`, the seconds tasks always run, even if the first one is not successful (or in case of `start` never terminates).

**Comment by Hakira-Shymuy** [comment]
work around for it??

@2ndkauboy your method isnt work for me, it puts the manifest there but removes it 1 second after, at least in my case

**Comment by emergoncalves** [comment]
I solved this in the following way:

add this in package.json

```
"build": "wp-scripts build && wp-scripts build-blocks-manifest --output=dist/blocks-manifest.php",
"start": "wp-scripts start",
"build-manifest": "wp-scripts build-blocks-manifest --output=dist/blocks-manifest.php"
```

I edited the block initialization file to use the /dist folder:

```
function studiowp_topbar_block_block_init()
{
	if (function_exists('wp_register_block_types_from_metadata_collection')) { // Function introduced in WordPress 6.8.
		wp_register_block_types_from_metadata_collection(__DIR__ . '/dist', __DIR__ . '/dist/blocks-manifest.php');
	} else {
		if (function_exists('wp_register_block_metadata_collection')) { // Function introduced in WordPress 6.7.
			wp_register_block_metadata_collection(__DIR__ . '/dist', __DIR__ . '/dist/blocks-manifest.php');
		}
		$manifest_data = require __DIR__ . '/dist/blocks-manifest.php';
		foreach (array_keys($manifest_data) as $block_type) {
			register_block_type(__DIR__ . "/build/{$block_type}");
		}
	}
}
```
Use `npm run build-manifest` before using `npm run start`, and now the **block-manifest.php** file will be preserved because it will be in the _/dist_ folder, and no longer in the _/build_ folder which is renewed when a change is detected by the watch.

The build-blocks-manifest provides input and output parameters, and moving the file out of the build prevents it from being removed.

https://github.com/WordPress/gutenberg/tree/trunk/packages/scripts#build-blocks-manifest

**Comment by Hakira-Shymuy** [comment]
> I solved this in the following way:
> 
> add this in package.json
> 
> ```
> "build": "wp-scripts build && wp-scripts build-blocks-manifest --output=dist/blocks-manifest.php",
>   "build-manifest": "wp-scripts build-blocks-manifest --output=dist/blocks-manifest.php"
> ```
> 
> I edited the block initialization file to use the /dist folder:
> 
> ```
> function studiowp_topbar_block_block_init()
> {
> 	if (function_exists('wp_register_block_types_from_metadata_collection')) { // Function introduced in WordPress 6.8.
> 		wp_register_block_types_from_metadata_collection(__DIR__ . '/dist', __DIR__ . '/dist/blocks-manifest.php');
> 	} else {
> 		if (function_exists('wp_register_block_metadata_collection')) { // Function introduced in WordPress 6.7.
> 			wp_register_block_metadata_collection(__DIR__ . '/dist', __DIR__ . '/dist/blocks-manifest.php');
> 		}
> 		$manifest_data = require __DIR__ . '/dist/blocks-manifest.php';
> 		foreach (array_keys($manifest_data) as $block_type) {
> 			register_block_type(__DIR__ . "/build/{$block_type}");
> 		}
> 	}
> }
> ```
> 
> Use `npm run build-manifest` before using `npm run start`, and now the **block-manifest.php** file will be preserved.
> 
> The build-blocks-manifest provides input and output parameters, and moving the file out of the build prevents it from being removed.

the problem here is not with the build but with the start
on build everything works okay
but with npm start while webpack is watching it removes the manifest

**Comment by emergoncalves** [comment]
> > I solved this in the following way:
> > add this in package.json
> > ```
> > "build": "wp-scripts build && wp-scripts build-blocks-manifest --output=dist/blocks-manifest.php",
> >   "build-manifest": "wp-scripts build-blocks-manifest --output=dist/blocks-manifest.php"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I edited the block initialization file to use the /dist folder:
> > ```
> > function studiowp_topbar_block_block_init()
> > {
> > 	if (function_exists('wp_register_block_types_from_metadata_collection')) { // Function introduced in WordPress 6.8.
> > 		wp_register_block_types_from_metadata_collection(__DIR__ . '/dist', __DIR__ . '/dist/blocks-manifest.php');
> > 	} else {
> > 		if (function_exists('wp_register_block_metadata_collection')) { // Function introduced in WordPress 6.7.
> > 			wp_register_block_metadata_collection(__DIR__ . '/dist', __DIR__ . '/dist/blocks-manifest.php');
> > 		}
> > 		$manifest_data = require __DIR__ . '/dist/blocks-manifest.php';
> > 		foreach (array_keys($manifest_data) as $block_type) {
> > 			register_block_type(__DIR__ . "/build/{$block_type}");
> > 		}
> > 	}
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Use `npm run build-manifest` before using `npm run start`, and now the **block-manifest.php** file will be preserved.
> > The build-blocks-manifest provides input and output parameters, and moving the file out of the build prevents it from being removed.
> 
> the problem here is not with the build but with the start on build everything works okay but with npm start while webpack is watching it removes the manifest

It would be removed if it were in the /build folder, but since it will be in the /dist folder, it will remain preserved.

The solution I suggested (which I am currently using and is functioning correctly) aims to resolve the issue with `npm run start`, and not `npm run build`.

**Comment by felixarntz** [comment]
I think the PR #69578 (based on @itsseanl's code above) is a cleaner solution, because it conditionally ties building the blocks manifest to the Webpack process. That way there's no need to have multiple commands in a single `package.json` script.

In the meantime, I think the above are reasonable workarounds until this has been fixed.

**Comment by audrasjb** [comment]
Hello, maybe this is a good candidate for a backport to branch 6.8 @joemcgill @Mamaduka ?

**Comment by Mamaduka** [comment]
@audrasjb, the `create-block` and `scripts` library/packages aren't bundled with WP and have separate release cycles. Unless the manifest fix is required for the WP build process, I don't see a reason for backporting.

P.S. I don't mind doing the backport; I just want to make sure we have a clear reason for it.

**Comment by felixarntz** [comment]
+1, since none of these changes are bundled in WordPress Core, I don't think a backport would help. Basically, this bug is fixed as soon as the new versions of the two NPM packages are released.

**Comment by Mamaduka** [comment]
The fix should be included in yesterday’s package release.

**Comment by audrasjb** [comment]
Thanks both for the confirmation 👍

**Comment by srikat** [comment]
> The fix should be included in yesterday’s package release.

Trying out @wordpress/create-block@latest for the first time and I think the problem is still there.

![Image](https://github.com/user-attachments/assets/581907b9-627d-425d-8cf3-5ac1966b7ad3)

**Comment by srikat** [comment]
> > The fix should be included in yesterday’s package release.
> 
> Trying out @wordpress/create-block@latest for the first time and I think the problem is still there.
> 
> ![Image](https://github.com/user-attachments/assets/581907b9-627d-425d-8cf3-5ac1966b7ad3)

The workaround/manual fix does the job https://github.com/WordPress/gutenberg/pull/69578#issuecomment-2763320067.

But the core issue still remains.

**Comment by michakrapp** [comment]
@srikat 
> But the core issue still remains.

You have to use the parameter for the start script like
`wp-scripts start --blocks-manifest`
