### ISSUE TITLE
Iteration: 6.9 Microsite

### ISSUE THREAD

**Issue by fcoveram** [WordPress/gutenberg#71822]
## What is this?

This tracking issue will cover the work needed for the 6.9 release microsite. The microsite is a landing page on WordPress.org that showcases all the highlighted features and enhancements for a particular release. Aesthetically, the design for this microsite has followed general WordPress branding instead of the unique flavor of any particular release.

Examples of previous highlight grids for reference:

[6.8 microsite](https://wordpress.org/download/releases/6-8/)
[6.7 microsite](https://wordpress.org/download/releases/6-7/)
[6.6 microsite](https://wordpress.org/download/releases/6-6/)

## Timing

- [x] Copy draft: ASAP
- [x] Initial design: November 11 2025, in line with RC1
- [ ] Final design: [TBD]

The main date we need to keep in mind is RC1 as we likely want to align with what's being shared on the About page and it would be helpful to have some shared approach there.

## Content

The microsite is distinct on its own meant for a broader outside of WordPress use case yet also should share structure and highlights with the About page. Because of this, we need to align with the [About page effort](https://core.trac.wordpress.org/ticket/64022) and ensure some cross pollination there.

cc @richtabor @jasmussen @annezazu. Please ping anyone else needed in this task.

**Comment by fcoveram** [comment]
Sharing a first draft of the microsite that reuses the content of the four highlighted features shared on the about page issue, plus content for the feature details and secondary features. All texts in red are pending.

Kudos to @marko-srb and @jasmussen 

<img width="2076" alt="Image" src="https://github.com/user-attachments/assets/7ecc706e-363b-4ca8-95f5-0668ebec7adf" />

---

## Design

You can see all designs in [this Figma file](https://www.figma.com/design/qhBsaACcBE9YjHYnJuNk4v/6.9-Highlight-Grid--Microsite--About-Page?node-id=6560-65024&t=ZHCr7XKB53yQCz3a-4).

**Comment by jeffpaul** [comment]
As noted in the highlight grid GitHub issue and about page Trac ticket, I would recommend referring to the feature as "Notes" and not "Block notes."  Otherwise is this microsite effort still underway and is there anything needed from the contributors working on the Notes feature in #66377?

**Comment by fcoveram** [comment]
Here is a new version of the microsite with the latest changes applied in [the grid](https://github.com/WordPress/gutenberg/issues/71818#issuecomment-3531477380) and the [About page](https://core.trac.wordpress.org/ticket/63941) content.

<img width="2076" alt="Image" src="https://github.com/user-attachments/assets/0a739c2c-4564-4cb2-a43b-916c2fd332a0" />

---

As noted in the grid ticket, I wanted to recognize contributors participation by showing their names and profile image. In this case I added @Mamaduka and @kjnanda. Please let me know if you both are fine with this idea. Otherwise I can easily change it and try other contributors.

**Comment by Mamaduka** [comment]
> Please let me know if you both are fine with this idea.

Of course. Thanks for the ping, @fcoveram!

**Comment by kjnanda** [comment]
Absolutely fine! Thank you for the ping. 🙇‍♀️

**Comment by desrosj** [comment]
Would it be possible to change the image being dragged at the very top of the screen to something more visually appealing? Every other image on the page is a vibrant flower or a beautiful mountain. But it's not fully apparent what this one is even after looking for a longer moment.

Also, it could at first glance be interpreted as possibly inappropriate because of the colors and shapes.

<img width="722" height="444" alt="Image" src="https://github.com/user-attachments/assets/f78fd227-ffc9-41a6-b5ae-af861d7f69c6" />

The same goes for where it is reused at the bottom of the page:

<img width="402" height="317" alt="Image" src="https://github.com/user-attachments/assets/e643a143-b22e-43dd-9fd7-61c757dfd7b0" />

**Comment by annezazu** [comment]
@fcoveram mind following up on this when you have a chance? I agree this needs to be updated.

**Comment by fcoveram** [comment]
Thanks @desrosj for the suggestion. The one in the microsite needs to have less visual information to not compete with the UI placed over it, so I will look for image that could work in both places. Otherwise, two images.

**Comment by fcoveram** [comment]
Here are two ideas I've been trying with different images. I replaced the one in the microsite's hero section with the one used in the highlight grid for the drag and drop as I see it working well. And the ones in notes in the grid and bind controls in microsite features are different.

I have a preference for the option in the right, but curious about your thoughts.

<img width="3342" height="2495" alt="Image" src="https://github.com/user-attachments/assets/638c4fcc-2632-410a-aa53-817396d765af" />

**Comment by desrosj** [comment]
Thanks for looking at this, @fcoveram! My opinion is that both options here are better than the current image. I think the first one is my personal preference. I like how the "bind controls to external sources" section in the first option does not contain any objects in the background. The shapes and colors draw my attention to that the UI in that screenshot without distracting from it. The Note in the first screen shot also makes mores sense with a colorful image than a more neutral one.

**Comment by fcoveram** [comment]
Sharing the design for the whole page.

<img width="2076" alt="Image" src="https://github.com/user-attachments/assets/6a5f2fe0-dcab-4ec7-9ad1-98dee6d8db91" />

**Comment by jasmussen** [comment]
Thanks, looks great. For those of you with wp.org access, I've now updated the microsite to the above, [here](https://wordpress.org/wp-admin/post.php?post=48239&action=edit). It should be ready on that end.

We'll need a little custom CSS for the videos to look their best, in addition to uploading the actual videos. For the time being, because it seemed the simplest, I have added some CSS helper classes to each video block, these:

```
has-1-1-aspect-ratio has-16px-radius has-custom-controls
```

When paired with the below CSS, it ensures the native video embed has rounded corners, a square aspect ratio (until fullscreen), and the same video controls as for the 6.7 release. Noting that the 6.7 release page also has the 1:1 CSS override, but at some point the custom CSS it was pointing to was removed.

```
.has-1-1-aspect-ratio video {
	aspect-ratio: 1/1 !important;
}

.has-16px-radius video {
	border-radius: 16px;
}


.has-custom-controls video::-webkit-media-controls-panel {
	background: transparent;
	color: var(--wp--preset--color--white);
}

.has-custom-controls video::-webkit-media-controls-fullscreen-button,
.has-custom-controls video::-webkit-media-controls-mute-button,
.has-custom-controls video::-webkit-media-controls-play-button,
.has-custom-controls video::-webkit-media-controls-volume-slider {
	background-color: rgba(0,0,0,0.6);
	border-radius: 24px;
}

.has-custom-controls video::-webkit-media-controls-current-time-display,
.has-custom-controls video::-webkit-media-controls-seek-back-button,
.has-custom-controls video::-webkit-media-controls-seek-forward-button,
.has-custom-controls video::-webkit-media-controls-time-remaining-display {
	background: rgba(0,0,0,0.6);
	color: var(--wp--preset--color--white);
}

.has-custom-controls video::-webkit-media-controls-play-button {
	border-radius: 24px 0 0 24px;
	margin-left: 0;
}

.has-custom-controls video::-webkit-media-controls-current-time-display {
	padding-right: 4px;
}

.has-custom-controls video::-webkit-media-controls-time-remaining-display {
	border-radius: 0 24px 24px 0;
	margin-left: 0;
	padding-right: 18px;
}

.has-custom-controls video::-webkit-media-controls-mute-button,
.has-custom-controls video::-webkit-media-controls-volume-slider {
	border-radius: 24px 0 0 24px;
}

.has-custom-controls video::-webkit-media-controls-fullscreen-button {
	border-radius: 0 24px 24px 0;
}

.has-custom-controls video::-webkit-media-controls-timeline {
	padding-top: 12px;
}

.has-custom-controls video::-webkit-media-controls-volume-slider {
	background-color: transparent;
	padding-left: 8px;
	padding-right: 8px;
}
```

**Comment by fcoveram** [comment]
Nice. Thanks for building it Joen. The last feature's heading was wrong so I updated it. In addition to that, I have a few comments regarding the design that I'm not sure how to apply. I don't want to break anything 😅

### Main image in hero

<img width="2620" height="1422" alt="Image" src="https://github.com/user-attachments/assets/7d0562c7-eb14-48f4-bc6c-f0da8e579b84" />

The main image looks small compared to the design. Perhaps reducing the gap between columns solve this, or overflow the image while keeping the text on the left within the current column width.

### Text balance

<img width="2092" height="1004" alt="Image" src="https://github.com/user-attachments/assets/c514d96a-f634-4fa2-9d24-d39dbf168c95" />

The last word "itself" makes the text to look unbalanced. We could apply a text balance property in the following texts:
1. Description (Below the "Content your way" heading).
2. Description texts in main features (The 4 rows below hero section).
3. Description texts in secondary features (The 6 items in two columns)

### Spacing between texts and images

| Secondary feature section | More details section |
|:---|:---|
| <img width="814" height="360" alt="Image" src="https://github.com/user-attachments/assets/d9a1a1eb-228c-4f8e-abf3-76e13c209e98" /> | <img width="658" height="438" alt="Image" src="https://github.com/user-attachments/assets/04b1148d-c62c-4df8-80b4-97174b7329c5" /> |

The space between texts and images look unbalanced. We could tweak them to reach a more even distribution.

### Icons color

<img width="450" alt="Image" src="https://github.com/user-attachments/assets/04b1148d-c62c-4df8-80b4-97174b7329c5" /> 

I noticed that texts are `Charcoal-3` but icons look like pure black.

**Comment by jasmussen** [comment]
Great feedback, thank you, I'll address all of it. The header feature is perhaps the trickiest one given it needs to be able to scale well across breakpoints, but I'll try some things.

**Comment by jasmussen** [comment]
Working on the feedback:

> The main image looks small compared to the design. Perhaps reducing the gap between columns solve this, or overflow the image while keeping the text on the left within the current column width.

I tried some things:

<img width="1307" height="733" alt="Image" src="https://github.com/user-attachments/assets/251520c4-72ed-4fd3-b6bf-1ef5cfdb3c51" />

The tricky part is ensuring things wrap well on mobile.

> The last word "itself" makes the text to look unbalanced. We could apply a text balance property in the following texts:

This should be handled by `text-wrap: pretty;`, which is applied on the final published site, but not in the editor. This is important because the text has to be slightly fluid to work across breakpoints.

> The space between texts and images look unbalanced. We could tweak them to reach a more even distribution.

Let me know what you think of this

<img width="1171" height="607" alt="Image" src="https://github.com/user-attachments/assets/96d631ff-67a5-4aa4-b616-0399b8325d97" />

> I noticed that texts are Charcoal-3 but icons look like pure black.

Done.


Noting that we are missing these two which I've copied over from earlier versions:

<img width="1400" height="863" alt="Image" src="https://github.com/user-attachments/assets/714197a5-bf37-49cc-ab9e-930dacd0de96" />

**Comment by fcoveram** [comment]
Thanks for the changes. Regarding feedback:
* Hero section looks good
* Applying the `text-wrap: pretty` sounds like a follow-up ticket. Do we need to open it or who can handle that directly without the need for a ticket?
* The space between texts look good
* Icons color looks good

For the two sections you added, do we need to update the contributors number manually? I see on [this slack message](https://wordpress.slack.com/archives/C08MVR1MU2K/p1763537061062159) that stats keep changing until last minute.

**Comment by jasmussen** [comment]
> Applying the text-wrap: pretty sounds like a follow-up ticket. Do we need to open it or who can handle that directly without the need for a ticket?

This is already applied across all of wp.org, so we should be good!

> For the two sections you added, do we need to update the contributors number manually?

I don't think so. It uses a shortcode to grab the numbers from somewhere else. But I'll check!

**Comment by dd32** [comment]
> When paired with the below CSS, it ensures the native video embed has rounded corners, a square aspect ratio (until fullscreen), and the same video controls as for the 6.7 release. Noting that the 6.7 release page also has the 1:1 CSS override, but at some point the custom CSS it was pointing to was removed.

The CSS is still present, but the Gutenberg-sourced CSS or HTML had changed I believe which has made them not quite the same as previously.  The CSS for the 6.7 page was here: https://github.com/WordPress/wporg-main-2022/blob/dc1485406c62f033b9e5f044787e6c2e0ca54d04/source/wp-content/themes/wporg-main-2022/src/style/style.scss#L652-L719

Resolved in https://github.com/WordPress/wporg-main-2022/pull/581

**Comment by annezazu** [comment]
Why isn't the Abilities API featured in any of this? Can we please add that in?

**Comment by jasmussen** [comment]
@dd32 Thanks for updating the CSS, this is 99% there. One additional piece, can you add that? When the video has a square aspect ratio, we also need to adjust the object-fit. So instead of:

```
.has-1-1-aspect-ratio video {
	aspect-ratio: 1/1 !important;
}
```

can you add:

```
.has-1-1-aspect-ratio video {
	aspect-ratio: 1/1 !important;
	object-fit: contain !important;
}
```

**Comment by fcoveram** [comment]
> Why isn't the Abilities API featured in any of this? Can we please add that in?

On it.

**Comment by marko-srb** [comment]
Demos for Microsite. These have just an addition with outro (WordPress logo + 6.9 at the end)

https://github.com/user-attachments/assets/96145296-2bce-44b7-8ecd-8b1f01fdd400
https://github.com/user-attachments/assets/ff0a7971-2aab-430a-9989-0d03560ecc0c
https://github.com/user-attachments/assets/a9a947e8-7a68-4bef-af7d-e67910a9fe50
https://github.com/user-attachments/assets/90986c5b-f476-4abe-adce-d80a3f397ec0
https://github.com/user-attachments/assets/2c718ea9-a39c-4cec-88ba-36d22d18fba4

**Comment by jasmussen** [comment]
These should be uploaded, ready, thank you Marko. 🙏

**Comment by fcoveram** [comment]
> Why isn't the Abilities API featured in any of this? Can we please add that in?

@annezazu. @jasmussen and I tested a few ideas, and replacing the "Maintain settings in DataViews" is the option we like most. The visual reuses the element made for the highlight grid, and can also be used for the announcement post.

Here below is a screenshot of that section. 

<img width="1432" alt="Image" src="https://github.com/user-attachments/assets/11165edf-cd2f-4858-bd84-29b6cb562d82" />

**Comment by annezazu** [comment]
I dig it! Thank you. Let’s drop the “new” at the beginning of the blocks. It’s implied it’s new by being on this page for the release.

**Comment by t-hamano** [comment]
Now that 6.9 is successfully released to the world, let's close this issue 👍
