### ISSUE TITLE
Template activation bugs with plugin-registered templates

### ISSUE THREAD

**Issue by Aljullu** [WordPress/gutenberg#72475]
### Description

While testing the template activation feature with a plugin-registered template in Gutenberg 21.8.2, I found a few issues.

The bugs might be in the Template registration API itself, or I might have done something wrong in my testing. In any case, documenting them here in case they are useful:

### Step-by-step reproduction instructions

1. Add this code to an existing plugin or in a code snippet using the [Code Snippets plugin](https://wordpress.org/plugins/code-snippets/):

```PHP
add_action(
	'init',
	function () {
		register_block_template(
			'gutenberg//plugin-template',
			array(
				'title'       => 'Plugin Template',
				'description' => 'A template registered by a plugin.',
				'content'     => '<!-- wp:template-part {"slug":"header","tagName":"header"} /--><!-- wp:group {"tagName":"main","layout":{"inherit":true}} --><main class="wp-block-group"><!-- wp:paragraph --><p>This is a plugin-registered template.</p><!-- /wp:paragraph --></main><!-- /wp:group -->',
			)
		);
		add_action(
			'category_template_hierarchy',
			function () {
				return array( 'plugin-template' );
			}
		);
	}
);
```

You can optionally also add the snippet below, but I don't think it makes a difference:

```PHP
		add_filter(
			'default_template_types',
			function ( $default_template_types ) {
				$default_template_types['gutenberg//plugin-template'] = array(
					'title'       => 'Plugin Template',
					'description' => 'A template registered by a plugin.',
				);
				return $default_template_types;
			}
		);
```

2. Go to `/category/my-category/` to verify the template is applied correctly:

<img width="1263" height="1060" alt="Image" src="https://github.com/user-attachments/assets/68cf035a-866d-45eb-bc62-4f0a593cbdbc" />

3. Click on _Edit Site_ in the top bar.
4. Now, click on the _Actions_ menu:

<img width="1263" height="1060" alt="Image" src="https://github.com/user-attachments/assets/347e0055-1d75-48dc-9e68-84dafbb7c33b" />

* **Issue 1:** It allows moving the template to trash, but this doesn't seem to make any difference in the frontend: the template keeps being rendered. I believe the editor shouldn't allow moving plugin-registered templates to trash.

5. Go back to `/category/my-category/` and click on _Edit Site_. Make some edits to the template, save and activate the template. Verify they are applied in the frontend.

<img width="1263" height="1060" alt="Image" src="https://github.com/user-attachments/assets/b472d0c0-d345-4f47-9b81-a9c262fd10ad" />

6. Click on _Edit Site_ again.

* **Issue 2:** This brings you to the unmodified template, instead of the template you just edited.

7. Go to _Appearance_ > _Editor_ > _Templates_ > _Active templates_. Open the modified _Plugin Template_, deactivate it and then move it to the trash.
8. Now go to _Appearance_ > _Editor_ > _Templates_ > _Gutenberg_.
9. Activate the plugin template:

<img width="917" height="725" alt="Image" src="https://github.com/user-attachments/assets/ea23261d-242f-417a-b2dc-1b4c6a008bd1" />

* **Issue 3:** Activating a plugin template doesn't seem to do anything. If after activating it you go to _Active templates_, it's not there.

### Environment info

- WordPress 6.9-alpha-60939.
- Gutenberg `trunk`.

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by Aljullu** [comment]
cc @ellatrix in case you can give it a try and see if you can reproduce any of these issues. 🙏 

Also cc @kmanijak for awareness.

**Comment by ellatrix** [comment]
Thank you for the thorough testing!

> It allows moving the template to trash, but this doesn't seem to make any difference in the frontend: the template keeps being rendered. I believe the editor shouldn't allow moving plugin-registered templates to trash.

I believe this is fixed, it's not possible to open an editor for static templates.

And in the list, there's no delete action:

<img width="384" height="260" alt="Image" src="https://github.com/user-attachments/assets/54a9ce91-be34-47de-adfb-deddd47d9011" />

> Issue 2: This brings you to the unmodified template, instead of the template you just edited.

Related: #63785. Perhaps I'm wrong and we should keep this button, but I find it very non beginner friendly. It's very weird that "edit site" takes you in the template editor, I think most users might be looking to edit the title, styles, theme, or navigation, but this button dumps you straight into template editing, which is pretty advanced.

> Issue 3: Activating a plugin template doesn't seem to do anything. If after activating it you go to Active templates, it's not there.

I deleted the duplicate and it does seem to move to active templates now. One note though: the template is wrongly marked as a custom template, which is wrong if it's being registered as a default template. This is something we should fix, cc @mcsf.

<img width="1464" height="955" alt="Image" src="https://github.com/user-attachments/assets/8d6401f1-814a-41db-9000-4aa0dace5ec8" />

**Comment by ntsekouras** [comment]
>It allows moving the template to trash, but this doesn't seem to make any difference in the frontend: the template keeps being rendered. I believe the editor shouldn't allow moving plugin-registered templates to trash.

> > I believe this is fixed, it's not possible to open an editor for static templates.

Not sure if I tested properly, but I encountered the `move to trash` for the plugin template.

**Comment by ellatrix** [comment]
Retested with Beta 2.

> It allows moving the template to trash, but this doesn't seem to make any difference in the frontend: the template keeps being rendered. I believe the editor shouldn't allow moving plugin-registered templates to trash.

This is still an issue. Could we create a separate issue for this?

> This brings you to the unmodified template, instead of the template you just edited.

This seems fixed to me. I edited the template. Edit Site brings me to the edit.

> Activating a plugin template doesn't seem to do anything. If after activating it you go to Active templates, it's not there.

This is fixed as well, BUT if you don't have it added as a default template type (with the filter), it won't appear under active templates.

@Aljullu Could you re-test and move remaining things into separate issues so we can close this?

**Comment by Aljullu** [comment]
Thanks for all your work with this, @ellatrix! 🙌 I gave it another try with WordPress 6.9-beta2 and Gutenberg `trunk`, this is what I noticed:

> Issue 1: It allows moving the template to trash, but this doesn't seem to make any difference in the frontend: the template keeps being rendered. I believe the editor shouldn't allow moving plugin-registered templates to trash.

This is still reproducible on my end:

https://github.com/user-attachments/assets/41a49eed-d930-4bc8-a010-c5523ff67bb4

> Issue 2: This brings you to the unmodified template, instead of the template you just edited.

✔️ This has been fixed. It now correctly redirects to the modified template.

> Issue 3: Activating a plugin template doesn't seem to do anything. If after activating it you go to Active templates, it's not there.

✔️ This has been fixed. The actions menu is disabled, so templates from plugins can't be activated.

---

So apparently only issue 1 remains. Let me know if you can't reproduce it or if I can help in any way. 🙂

**Comment by ellatrix** [comment]
Yep, I mentioned number 1 this was still an issue, perhaps we can open a new issue for just that. Or let me try to fix it now quickly

**Comment by Aljullu** [comment]
> Yep, I mentioned number 1 this was still an issue, perhaps we can open a new issue for just that. Or let me try to fix it now quickly

Ups, sorry, I just missed that from your comment. 🤦‍♂️ I just approved your PR!
