### ISSUE TITLE
Notice Component Actions: Missing Features and Limitations

### ISSUE THREAD

**Issue by manzoorwanijk** [WordPress/gutenberg#74090]
## What problem does this address?

The `Notice` component's action buttons have several limitations that restrict their functionality in real-world use cases, as we have seen while working in [Jetpack](https://github.com/Automattic/jetpack). I'm always frustrated when I need to use common button features like disabled states, loading indicators, or icons in notice actions, but they're not supported even though the underlying `Button` component supports them.

The current implementation has the following problems:

### 1. No Support for Disabled State

Action buttons cannot be disabled, which is problematic when an action is temporarily unavailable or being processed.

**Current behavior:**
```tsx
<Notice
  status="info"
  actions={[
    {
      label: "Save Changes",
      onClick: handleSave,
      // No way to disable this while saving
    }
  ]}
>
  Settings updated
</Notice>
```

### 2. No Support for Custom Button Size

The dismiss button uses `size="small"` (line 171), but action buttons don't support size customization, leading to inconsistent sizing options.

**Current behavior:**
```tsx
// Action buttons are always default size (40px with __next40pxDefaultSize)
<Notice
  actions={[
    {
      label: "Action",
      onClick: handleAction,
      // No size prop available
    }
  ]}
/>
```

### 3. onClick Ignored When URL is Provided

When both `url` and `onClick` are provided, the `onClick` is completely ignored. This prevents tracking analytics, confirmation dialogs, or handling link clicks with JavaScript.

**Current behavior:**
```tsx
<Notice
  actions={[
    {
      label: "View Details",
      url: "/details",
      onClick: (e) => {
        // This onClick is NEVER called because url takes precedence
        trackAnalytics('notice_action_clicked');
      }
    }
  ]}
/>
```

### 4. No Support for Icon Buttons

Action buttons cannot include icons, which would improve visual clarity and accessibility.

### 5. No Support for Loading State

Actions cannot show loading indicators when processing asynchronous operations.

### 6. No Support for Tooltip/Help Text

Actions cannot provide additional context via tooltips.

### 7. Missing `openInNewTab` Implementation

The [type definition includes `openInNewTab?: boolean` for `NoticeActionWithURL`](https://github.com/WordPress/gutenberg/blob/653421112847f1c8bdaa688bc873f8421c877c69/packages/components/src/notice/types.ts#L17), but it's never used in the implementation. The `href` prop is passed to Button without `target="_blank"` or `rel="noopener noreferrer"`.

**Current behavior:**
```tsx
<Notice
  actions={[
    {
      label: "External Link",
      url: "https://example.com",
      openInNewTab: true, // This prop exists in types but does nothing!
    }
  ]}
/>
```

### Impact

These limitations force us at Jetpack to:
- Create custom notice implementations when we need these features
- Use workarounds that may not be accessible or consistent with design patterns
- Miss opportunities for better UX (loading states, disabled states, icons, etc.)

## What is your proposed solution?

Enhance the `NoticeAction` types to include commonly used Button props that are currently missing:

```tsx
type CommonNoticeActionProps = {
  label: string;
  className?: string;
  noDefaultClasses?: boolean;
  variant?: 'primary' | 'secondary' | 'link';
  disabled?: boolean;
  size?: 'default' | 'compact' | 'small';
  icon?: JSX.Element;
  iconPosition?: 'left' | 'right';
  iconSize?: number;
  isBusy?: boolean;
  isDestructive?: boolean;
  tooltipPosition?: ComponentProps<typeof Button>['tooltipPosition'];
  text?: string;
};
```

Update the implementation to:

1. **Pass through all supported props** to the underlying `Button` component instead of only passing a subset
2. **Properly implement `openInNewTab`** by setting appropriate `target` and `rel` attributes when this prop is true
3. **Allow `onClick` to be called even when `url` is provided** (matching the behavior of the `Button` component), enabling analytics tracking, confirmation dialogs, and custom link handling
4. **Forward all other relevant Button props** like `disabled`, `size`, `icon`, `isBusy`, etc.

### Example of expected usage after fix:

```tsx
<Notice
  status="success"
  actions={[
    {
      label: "Save Changes",
      onClick: handleSave,
      disabled: isSaving,
      isBusy: isSaving,
      icon: saveIcon,
      variant: "primary"
    },
    {
      label: "Learn More",
      url: "https://example.com/docs",
      openInNewTab: true,
      onClick: () => trackAnalytics('docs_clicked'),
      icon: externalIcon,
      size: "small"
    }
  ]}
>
  Settings updated successfully
</Notice>
```

This would make Notice actions as flexible and feature-rich as standalone Button components, while maintaining consistency across the component library.

**Comment by ciampo** [comment]
Hey folks, slowly ramping up on @WordPress/gutenberg-components  -related work after having been away for a few months.

My main piece of feedback is: given the planned efforts for the `@wordpress/ui`package and the new re-designed set of components which will include a new `Notice` version, we need to make sure that:

- we spend time and efforts where it matters the most;
- we only introduce changes that will apply to the new version of the component (both design-wise and feature/API wise);

In other words, quick wins and fixes are welcome (such as supporting `onClick`, fixing `openInNewTab` and allowing disabled buttons), but I'd be cautious in opening up more "design freedom" such as different button sizes / variants (including icons). 

I'll let the rest of @WordPress/gutenberg-components @WordPress/gutenberg-design  also advise on this one.

**Comment by manzoorwanijk** [comment]
Then an alterntavie solution which is future proof and may be follows the new UI guidelines is to start supporting actions via composition, which means that actions could be a `React.ReactNode` which is rendered directly without looping.

```tsx
<Notice
	status="info"
	actions={
		<>
			<Button variant="primary">Save</Button>
			<Button variant="primary" disabled>Retry</Button>
		</>
	}
>
	Your changes have not been saved yet.
</Notice>
```

**Comment by mirka** [comment]
> In other words, quick wins and fixes are welcome (such as supporting `onClick`, fixing `openInNewTab` and allowing disabled buttons), but I'd be cautious in opening up more "design freedom" such as different button sizes / variants (including icons).

I agree. Those "quick fix" changes are a no-brainer, and we can merge them quickly. The bigger changes for design customization, passing through props, or supporting modularity is a lot more complex since they have knock-on effects. I don't even think we _want_ to open up full customization here? Notices are a "public space" where different tenants post content, and too much divergence between them is going to take a certain toll on the users.

@manzoorwanijk Could you maybe split out the non-controversial changes so we can ship them first?

**Comment by manzoorwanijk** [comment]
What do you folks think about the alternative solution I proposed above https://github.com/WordPress/gutenberg/issues/74090#issuecomment-3681296174?

> Could you maybe split out the non-controversial changes so we can ship them first?

I have updated the PR though.

**Comment by mirka** [comment]
> What do you folks think about the alternative solution I proposed above [#74090 (comment)](https://github.com/WordPress/gutenberg/issues/74090#issuecomment-3681296174)?

This kind of modular API is the general direction we are headed in `@wordpress/ui`, but for certain things we intentionally tighten restrictions on customization to maintain consistency instead. We'll have to do some thinking with designers to decide whether we want to open up this kind of customization in the `@wordpress/ui` `Notice`. In any case I don't think we can do it in `@wordpress/components` at this juncture.

**Comment by SirLouen** [comment]
@ciampo wrote:
> My main piece of feedback is: given the planned efforts for the `@wordpress/ui`package and the new re-designed set of components which will include a new `Notice` version, we need to make sure that

I'm a little confused about the separation between components and UI elements. Is there an informational piece of content regarding this topic? Are UI elements just a 2.0 version of current components to avoid BC or something? I always thought that the admin UI was going to be built around current components, so I'm a little confused atm.

**Comment by ciampo** [comment]
> I'm a little confused about the separation between components and UI elements. Is there an informational piece of content regarding this topic? Are UI elements just a 2.0 version of current components to avoid BC or something? I always thought that the admin UI was going to be built around current components, so I'm a little confused atm.

Main relevant issues/PR:
- https://github.com/WordPress/gutenberg/issues/71196
- https://github.com/WordPress/gutenberg/pull/72305
- https://github.com/WordPress/gutenberg/pull/72984

**Comment by SirLouen** [comment]
> * [Design System: Support for admin redesign #71196](https://github.com/WordPress/gutenberg/issues/71196)
> * [Add `theme` package #72305](https://github.com/WordPress/gutenberg/pull/72305)
> * [UI: Implement Box component as part of new UI package #72984](https://github.com/WordPress/gutenberg/pull/72984)

Despite reading #71196 some months ago, I'm still unable to grasp how the challenges that Andrew commented, are not going to appear again after this “new” implementation. I'm seeing (and foreseeing) a good amount of code duplication.

For example, `RangeControl` slider component is going to be identical to `Slider` primitive. If we only wanted abstraction and the core functionality, it could have been perfectly abstracted from `RangeControl`, something like `core.ts` and used from there. 

For example, challenges, like this:
> Locked to specific implementation details: Current reliance on CSS-in-JS introduces runtime performance costs, and this cannot be easily removed.

Could be part of such abstraction process. But maintaining just 1 component for all, is way simpler, than having two replicas. And this is going to apply for a good amount of elements all over the place.

Some months ago, I asked how the "New Admin Interface" could be called, and given how it's being unfolded, it feels that the perfect name will be `Gutenberg UI` (and at some point Gutenberg will replace WordPress all-over 😅)

**Comment by aduth** [comment]
As it relates to the original issue, my interpretation of @ciampo's comment regarding `@wordpress/ui` and an evolved set of components with this `Notice` in particular ties back to the point in #71196 around API inconsistencies and composition, where [newer conventions around compound components](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CONTRIBUTING.md#compound-components) didn't exist at the time that `Notice` was originally developed, but would be how we'd consider this type of subcomponent customization if done over today. 

The differences won't always be quite so drastic for some components as compared to others, but the goal being to have a consistent set of components that build on shared design language. And doing so in a future-compatible way that avoids tying our hands in the future (i.e. unlocking the potential for breaking changes through package versioning). Duplication is not ideal from either a consumer's or maintainer's perspective, so we'll want to be clear to have one canonical implementation as much as possible, possibly updating existing implementations to use newer equivalents.

**Comment by SirLouen** [comment]
> The differences won't always be quite so drastic for some components as compared to others, but the goal being to have a consistent set of components that build on shared design language. And doing so in a future-compatible way that avoids tying our hands in the future (i.e. unlocking the potential for breaking changes through package versioning). Duplication is not ideal from either a consumer's or maintainer's perspective, so we'll want to be clear to have one canonical implementation as much as possible, possibly updating existing implementations to use newer equivalents.

It's easy to quickly see how dupes are already and will be popping up all over the place, like:

https://github.com/WordPress/gutenberg/blob/8604a8bb08945c7903279b8ae07a25b9ba54e510/packages/components/src/badge/index.tsx
https://github.com/WordPress/gutenberg/blob/f849572b5558f1c82768ce4aad74c463d7f18ab2/packages/ui/src/badge/index.ts

I would bet that for every single UI element there is going to be a component counterpart for the next 2 or 3 years of development.

But since I don't have the full background, I assume that fixing the current status of the components is almost impossible, if not totally impossible, because of BC, like I commented.

> Are UI elements just a 2.0 version of current components to avoid BC or something?

With this, I think I've got the full picture now 👍
What I want to see now is how all these new components are going to be overcome all the challenges that were commented on here #71196
