### ISSUE TITLE
"This block has encountered an error and cannot be previewed."

### ISSUE THREAD

**Issue by k2art** [WordPress/gutenberg#8936]
Wow! Gutenberg is totally useless! Can't post anything to my website blog. When I click to open a new block, an error appears that says: "This block has encountered an error and cannot be previewed." Thanks, Wordpress/Gutenberg... you've managed to do what no hacker has been able to do... disable my website so that I can't post anymore!!!

**Comment by designsimply** [comment]
Hi @k2art. First of all, thank you for opting in to test Gutenberg and apologies you're seeing a problem like that! The error you mentioned sounds like it might be a plugin conflict of some kind. For example, someone recently posted to say they saw a similar error that was resolved by updating to the latest version of the Advanced Custom Fields plugin (https://github.com/WordPress/gutenberg/issues/8866#issuecomment-412269018). Do you happen to have ACF installed and can you check to see if you are running the latest version? If you don't, may I ask what other plugins you are using? Plesk hosting is another example where a conflict occurs with certain configurations of their their security add-on (https://github.com/WordPress/gutenberg/issues/8099#issuecomment-406892450).

If possible, are you able to check your browser console to see what error appears when you open a new block? More information is needed to troubleshoot this issue, and the console errors may help give us some information about what the source of the trouble could be.

**Comment by k2art** [comment]
I don't have any of the plug-ins you mentioned. My site is very simple and was perfectly fine before the latest update of Wordpress. If Gutenberg is going to be forced on us, I hope you get this thing working regardless of whatever plug-ins anyone adds. The ones I do have have all worked fine on my site for years. I need this fixed ASAP so I can continue to post to my website... it's going on four days since I've posted last. Please update me with anything I can do to remedy this.

**Comment by designsimply** [comment]
Are you able to check your browser console to see what error appears when you open a new block? It may help narrow down the source of the problem or give some clues about which plugin might be causing trouble if it does turn out to be a plugin conflict.

You could also list your plugins here for reference. Note that once a plugin conflict is found, the best route from there may be to ask you to contact the plugin developer to help and include whatever troubleshooting information you can think of we can find here that be helpful for them.

**Comment by k2art** [comment]
I have no idea how to open a console in Safari. I'm not a programmer or coder, either, so my knowledge of how to dig into this is limited.

The list of active Plug Ins I have are:
Akismet
Anti-Spam by CleanTalk
Clicky Analytics
Column Shortcodes
Contact Bank
Gutenberg
Maintenance (which is turned off)
Printful Integration for Woo Commerce
Search Engine Visibility
Woo Commerce
Wordfense Security
Wordpress Importer
Yoast SEO

That's it. As I mentioned earlier, no problems existed before this latest Wordpress Update. The Classic Editor would not work, so I switched to Gutenberg, hoping it would, but it doesn't. I hope you can identify the problem and get me back up and running soon.

Thanks.

**Comment by k2art** [comment]
Hi, I just updated to the latest edition of Gutenberg and I am still encountering the same issue: "This block has encountered an error and cannot be previewed."

**Comment by k2art** [comment]
I tried that and it still says, "This block has encountered an error and cannot be previewed."

I also deactivated several other plug-ins and tried adding a block after deactivating each one... nothing.

**Comment by Totill0** [comment]
Hello, i installed the Guttember plugin and have the same issue. 

The console shows:

> _tinymce-plugin-lists.min.137fa94a.js:1

>  Uncaught ReferenceError: tinymce is not defined
>     at tinymce-plugin-lists.min.137fa94a.js:1
>     at tinymce-plugin-lists.min.137fa94a.js:1
> tinymce-plugin-paste.min.f6e82d7a.js:1 Uncaught ReferenceError: tinymce is not defined
>     at tinymce-plugin-paste.min.f6e82d7a.js:1
>     at tinymce-plugin-paste.min.f6e82d7a.js:1
> tinymce-plugin-table.min.3fa6c17e.js:1 Uncaught ReferenceError: tinymce is not defined
>     at tinymce-plugin-table.min.3fa6c17e.js:1
>     at tinymce-plugin-table.min.3fa6c17e.js:1
> react-dom.min.82e21c65.js:110 TypeError: Cannot read property 'init' of undefined
>     at t.value (index.js?ver=1534771270:12)
>     at t.value (index.js?ver=1534771270:12)
>     at jc (react-dom.min.82e21c65.js:134)
>     at gc (react-dom.min.82e21c65.js:127)
>     at vb (react-dom.min.82e21c65.js:126)
>     at ub (react-dom.min.82e21c65.js:126)
>     at zd (react-dom.min.82e21c65.js:124)
>     at ra (react-dom.min.82e21c65.js:123)
>     at Object.enqueueSetState (react-dom.min.82e21c65.js:189)
>     at e.q.setState (react.min.ab6b06d4.js:18)_
> 
At the moment i can use the classic editor, but without it i can´t be able to post anymore.

THANKS

**Comment by Totill0** [comment]
i tried with Mac OS and Windows 10.

Desacticvate all plugins.

Tried safari, mozilla and Chrome

It still failing 

Anybody can help me??

**Comment by k2art** [comment]
Coming up on three weeks since I've been able to post to my blog and now this thread has gone silent. I need this issue resolved. My website is DEAD! I can't even use the Classic Editor since the latest update of Wordpress was released.

**Comment by youknowriad** [comment]
I opened the #9373 PR that might fix all these issues. I'd appreciate help in testing this PR since I can't reproduce the issue myself. Thanks

**Comment by youknowriad** [comment]
closed by #9373 

Feel free to raise again if it's still happening after the release of 3.7
