### ISSUE TITLE
Block validation error for 'viewbox' attribute

### ISSUE THREAD

**Issue by Michael-Ashfield** [WordPress/gutenberg#9898]
**Describe the bug**
Gutenberg returns a block validation error when using the viewbox attribute in an inline svg when using the custom HTML block

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a custom HTML block
2. Add an inline svg that uses the viewbox attribute
3. Leave and comeback to the editor
4. The block will now display as 'externally modified' and will show an error in the developer console:
"Block validation: Encountered unexpected attribute `viewbox`."

**Expected behavior**
I expected any content I enter into the custom HTML block to be regarded as valid *wether it is valid HTML or not* as I develop custom HTML my way, at the least for valid attributes to not bring up errors.

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6
 - Browser: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
 - Gutenberg Version: Version 3.8.0 
 - Server: MAMP 4.4.1 (local host)

Extra context:
There are other unrelated errors reported on my page due to the absence of any container block, meaning that I have to place a rogue "`<div class='my-container'> `" above a set of blocks, then close it in a separate HTML element "`</div> <!-- closes my-container --> `" below the blocks, this is a hacky work around which produces invalid HTML errors, however they should not affect the viewbox error, as they are just expected errors looking for closing/opening tags.

**Comment by Michael-Ashfield** [comment]
To be clear, this is not a help request, I am reporting a bug. The viewbox attribute is in the SVG2 specification, SVG1.1 (second edition) and is described in detail in the Mozilla Web Docs.

In addition, after further digging, I found multiple issues with Gutenberg and SVGs.
Gutenberg will throw errors for valid SVG attributes claiming they must be lowercase, when infact they are camelcase in the specs (For example "linearGradient" will throw an error saying it must be "lineargradient" which is wrong). This error is pointed out in the edit but not the console it seems, however when it the attribute is lowercase, it is reported as an error in the console.

Gutenberg will also take issue with self closing elements in SVGs, which are used extensively in any SVG asset and is perfectly valid and inline with the specs(Paths for example ares elf closing). This is further heightened by the fact that the suggested closing tags ("</path>" "</rect>" e.c.t.) are invalid and will cause even more issues. It is an issue in the console if you don't close the tags and an issue in the editor if you do close them.

SVGs seem to be a wider issue in the custom HTML editor block, upon further inspection. There is a distinct lack of communication between the console reported errors and what the frontend reports as errors, it is a lose-lose situation when trying to use inline SVGs.
This has been tested on a fresh install.

Sources:
- https://svgwg.org/svg2-draft/coords.html#ViewBoxAttribute
- https://www.w3.org/TR/SVG11/coords.html#ViewBoxAttribute
- https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox
- https://www.w3.org/TR/SVG/paths.html

**Comment by chrisvanpatten** [comment]
I've been experiencing similar issues today. SVG code inside HTML blocks are being interpreted as invalid/externally modified blocks on a page refresh.

**Comment by johngodley** [comment]
This should be fixed in #10474. Note that an SVG is still likely to be transformed in some way, and this is being looked at in #10551. Marking this as fixed as the invalid block warning is no longer shown.

**Comment by jshwlkr** [comment]
I seem to be experiencing this issue in WP 5.2.2. ( Which is Gutenberg 6.1.0 I think?) Both in the custom HTML block and in a custom block with hardcoded SVGs.

**Comment by aduth** [comment]
@firxworx I agree this should not be considered an invalidation. For that task, I have opened #18266 

As for the markup produced by Gutenberg: There is an issue at #12932 with some additional context. It's still unclear to me whether it makes a significant difference to output in lower-case. A workaround is possible for hyphened attributes to include the hyphen in the rendered element. That all being said, this seems like an easy pitfall, especially with the inconsistency from React, and I'd be inclined to reopen that issue.

**Comment by johnstonphilip** [comment]
I ran into this today on WP 5.7. It seems this is still an active bug, both that it transforms `viewBox` to `viewbox`, and also that it causes invalidation of the block.

**Comment by iamleese** [comment]
As of September 16, 2021 - this is still an issue. It seemed to have been resolved sometime at the end of 2020 but has reappeared.

**Comment by cmorgannorris** [comment]
Just ran into this issue when using FontAwesome JS on some blocks.
